### ISSUE TITLE
Bookkeeper-server shaded artifact test fail on branch-4.6

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#1003]
if I run on branch-4.6
`mvn clean install`

I get this error:

```
Running org.apache.bookkeeper.tests.shaded.BookKeeperServerShadedArtifactTest
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.104 sec <<< FAILURE! - in org.apache.bookkeeper.tests.shaded.BookKeeperServerShadedArtifactTest
testProtobufIsShaded(org.apache.bookkeeper.tests.shaded.BookKeeperServerShadedArtifactTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: java.lang.ClassNotFoundException


Results :

Failed tests: 
  BookKeeperServerShadedArtifactTest.testProtobufIsShaded Expected exception: java.lang.ClassNotFoundException
```

**Comment by eolivelli** [comment]
odd fact:
if I run the tests inside this directory, all runs fine
bookkeeper/tests/backward

I think it is due to the use of Maven Reactor

when running tests inside "tests" all modules will load dependencies from "target/classes" directory, which is empty for bookkeeper-server-compat-4.0.0 (and other directories)

when running a single project dependencies are taken from .m2

**Comment by eolivelli** [comment]
@sijie do you think this is a blocker for release ?

Somehow tests pass, it is a problem of the global configuration of the poms and we are refactoring all of this in 4.7

**Comment by eolivelli** [comment]
if I run 
`mvn clean install`
the problems does not occur on backward tests, so it is not a show stopper for release.

Anyway I get another problem and this a blocker, to be fixed
```
Running org.apache.bookkeeper.tests.shaded.BookKeeperServerShadedArtifactTest
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.104 sec <<< FAILURE! - in org.apache.bookkeeper.tests.shaded.BookKeeperServerShadedArtifactTest
testProtobufIsShaded(org.apache.bookkeeper.tests.shaded.BookKeeperServerShadedArtifactTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: java.lang.ClassNotFoundException


Results :

Failed tests: 
  BookKeeperServerShadedArtifactTest.testProtobufIsShaded Expected exception: java.lang.ClassNotFoundException

```

**Comment by eolivelli** [comment]
Just for completeness....the best command to test the full suite is
`mvn verify`

**Comment by sijie** [comment]
https://builds.apache.org/job/bookkeeper_release_branch/31/

this CI is running against branch-4.6. I didn't see BC tests are failing. 

> BookKeeperServerShadedArtifactTest.testProtobufIsShaded Expected exception: java.lang.ClassNotFoundException

I think maven includes protobuf in test classpath. with shading plugin, you have to run the tests from root directory, otherwise you will get weird behavior. so if you want to verify the build, please run from the root directory, rather from tests directory, or use the CI build result.

And I don't think this is a blocking issue for 4.6.1

**Comment by eolivelli** [comment]
closed with https://github.com/apache/bookkeeper/commit/807678c78468db3d40c7a2ccfc9c0cdbb1cc5f66
