### ISSUE TITLE
BC test cleanup

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#1030]
See https://github.com/apache/bookkeeper/pull/1028#discussion_r162941741

- [x] Move all backwards compat tests under a common directory
- [x] Also move tests into a backward-compat java package.
- [x] close all classloaders in groovy tests
- [x] Add pointers on running arquillian tests
- [x] Add integration tests to CI

**Comment by ivankelly** [comment]
Also move tests into a backward-compat java package.

**Comment by ivankelly** [comment]
Also, close all classloaders in groovy tests

**Comment by eolivelli** [comment]
Currently we have a directory named 'tests', what about renaming it 'ittests' o 'itests' (for ' integration tests')

**Comment by ivankelly** [comment]
It would be under a common directory under tests, likes tests/backwards-compat

**Comment by sijie** [comment]
This issue has been addressed by all the subtasks linked above
