### ISSUE TITLE
Problems with the download page

### ISSUE THREAD

**Issue by sebbASF** [apache/bookkeeper#1090]
The download page
https://bookkeeper.apache.org/releases/
currently links to the KEYS file using the URL
https://dist.apache.org/repos/dist/release/bookkeeper/KEYS

The dist.apache.org host is only intended for ASF developers to stage/publish releases and is not intended for use by people downloading releases.

Please change the URL to 
https://www.apache.org/dist/bookkeeper/KEYS

Also, the download page should have links to the sigs and hashes.
These must use URLs with the base:
https://www.apache.org/dist/bookkeeper/

**Comment by sijie** [comment]
@sebbASF will work on addressing this.

**Comment by sijie** [comment]
@sebbASF we've addressed the concerns about the download page: http://bookkeeper.apache.org/releases/

do you mind taking a look to see if there is anything we missed there?

**Comment by sebbASF** [comment]
I think the following sentence should be deleted:
"Releases can be downloaded from BookKeeper’s Apache mirrors site or using the instructions below."

It is confusing (and redundant) given that the instructions below also point to the same mirrors.

Otherwise the problems I raised have been addressed; thanks
