### ISSUE TITLE
Use loopback network interface for testcases.

### ISSUE THREAD

**Issue by reddycharan** [apache/bookkeeper#1107]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Use loopback network interface for testcases.

- tests would be more reliable irrespective of the environment, if the loopback address is used in testsuites.
- unless loopback address is set explicitly, in my env (while on company's VPN), UpdateCookieCmdTest is failing most of the times.
- currently allowLoopback is set to true in BookKeeperClusterTestCase, it doesn't make Bookies to use loopback interface address.
- loopback network interface should be set explicitly as listening interface to use loopback address.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

This is needed for test envs. / testsuites to be reliable.

**Comment by sijie** [comment]
This is fixed by #1097
