### ISSUE TITLE
A lot of underreplicated ledgers occur when periodic check run

### ISSUE THREAD

**Issue by hrsakai** [apache/bookkeeper#1197]
**BUG REPORT**
- What did you do?
After every bookkeeper periodic check, thousands of  ledgers become underreplicated.
Although most of them will disappear from the underreplicated list, one or several ledgers remain in the list.
We need to restart all bookies to clean the underreplicated list when the above happen.
```
11:22:03.781 [AuditorBookie-XX.XX.XX.XX:3181] INFO  o.a.bookkeeper.replication.Auditor   - Running periodic check
```

<br>

- What did you expect to see?
No ledgers become underreplicated and if ledgers become underreplicated, they should  recover successfully.

<br>

- What did you see instead? 
A lot of underreplicated ledgers occurred and some of them remained.

<br>
Do you know what could be happening? 

If you have any ideas, please let us know.

System configuration
BookKeeper version : 4.3.1.83-yahoo
Number of Bookies: 3
Ensemble size: 2
Write quorum size: 2
Ack quorum size: 2
priodic check interval: 1week

**Comment by hrsakai** [comment]
@sijie 
Yes, that's right.

**Comment by sijie** [comment]
@hrsakai can you share more logs by any chance?

**Comment by hrsakai** [comment]
@sijie 
These are auditor logs when a lot of ledgers were marked as underreplicated.
[replicator.2018-02-12_1.txt](https://github.com/apache/bookkeeper/files/1747206/replicator.2018-02-12_1.txt)
[replicator.2018-02-12_2.txt](https://github.com/apache/bookkeeper/files/1747209/replicator.2018-02-12_2.txt)


And following is metadata of the ledger that remained in underreplicated list.
```
ledgerID: 1385659
BookieMetadataFormatVersion	2
quorumSize: 2
ensembleSize: 2
length: 73284
lastEntryId: 123
state: CLOSED
segment {
  ensembleMember: “xx.xx.xx.12:3181"
  ensembleMember: “xx.xx.xx.11:3181"
  firstEntryId: 0
}
digestType: CRC32
password: ""
ackQuorumSize: 2
```

```
$ grep -h 1385659 ./replicator.2018-02-12_1.txt replicator.2018-02-12_2.txt
13:04:57.341 [AuditorBookie-xx.xx.xx.10:3181-EventThread] INFO  o.a.b.meta.AbstractZkLedgerManager   - Registered ledger metadata listener ReadOnlyLedgerHandle(lid = 1385659, id = 414721325) on ledger 1385659.
13:04:57.341 [main-EventThread] INFO  o.a.b.meta.AbstractZkLedgerManager   - Unregistered ledger metadata listener ReadOnlyLedgerHandle(lid = 1385659, id = 414721325) on ledger 1385659.
13:05:23.537 [BookKeeperClientWorker-114-1] INFO  o.a.bookkeeper.replication.Auditor   - Following ledgers: [1385659] of bookie: xx.xx.xx.11:3181 are identified as underreplicated
13:05:23.542 [BookKeeperClientWorker-114-1] INFO  o.a.bookkeeper.replication.Auditor   - Following ledgers: [1385659] of bookie: xx.xx.xx.12:3181 are identified as underreplicated
```

Are there any other required logs?

**Comment by hrsakai** [comment]
This issue has been fixed when we changed settings:
```
verificationPercentage=20 (from 100)
maxPendingReadRequestsPerThread=50000 (from 30000)
rereplicationEntryBatchSize=50 (from 5000)
readEntryTimeoutSec=40 (from 20)
throttle=15 (from 5000)
```
