### ISSUE TITLE
Please delete old releases from mirroring system

### ISSUE THREAD

**Issue by sebbASF** [apache/bookkeeper#1213]
To reduce the load on the ASF mirrors, projects are required to delete old releases [1]

Please can you remove all non-current releases?
It's unfair to expect the 3rd party mirrors to carry old releases.

It looks to me as though the following releases are have been superseded:

4.6.0
4.5.0
4.4.0
distributedlog/0.4.0-incubating/

Please delete these from

https://dist.apache.org/repos/dist/release/bookkeeper/

Note that older releases can still be linked from the download page, but such links should use the archive server at:

http://archive.apache.org/dist/bookkeeper/

Thanks!

[1] http://www.apache.org/dev/release.html#when-to-archive

**Comment by sijie** [comment]
@sebbASF I have deleted the old releases and will update the download page.

**Comment by sebbASF** [comment]
Please also update any release documentation to ensure that old releases are tidied after future releases.
It's best to do this just after sending the announce for the new release.

Also it's best to update the download page to point to the archives before deleting the dist/release directory so the links don't break.

**Comment by sijie** [comment]
yeah. I am sending a PR to change the download page and will update the release guide as well.

**Comment by sijie** [comment]
@sebbASF both release page and download page are updated. Closing this issue now.

**Comment by sebbASF** [comment]
It's long since time to delete 4.7.1 please

**Comment by eolivelli** [comment]
Okay will do. Sorry for delay @sebbASF

I will check/update the release procedure as well
