### ISSUE TITLE
remove old Codahale in package `org.apache.bookkeeper.stats`

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#1262]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
This is a followed task for #762 ,  which aimed to remove old Codahale in package `org.apache.bookkeeper.stats` in release 4.8.0

```
Codahale stats providers are sharing same package name with the stats library `org.apache.bookkeeper.stats`. We should consider moving them to their own package name.
Codahale => `org.apache.bookkeeper.stats.codahale`

For BC concerns, we need to do this in two phases:

- in 4.7, we copy the files but still have the old files for BC. but mark the old classes as deprecated.
- in 4.8, we remove the old files.

because the class names are used for reflection.
```
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*should-have*

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by Ghatage** [comment]
@jiazhai It seems this work was done in https://github.com/apache/bookkeeper/issues/762.
Only thing remaining is to remove the deprecated code from `org.apache.bookkeeper.stats`.
What do you recommend we do next?

**Comment by Ghatage** [comment]
Mailing list conversation: [Thread](http://mail-archives.apache.org/mod_mbox/bookkeeper-dev/202010.mbox/browser)
