### ISSUE TITLE
closing channel with wait in a netty thread can lead to deadlock

### ISSUE THREAD

**Issue by kishorekasi** [apache/bookkeeper#1334]
**BUG REPORT**
https://github.com/netty/netty/issues/140  
channel.close from the io thread can lead to problems.

We can try submitting close as a task to OrderedSafeExecutor or try close without wait.

**Comment by shoothzj** [comment]
Thanks for your report, closed by netty has fixed that bug. https://github.com/netty/netty/issues/140#issuecomment-3701297

> If you call Channel.close() a downstream event will get fired. The event will then processed and finally close the channel. After the channel is closed it trigger an upstream event to notify about the closed channel. The problem is that this event will NOT get executed in the IO-Thread and so its possible to see a race-condition. This need to get fixed as this is a "global" problem.
