### ISSUE TITLE
build failure ...

### ISSUE THREAD

**Issue by ack72tdp** [apache/bookkeeper#1357]
Any thoughts on build failure ...?

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:01 min
[INFO] Finished at: 2018-04-18T18:13:18-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project twitter-science-provider: Could not resolve dependencies for project org.apache.bookkeeper.stats:twitter-science-provider:jar:4.7.0-SNAPSHOT: Failed to collect dependencies at com.twitter.common:stats:jar:0.0.64: Failed to read artifact descriptor for com.twitter.common:stats:jar:0.0.64: Could not transfer artifact com.twitter.common:stats:pom:0.0.64 from/to twitter (http://maven.twttr.com): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :twitter-science-provider

**Comment by yafengw** [comment]
Set the env varialbe BENCHMARK_EXTRA_CLASSPATH, then try to execute ./benchmark writes -help .

export BENCHMARK_EXTRA_CLASSPATH=/usr/local/share/bookkeeper-4.7.0/bookkeeper-benchmark/target/bookkeeper-benchmark-4.7.0.jar

**Comment by ack72tdp** [comment]
It could .. I guess.. I did similar thing to workaround ... export BENCHMARK_EXTRA_OPTS="-Dorg.apache.bookkeeper.conf.readsystemproperties=true -DzkLedgersRootPath=/bookkeeper/ledgers"

**Comment by ack72tdp** [comment]
Although build problem ... I haven't verified .. and it might still exists ..
