### ISSUE TITLE
Size-based throttling in Bookie side

### ISSUE THREAD

**Issue by ArvinDevel** [apache/bookkeeper#1367]
feature request

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Size based throttling in Bookie side

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
nice-to-have

3. Provide any additional detail on your proposed use case for this feature.
Current bookie use `maxPendingAddRequestsPerThread` to limit server request processor‘s writing capacity, which can't deal different request size gracefully, and we can't setting it according to server resource accurately. In my test case, I have to change this setting to avoid the `TooManyRequestsException`.

**Comment by dlg99** [comment]
see https://github.com/apache/bookkeeper/issues/1409 / https://github.com/apache/bookkeeper/pull/1410
