### ISSUE TITLE
Size based throttling on client side

### ISSUE THREAD

**Issue by ArvinDevel** [apache/bookkeeper#1368]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Size based throttling in Bookie side

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
nice-to-have

3. Provide any additional detail on your proposed use case for this feature.
BookKeeper client throttle setting is limited to entry number throttle , that means we can't setting it according to client resource accurately. In my test case, I have to decrease it when entry size increase, otherwise client will see add-request timeout error, or disconnect with bookie.

**Comment by dlg99** [comment]
I think this is covered in fix to https://github.com/apache/bookkeeper/issues/1086 see https://github.com/apache/bookkeeper/pull/1088

**Comment by ArvinDevel** [comment]
@dlg99 thanks!
