### ISSUE TITLE
addBookieAndCheckCovered in RRQuorumCoverageSet doesn't work correctly if AcqQuorumSize is greater than (WriteQuorumSize+1)/2

### ISSUE THREAD

**Issue by reddycharan** [apache/bookkeeper#1380]
**QUESTION**

Ensemble Size       - 9
WriteQuorum Size  - 7
AcqQuorum Size    - 5
 
lets assume the following scenario
 
BK - means Bookie
BK0 (NonValidResponse) - BK1 (ValidResponse) -BK2 (NonValid) - BK3 (Valid) -BK4 (NonValid) - BK5 (Valid) -BK6 (NonValid) - BK7 (Valid) - BK8 (NonValid)
 
basically
False (0) - True (1) - False (2) - True (3) - False (4) - True (5) - False (6) - True (7) - False (8)
 
Here we got valid responses from only 4 bookies and also no writesets has more than ack number of valid responses, but RRQuorumCoverageSet's addBookieAndCheckCovered returns true in this case.
 
Before I confirm this as bug, I need others opinion on expectation of this RRQuorumCoverage.

Anyhow I added testcase to validate this logic
https://github.com/reddycharan/bookkeeper/commit/9eead2212b9dc5910c8957447827edcbed4d93b6

**Comment by sijie** [comment]
@reddycharan actually I was thinking this for writes. but it turns out this is used for quorum read, if that's the case, I don't think the logic is wrong. Can you clarify your use case here?

**Comment by reddycharan** [comment]
As far as I understood, RRQuorumCoverageSet should return true for checkCovered only if all the writesets have atleast AckQuorum number of OKAY responses (in this OK/NoSuchEntryException/NoSuchLedgerExistsException). 

If that is the correct expectation, then current implementation of  RRQuorumCoverageSet  doesn't work accordingly in the example I mentioned above.

**Comment by sijie** [comment]
> RRQuorumCoverageSet should return true for checkCovered only if all the writesets have atleast AckQuorum number of OKAY responses

No. I don't think that is the meaning. The checkConvered here is used for quorum reads not for quorum writes, what you expect here is you should have at least one valid response from every quorum. so the check `nodesNotCovered >= ackQuorumSize` means if I have more "not covered" responses than ackQuorumSize, this quorum didn't see enough responses, the client should fail the quorum reads.

**Comment by ivankelly** [comment]
@reddycharan @sijie 

Yes, it's as @sijie says. checkCovered is not for the write path as such. Not really for the read path either. It's for fencing.

The intuition behind it is, if a entry X has been acknowledged to the client, it has to have been written to a full ack quorum of bookies. Conversely, if at least one bookie in each possible ack quorum has acknowledged the a fence operation, then it is impossible for any entry to be acknowledged to the client from that point on.

**Comment by reddycharan** [comment]
hmm..more comments to this class would have been helpful in understanding the expectation and purpose of RRQuorumCoverageSet. Anyhow I still have following questions

1)  *"Sijie: what you expect here is you should have at least one valid response from every quorum"*, if that is the expectation, then it wouldn't work in the following case, where in a writeQuorum if nodesOkay=1 and (nodesNotCovered >= ackQuorumSize). In this case writeQuorum got one okay response but more failure responses than ackQuorumSize.

2) If all the responses are either NoSuchEntryException or NoSuchLedgerExistsException, then nodesOkay=nodesNotCovered=nodesUninitialized=0, and it would return true, is that ok?

3) RoundRobinDistributionSchedule/RRQuorumCoverageSet seems to be a generic class, then why did we bring scenario specific flags/logic (NoSuchEntryException or NoSuchLedgerExistsException) to its implementation.

**Comment by reddycharan** [comment]
> I am not sure I understand your question.

I was referring to following scenario, for a writeSet nodesOkay = 1 but nodesNotCovered >= ackQuorumSize, in this case it will immediately return false. 

> what you expect here is you should have at least one valid response from every quorum.

isn't the above mentioned example contradict your statement?

> to satisfy the quorum read

mainly I'm trying to understand this part, actually what is the quorum for read?

If NoSuchEntryException and NoSuchLedgerExistsException are valid expected responses then why is "nodesOkay" count not incremented?

(PS: I'm sorry if it seems i'm repeating the questions)

**Comment by sijie** [comment]
> actually what is the quorum for read?

the quorum read here is for lac, not for individual entry. what the coverage covers here: for each write quorum, it has meaningful coverage. 

> If NoSuchEntryException and NoSuchLedgerExistsException are valid expected responses then why is "nodesOkay" count not incremented?

"nodesOkay" there means responses that can tell what is lac. "no such entry" or "no such ledger" are valid response, that they can tell lac.

**Comment by jvrao** [comment]
I think @reddycharan 's point is very simple.

1. The logic of checkCovered() is not correct.
```
          if (nodesNotCovered >= ackQuorumSize || (nodesOkay == 0 && nodesUninitialized > 0)) {
                    return false;
           }
```
      The negative logic is not correct. We should be checking
```

if (nodesOK >= Ack ) {
      return True;
} else {
     return  false;
}
```
2. But if we look at the usage of this, it is used only in readLac. So as far as ReadLac, we are OK as long as we have one valid response from that write quorum. If that is agreed upon behavior, do we really need a class and checkCovered() response?

@sijie @ivankelly ?

**Comment by sijie** [comment]
@jvrao @reddycharan : 

because the way how bookkeeper writes entries and the lac protocol. we don't really need "quorum" read for reading any entries. that says the coverage here is never designed for a "quorum-read" on entries. so there is no point saying "checkCovered() is not correct". 

we only need to quorum coverage check for LAC on determining what is the LAC and that is the class designed for. 

> o as far as ReadLac, we are OK as long as we have one valid response from that write quorum. If that is agreed upon behavior, do we really need a class and checkCovered() response?

if the goal is just to read any valid lac, we don't need quorum check; if the goal is to read max valid lac, the quorum check is needed (however I should also say it is not that strongly required). if you look into the API, read any valid lac is tryReadLastAddConfirmed, while read max valid lac is readLastAddConfirmed.

Hope this make the question clear.

**Comment by sijie** [comment]
removed label "priority/important" and "release/4.7.1", based on the conversation, this doesn't seem to be a bug (or at least not a critical issue).
