### ISSUE TITLE
createLedger() may fail if called immediatly after bookie startup

### ISSUE THREAD

**Issue by dlg99** [apache/bookkeeper#1400]
**BUG REPORT**

[testLedgerCreateAfterBookieStartup.txt](https://github.com/apache/bookkeeper/files/1992491/testLedgerCreateAfterBookieStartup.txt)

Caught this as a flapper in a separate (new) test suite.
createLedger() may fail with "org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available" if executed immediately after bookie restart.

It does not seem to be a production risk as the test uses single bookie and simple sleep(100ms) after bookie startup takes care of this problem.
OTOH I tried this test on internal (older) branch and the test passes so clearly there is a regression somewhere. 

Narrowed down it reproduces like this (also patch attached):

```java
    @Test
    public void testLedgerCreateAfterBookieStartup() throws Exception {
        // only one bookie started initially

        for (int n = 0; n < 30; n++) {
            int bkId = 0;
            BookieServer bks = bs.get(bkId);
            bks.shutdown();
            bks = new BookieServer(bsConfs.get(bkId));
            bks.start();
            bs.set(bkId, bks);

            // all passes with this sleep:
            //Thread.sleep(100);

            // Create ledgers
            LedgerHandle[] lhs = new LedgerHandle[10];
            for (int i = 0; i < 10; i++) {
                LOG.info("Iteration {}, creating ledger", n);
                lhs[i] = bkc.createLedger(1, 1, BookKeeper.DigestType.CRC32, "z".getBytes());
                LOG.info("Iteration {}, created ledger ID: {}", n, lhs[i].getId());
                lhs[i].addEntry("zzz".getBytes());
            }
        }
    }
```

**Comment by jvrao** [comment]
@dlg99 are you suggesting a check that ZK connection state is ready for consumption before operating on? How did you debug this? increasing the sleep helped you or something?

**Comment by dlg99** [comment]
@jvrao sleep() helps indeed. test passes under the debugger (which adds delays).
I did not look at this much closer after finding a repro & workaround/unblocking myself.

**Comment by eolivelli** [comment]
Does the bookie advertise itself on zk as available before actually beeing able to serve writes?
