### ISSUE TITLE
org.apache.distributedlog.fs.TestDLFileSystem fails on CI

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#1415]
The tests seems flaky

org.apache.distributedlog.fs.TestDLFileSystem.testBasicIO

Failing for the past 1 build (Since Instabile#40 )
Took 0.88 s.
Error Message
/tmp/testBasicIO (Permission denied)
Stacktrace
java.io.FileNotFoundException: /tmp/testBasicIO (Permission denied)
	at org.apache.distributedlog.fs.TestDLFileSystem.testBasicIO(TestDLFileSystem.java:68

**Comment by sijie** [comment]
it seems CI doesn't allow creating file under "/tmp".

so it might be worth changing the base dir to use `tmpDir`: https://github.com/apache/bookkeeper/blob/master/stream/distributedlog/io/dlfs/src/test/java/org/apache/distributedlog/fs/TestDLFileSystem.java#L64

Anyone interested in fixing this?
