### ISSUE TITLE
BP-33: Move releasing official docker images out of main repo

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1449]
**BP**

This is the master ticket for tracking BP-33 :

Current bookkeeper docker images are auto-built by apache docker account. However it becomes problematic in the release process:

Docker autobuild uses release tag for labeling the versions for docker images. But the `Dockerfile` can only be updated after a release is successfully made. So we have to retag a release after a release, in order to update `Dockerfile` to build the docker images.

Proposal PR - #1450

- [ ] add bookkeeper docker definition to docker-library/official-images
- [ ] add bookkeeper docker doc to https://github.com/docker-library/docs
- [ ] update release guide about docker image release procedure.

**Comment by eolivelli** [comment]
@sijie @jiazhai  FYI I have filed this new INFRA issue
https://issues.apache.org/jira/browse/INFRA-21000

because it looks like the autobuild is not working

**Comment by shoothzj** [comment]
closed by no updates.
