### ISSUE TITLE
MavenReportException: Error while generating Javadoc" while building master

### ISSUE THREAD

**Issue by dlg99** [apache/bookkeeper#1467]
**BUG REPORT**

1. Please describe the issue you observed:

pulled master locally and ran "mvn clean apache-rat:check install spotbugs:check -Dstream -DskipTests"
Build failed with "MavenReportException: Error while generating Javadoc" - "no description for @throws" etc.

Expected: build not failing because of javadoc

**Comment by eolivelli** [comment]
@dlg99 I think this can be closed now

**Comment by sijie** [comment]
This is resolved by #1468
