### ISSUE TITLE
BookieJournalForceTest is flaky

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1490]
*Problem*

```
2018-06-06\T\08:03:29.167 [ERROR] testForceLedger(org.apache.bookkeeper.bookie.BookieJournalForceTest)  Time elapsed: 0.263 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
	at org.apache.bookkeeper.bookie.BookieJournalForceTest.testForceLedger(BookieJournalForceTest.java:367)

```

**Comment by sijie** [comment]
@eolivelli I found that `BookieJournalForceTest` is flaky. Can you take a look at this? I would be surprised about this, since this unit test is mock based.

**Comment by eolivelli** [comment]
Sure. Will do soon. It is very strange.

**Comment by sijie** [comment]
yeah. there might be some non-deterministic behavior in the test. but it is seen multiple times in the "bookie tests" in recent PRs.

**Comment by eolivelli** [comment]
There are multiple threads which are playing in the game. I will debug as soon as I have time this week. We must not have flakes especially on new tests
