### ISSUE TITLE
Clean up javadoc mojos execution

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#1514]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

run "mvn clean install -DskipTests" on current master

- What did you expect to see?
build okay without warnings

- What did you see instead?

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:javadoc (default-cli) on project bookkeeper-tools-framework: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - javadoc: error - No public or protected classes found to document.

**Comment by sijie** [comment]
what is your environment and command? I never see this on CI or my local runs.

**Comment by eolivelli** [comment]
The error is hidden in the logs

during the build of bookkeeper-server module you can find this kind of lines:

> [INFO] --- maven-javadoc-plugin:3.0.0:jar (attach-javadocs) @ bookkeeper-server ---
> [INFO] The goal 'org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:javadoc' has not been previously called for the module: 'org.apache.bookkeeper:bookkeeper-common:jar:4.8.0-SNAPSHOT'. Trying to invoke it...
> [WARNING] Creating fake javadoc directory to prevent repeated invocations: /xxxxx/bookkeeper/bookkeeper-common/target/apidocs
> [INFO] The goal 'org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:javadoc' has not been previously called for the module: 'org.apache.bookkeeper:bookkeeper-proto:jar:4.8.0-SNAPSHOT'. Trying to invoke it...
> [ERROR] MavenInvocationException: Error when invoking Maven, consult the invoker log file: /home/diennea.lan/enrico.olivelli/dev/bookkeeper/bookkeeper-server/target/invoker/maven-javadoc-plugin1922966295.txt
> [WARNING] Creating fake javadoc directory to prevent repeated invocations: xxxxxx/bookkeeper/bookkeeper-proto/target/apidocs
> [INFO] The goal 'org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:javadoc' has not been previously called for the module: 'org.apache.bookkeeper:bookkeeper-tools-framework:jar:4.8.0-SNAPSHOT'. Trying to invoke it...
> [ERROR] MavenInvocationException: Error when invoking Maven, consult the invoker log file: /home/diennea.lan/enrico.olivelli/dev/bookkeeper/bookkeeper-server/target/invoker/maven-javadoc-plugin952120288.txt
> [WARNING] Creating fake javadoc directory to prevent repeated invocations: /xxxxx/bookkeeper/tools/framework/target/apidocs
> [INFO] The goal 'org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:javadoc' has not been previously called for the module: 'org.apache.bookkeeper.http:http-server:jar:4.8.0-SNAPSHOT'. Trying to invoke it...

then:

> [ERROR] MavenInvocationException: Error when invoking Maven, consult the invoker log file: /xxxxx/bookkeeper/bookkeeper-server/target/invoker/maven-javadoc-plugin1088547901.txt


now look into maven-javadoc-plugin1088547901.txt

@sijie

**Comment by sijie** [comment]
@eolivelli does it fail the build?

**Comment by eolivelli** [comment]
No, I think this is only a reason of slow down.

Anyway logs are messy.

We can tidy up.
This is not a blocker problem and it is not high priority

**Comment by eolivelli** [comment]
@sijie don't you see always the same logs at every build?
