### ISSUE TITLE
distributedlog links still point to incubator location

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1537]
*Problem*

in bookkeeper website, we are still using incubator locations for dlog references. we should change it to http://bookkeeper.apache.org/distributedlog

**Comment by ngwese** [comment]
One page which contains links to older incubator locations is this one: http://bookkeeper.apache.org/docs/latest/api/distributedlog-api/

**Comment by jiazhai** [comment]
will handle it.
