### ISSUE TITLE
Update 'upgrade' doc by adding an entry "4.7.x to 4.8.0 upgrade" for ExplicitLac persistence

### ISSUE THREAD

**Issue by reddycharan** [apache/bookkeeper#1565]
**FEATURE REQUEST**

Update 'upgrade' doc by adding an entry "4.7.x to 4.8.0 upgrade" for ExplicitLac persistence. 

For more info about ExplicitLac persistence, check - https://github.com/apache/bookkeeper/issues/1527

**Comment by eolivelli** [comment]
@reddycharan  will you pick this up please?
