### ISSUE TITLE
Add Code Coverage report for 'Stream' modules

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#1581]
In order to enable code coverage reporting on Stream modules we have to add -DstreamTests to the command line of the Jenkins build

I have started a test run
https://builds.apache.org/job/bookkeeper_codecoverage/164/

if the change is fine let's change the configuration on Jenkins DSL

**Comment by eolivelli** [comment]
cc @sijie

**Comment by sijie** [comment]
@eolivelli : https://github.com/apache/bookkeeper/blob/master/.test-infra/jenkins/job_bookkeeper_postcommit_master_java8.groovy#L42

**Comment by eolivelli** [comment]
@sijie  thank you
new run
https://builds.apache.org/job/bookkeeper_codecoverage/166/

**Comment by eolivelli** [comment]
I am closing this PR.
We will drop "stream" and "straemTests" profiles, so no other action will be needed
