### ISSUE TITLE
Etcd based metadata driver implementation

### ISSUE THREAD

**Issue by codingwangqi** [apache/bookkeeper#1639]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

We are investigating using bookkeeper as a storage component for our metadata service. However our infrastructure only uses Etcd and Kubernetes. we would like that bookkeeper can run with Etcd, we don't want to use and operate zookeeper. 

After talked to @jiazhai and @sijie, they pointed us to @sijie's prototype on Etcd #1114 . I have implemented the Etcd metadata driver, and would like to share it with the community and continue the development in the community, while we are investigating the usage of bookkeeper. 

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

nice-to-have

3. Provide any additional detail on your proposed use case for this feature.

Be able to run bookkeeper with Etcd.

**Comment by codingwangqi** [comment]
@sijie @jiazhai does this look good to you?

**Comment by sijie** [comment]
@codingwangqi thank you!
