### ISSUE TITLE
Apache BookKeeper Tutorial Implemented with Scala

### ISSUE THREAD

**Issue by bwsw** [apache/bookkeeper#165]
Hello, guys. Our developer reimplemented your tutorial with Scala. May be you find it interesting to expand your documentation. Just FYI it is here: https://github.com/bwsw/bookkeeper-tutorial-scala

**Comment by eolivelli** [comment]
@bwsw  awesome !
Thank you for sharing you work!

**Comment by sijie** [comment]
@bwsw great job! 

@eolivelli do you want to update the documentation to include @bwsw 's tutorial?

**Comment by eolivelli** [comment]
@sijie I will do as soon as possible

**Comment by eolivelli** [comment]
@sijie 
we can add a link to the project here http://bookkeeper.apache.org/docs/master/bookkeeperTutorial.html
after the reference to @ivankelly repository  https://github.com/ivankelly/bookkeeper-tutorial/ 
is it OK ?
shall we create a JIRA for this ?

**Comment by sijie** [comment]
@eolivelli let's discuss the issue tracking at the mail-list. but my thought here is - if there is a github issue here, we don't need to create a jira. but the pull request need to be "Issue-<Issue-#>: ...."

**Comment by eolivelli** [comment]
@sijie  committed to staging website, see https://issues.apache.org/jira/browse/BOOKKEEPER-1080

**Comment by sijie** [comment]
oh I just realized that site repo is still in svn. we might need to move that to git (and probably rewrite this using static generator like jeklly). Otherwise there is visibility on the changes on the site.

For this change, +1 for the staging.

**Comment by eolivelli** [comment]
Done
I cannot close this issue, @bwsw  can you close it?

**Comment by sijie** [comment]
@eolivelli I believe we might need to request permission from INFRA team.

**Comment by jvrao** [comment]
Sorry for being naive on this subject. What is the real use of implementing tutorial in Scala? and have a separate git repo for it?

**Comment by sijie** [comment]
@jvrao 

re "a separate git repo" - current java tutorial is a tutorial wrote by @ivankelly , it is not in bookkeeper's repo.

a tutorial is just a sample application to show how to use BookKeeper to build applications. I don't know if it is necessary to have it along with the main repo. If it is easier, we can merge them into the main repo.

scala vs java - my take is just different ways to use bookkeeper in different languages.
