### ISSUE TITLE
Use FileLock to prevent multiple processes mutating data on disks

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1654]
As commented at https://github.com/apache/bookkeeper/pull/1642#discussion_r215035261, we might need a mechanism to prevent multiple processes mutating data on disks. At twitter branch, there was a FileLock mechanism to prevent this happen, we need to double check and port the change back.

**Comment by shoothzj** [comment]
@sijie I think now OSS BookKeeper is single process model, we don't need handle this. Closed this for now, feel free to reopen it.
