### ISSUE TITLE
Make build pass on JDK11

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#1710]
Is this a question, feature request, bug report, or bookkeeper proposal?

**FEATURE REQUEST**

I want to be able to build and test BookKeeper code base using JDK11

Only a bunch of changes are needed:
- upgrade Mockito
- Move Kerberos tests to Kerby
- Add javax annoatations api as compile time dependency (not runtime)
- add CI jobs

**Comment by sijie** [comment]
@eolivelli can we claim this is done?

**Comment by eolivelli** [comment]
Spotbugs is not passing on JDK11.

And we still have build passing on JDK11 but we do not have CI jobs on Jenkins:
- precommit
- nightly
....

I have bookies and clients running on JDK11 in production.
I was blocked in spotbugs change because you are suggesting to disable a rule on JDK11, it is quite tricky and in the meantime I was busy in other tasks (non-BK).
I can try to finish these tasks during these days.

**Comment by sijie** [comment]
@eolivelli can we move it to 4.10 then?

**Comment by eolivelli** [comment]
The only blocker for me is the spotbugs configuration.please check my last comment.
 
I fell I can finish this work thus week

**Comment by sijie** [comment]
#1849 (spotbugs change) is merged.
