### ISSUE TITLE
Download page use of archive links

### ISSUE THREAD

**Issue by sebbASF** [apache/bookkeeper#1715]
The download page currently links to "Latest stable release (version 4.7.2)" using the host archive.apache.org. However release 4.7.2 is still present on the mirrors.

Either release 4.7.2 is still current, in which case it must be linked from the mirror servers, or it is no longer current, and must be removed from the mirrors, and can then be linked from the archive server.

[It is unfair to burden 3rd party mirrors with releases that are not current, and the archive server is only designed for downloading historic releases.]

**Comment by sijie** [comment]
@sebbASF 4.7.2 is no longer current. 4.8.0 is the latest release. I just deleted 4.7.2 from dist, so it will no longer present on the mirrors.
