### ISSUE TITLE
Release procedure: drop old releases from dist.apache.org

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#1728]
We have to upgrade the release guide in order to drop old releases from dist.apache.org.
We should keep only 1 version per active branch

**Comment by eolivelli** [comment]
Marking this as "important" because we have to fix this at least at next major release (when we will create a new release branch)

**Comment by sijie** [comment]
@eolivelli : there is already a section "Cleanup old releases" in the release guide, no?

**Comment by eolivelli** [comment]
I missed that. Sorry
