### ISSUE TITLE
Document issue

### ISSUE THREAD

**Issue by david-streamlio** [apache/bookkeeper#1761]
**BUG REPORT**

1. Please describe the issue you observed:

The instructions on the https://bookkeeper.apache.org/docs/4.8.0/getting-started/installation page 
are incorrect.

**What did you do?**

 - git clone git://git.apache.org/bookkeeper.git/
 - mvn package assembly:single
 
**What did you expect to see?**

I expected the command to execute correctly. 

**What did you see instead?**

Instead there was an error indicating that the pom was missing an assembly descriptor:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.656 s
[INFO] Finished at: 2018-10-25T09:47:28-07:00
[INFO] Final Memory: 37M/124M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (default-cli) on project bookkeeper: Error reading assemblies: No assembly descriptors found. -> [Help 1]

**Comment by eolivelli** [comment]
Try with
mvn clean install -Dstream -DskipTests

**Comment by david-streamlio** [comment]
I get the same error running "mvn clean install -Dstream -DskipTests package assembly:single"

**Comment by eolivelli** [comment]
Just use the command I am suggesting you will find the binaries into 'dist' folder (If I remember correctly).

In fact 'install' will include the packaging phase

**Comment by david-streamlio** [comment]
I am sure your command works, the issue I am pointing out is with the documentation itself and the fact that the "mvn package assembly:single" command that is listed on the web page, does not actually work.

**Comment by eolivelli** [comment]
Sure.
Let's fix it.
Do you have time to send a PR? The website is inside the repo

**Comment by david-streamlio** [comment]
I could send a PR. I guess the bigger question is do we want to just remove the non-working command from the documentation, or should we fix the pom.xml file so that the command works?

**Comment by eolivelli** [comment]
@sijie maybe you know the full history of the page...

To me it is better to run the command I suggested.
Maybe it is enough

mvn clean package -Dstream -DskipTests

**Comment by sijie** [comment]
the doc page will be updated (fixed) by #1800

**Comment by sijie** [comment]
#1800 addressed part of the issue. others will be addressed by #1822
