### ISSUE TITLE
Example application link broken

### ISSUE THREAD

**Issue by david-streamlio** [apache/bookkeeper#1763]
Documentation issue:

The "Example Application" link on the https://bookkeeper.apache.org/docs/latest/api/ledger-api/ page is broken.  

The Link url is https://bookkeeper.apache.org/docs/latest/api/example-application, but when you click on it, you get a 404 "The requested URL /docs/latest/api/example-application was not found on this server." error instead.

**Comment by sijie** [comment]
This was fixed by #1764
