### ISSUE TITLE
Content need update for release management page

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#1820]
In  [release management](http://bookkeeper.apache.org/community/releases/
)  page, some information is out of date.

such as: 
```
The next feature release is 4.8.0. The release window is the following:
```
and 
```
Release Schedule
4.7.0: November 2017 - April 2018
4.8.0: April 2018 - July 2018
4.9.0: July 2018 - October 2018
4.10.0: October 2018 - January 2019
```

**Comment by eolivelli** [comment]
good catch.
We can update it after releasing 4.8.1.

We have also to find a release manager for 4.9

**Comment by sijie** [comment]
The release schedule has been updated after 4.9.0
