### ISSUE TITLE
Support GitHub issues in bk-merge script

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#184]
This issue is to support GitHub issues in bk-merge script as well as we are doing with ASF JIRA.

**Comment by eolivelli** [comment]
I am not expert of GitHub API and I am a python newbie, @Sijie I think
you created the actual script and maybe you be be able to edit is in
order to enhance it

I think that first of all we should discuss about the structure of
such an issue:
- labels ?
- milestones ?

my first proposals:
- labels -> we can use it for:
-- "component" in JIRA, like component/server, component/autorecovery
-- "priority", like priority/blocker
-- estimation of the difficulty, like 'newbie", "expert"
- milestone -> this is kind of "release", so we should create a 4.5.0
"milestone" ?

other "issue":
pull requests wil be bound to issues, we have to cases:
- the pull request is per-se and issue, so for small changes which
already have a PR we can create only the PR, and all will be "lighter"
- the issue will need more patches, we should define a conventional
way of referring to issues (GitHub recognizes the #NN syntax, and is
able to automatically close related issues)

I don't know the "magic works" that the asfgit + bk-merge is doing
undercover, it is a missing piece from my part: the merge script is
adding a comment with "closes #NNN" but this comment is not reported
in "git log"

**Comment by eolivelli** [comment]
another problem...how can we create release notes ?
maybe for 4.5.0 we should stay on JIRA as most of the issues are on that system

**Comment by sijie** [comment]
I think Jia posted a BP. @eolivelli can you work with Jia to consolidate the efforts?
