### ISSUE TITLE
java.lang.IllegalStateException: State is not enabled

### ISSUE THREAD

**Issue by hiscal2015** [apache/bookkeeper#1880]
bookkeeper version: 4.7.3
Pulsar broker version : 2.2.0

We have a 3 nodes bk cluster on bare metal and 3 brokers on Kubernetes. We followed the guide to create a function, but when our Pulsar function calls "putState" the following exception occurs:
```
java.lang.IllegalStateException: State is not enabled
```

Are there missing steps that we need to take to enable State for functions?
Please help, thanks.

**Comment by sijie** [comment]
@hiscal2015 : this is related to apache/pulsar#3140

**Comment by sijie** [comment]
close this one, since pulsar is going to release 2.3.0 this week.
