### ISSUE TITLE
Handle double bookie failures with outstanding metadata change.

### ISSUE THREAD

**Issue by jvrao** [apache/bookkeeper#1886]
Is this a question, feature request, bug report, or bookkeeper proposal?

**QUESTION**

Have you checked our documentation at http://bookkeeper.apache.org/ , If you could not find an answer there, please consider asking your question in our community forum at user@bookkeeper.apache.org, as it would benefit other members of our community.

**BUG REPORT**

1. Please describe the issue you observed:
Following race is not handled in 4.8 and prior code. Master is fine as we have immutable metadata

   1. ZK metadata version is different from Client write ledger
       handle - Replication worker
    2. Client made an ensemble change and replaced a bookie,
       sent change proposal to zk
    3. While this is pending, Client made another ensemble change
       replaced the same index with the bookie that was prior to step#2
    4. Ensemble change made in step#2 came back to client with
       version conflict error.
    5. Client need to resolve this conflict

**Comment by ivankelly** [comment]
Fixed by #1887
