### ISSUE TITLE
publishing official Bookkeeper source release to Maven Central

### ISSUE THREAD

**Issue by hboutemy** [apache/bookkeeper#1895]
I see that the Apache source release tarball is bookkeeper-4.8.1-src.tar.gz (in Apache dist https://www.apache.org/dist/bookkeeper/bookkeeper-4.8.1/ )
but on Maven Central, it is bookkeeper-4.8.1-source-release.zip that is published (in https://repo1.maven.org/maven2/org/apache/bookkeeper/bookkeeper/4.8.1/ )

and in 4.5.0 and 4.5.1, both archives (*-src.tar.gz and *-source-release.zip) were published on Central...

I suppose you have a conflict with the default archive in the default release profile from Apache parent POM: https://maven.apache.org/pom/asf/#The_apache-release_Profile
you should disable default archive and enable publication of your own archives

don't hesitate to let me know if you need help

**Comment by eolivelli** [comment]
Thank you @hboutemy, we wil try to fix this before the next release which will happen soon.
I think it is not worth to try to fix the past

**Comment by hboutemy** [comment]
no, past is past...

on fixing, you should easily be able to do as Maven core does = disable default source-release in root https://github.com/apache/maven/blob/master/pom.xml#L604 then publish your source-release in another artifact https://github.com/apache/maven/blob/master/apache-maven/pom.xml#L263 since you have currently the bookkeeper-dist module that looks equivalent to apache-maven

or you can decide to refactor more: I don't know what is the best solution for your build since I don't get really your details

**Comment by sijie** [comment]
I am wondering what is the motivation about this. apache dist is the only *binary* distribution channel for both source and binary packages, maven is for artifacts but we didn't use it for source distribution. It would be great to share more details behind this request.

**Comment by eolivelli** [comment]
@sijie we are deploying the sources of each module together with the binary to Maven central. This is very useful for developers, as IDEs can download the sources automatically from Maven centr

**Comment by eolivelli** [comment]
I had accidentally closed the issue. Sorry about that

**Comment by hboutemy** [comment]
@eolivelli the sources for the IDE are published along every artifact, as *-sources.jar, and it is a checked requirement for Central, then you don't have any issue on that
@sijie adding the buildable source release is not a strict requirement, but is a good practice since the sources for the IDE are not buildable, and Open Source is about source: source that is not buildable is not very useful. And since Bookkeeper deploys some buildable sources (as -source-release.zip) without knowing, either you should remove it or replace with the official archive: it's for clarity

Last point: I'm currently working on reproducible builds to improve security for the JVM ecosystem, and this question of being able to rebuild everything in Maven central is coming: see https://reproducible-builds.org/docs/jvm/

**Comment by sijie** [comment]
@hboutemy thank you for your comment.

> you should disable default archive and enable publication of your own archives

Are you interested in contributing a fix for us?

**Comment by hboutemy** [comment]
@sijie @eolivelli please review #1904

**Comment by eolivelli** [comment]
Committed your fix. Thanks
