### ISSUE TITLE
Masquerading ZK errors as generic ZKException

### ISSUE THREAD

**Issue by adrianmo** [apache/bookkeeper#1905]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

We are in the process of updating BookKeeper dependency in Pravega from 4.5.0 to 4.7.3. In some tests, we try to create a Znode in a path that doesn't exist and expect to receive an exception accordingly.

- What did you expect to see?

We expect to see a [`KeeperException.NoNodeException`](https://github.com/apache/zookeeper/blob/branch-3.5/zookeeper-server/src/main/java/org/apache/zookeeper/KeeperException.java#L118), which is the original error thrown by the ZK client and it was preserved by BK 4.5.

- What did you see instead?

Instead of a `NoNodeException`, we get the following.

```
org.apache.bookkeeper.client.BKException$ZKException: Error while using ZooKeeper
	at org.apache.bookkeeper.discover.ZKRegistrationClient.lambda$getChildren$0(ZKRegistrationClient.java:212)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$25$1.processResult(ZooKeeperClient.java:1174)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:619)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:499)
```

Looking at the code, it seems that BK is ignoring the return/error code from ZK and rethrowing a generic `ZKException` in https://github.com/apache/bookkeeper/blob/branch-4.7/bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationClient.java#L211.

**Comment by eolivelli** [comment]
Can you please report which API call is failing on BK ? it is not clear from the stacktrace

**Comment by eolivelli** [comment]
It should be easy to add the ZK error code to the ZKException or create a dummy KeeperException and attach to the ZKException as "cause"

**Comment by eolivelli** [comment]
I am leaning toward closing this ticket as 'won't fix'.
In general client should not rely on the internal errors of BK.
We are also stripping away the dependency from zk. So ZKException is already an internal implementation  detail

Is this blocker in your case?

**Comment by adrianmo** [comment]
No, it's not a blocker, but this is preventing us from seeing the real cause of the exception. My question is, why rethrowing a generic ZKException if the real error cause is available?

**Comment by Ghatage** [comment]
@adrianmo https://github.com/apache/bookkeeper/pull/2384 from @eolivelli improves the details around ZKException, was wondering if that would be good enough for this ticket as well.

**Comment by adrianmo** [comment]
Yes, that PR should fix the issue. Thanks for the heads up @Ghatage.
