### ISSUE TITLE
EnsemblePlacementPolicy exposes third party API "Pair" from commons-lang3 in a public API

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#1914]
We are going to release a public API which depends on a third party library. This will introduce compatibility problems in the future.

EnsemblePlacementPolicy API is an extension point on the client side, we should not depend on APIs from third party providers.

The issue was introduced in #1883

This is very like to #67, #300 and #804

**Comment by reddycharan** [comment]
@eolivelli @sijie will take care of this in couple of days. Thanks for creating an issue for this.

@jvrao fyi.

**Comment by eolivelli** [comment]
If you prefer @reddycharan I can send a patch.
The proposal from @sijie is to create a Pair class inside bookkeeper-common package.

I would like to move the release forward, because new  Pulsar release depends on this patch (AFAIK)

**Comment by sijie** [comment]
@eolivelli agreed with you. I think it is a straightforward task, @reddycharan if you agree with approach, @eolivelli can help with the code change.

**Comment by reddycharan** [comment]
@eolivelli @sijie I'm fine, you may proceed. Thanks.

**Comment by sijie** [comment]
This has been fixed by #1916 in 4.9.0 release
