### ISSUE TITLE
Bypass journal ledger feature

### ISSUE THREAD

**Issue by ArvinDevel** [apache/bookkeeper#1918]
Is this a question, feature request, bug report, or bookkeeper proposal?

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Currently, BK write journal before flush data to persistent device which will cause two write of data. Since we already have replicas to guarantee the availability and has auto-recovery mechanism, sometimes we don't want this high reliability with writing journal at the cost of write twice of the same data. Especially when the disk bandwidth is precious.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
nice-to-have

3. Provide any additional detail on your proposed use case for this feature.
When the source of data has another backup, it's ok to tolerant data lost of the memtable. In addition to that, the bk's auto-recovery could recover the failed bookie's data from other healthy bookies.

I think this feature is a bit like  #471, but with another method. Hope to see you guys' viewpoint.

**Comment by jiazhai** [comment]
Comparing with 471, Seems this would change a lot in the IO path. @sijie @eolivelli What do you think of this idea?

**Comment by eolivelli** [comment]
We already discussed about this.
On the clientside we can have a new WriteFlag.
Handling of LAC should be like with DEFEREED_SYNC flag.

We can change force() to force and wait for a checkpoint of the memtable with this new flag: this way LAC will advance in a consistent way

**Comment by merlimat** [comment]
I too would like to have an option to avoid the journal completely. That would avoid the double data write (of course at the expense of data durability).

**Comment by sijie** [comment]
@jvrao have you guys started the bypass-journal work? or @ArvinDevel are you interested in contributing this feature?

**Comment by ArvinDevel** [comment]
@sijie I'm glad to contribute this feature, after I'm familiar with #471 and #743 , I'll make one clear BP for this feature.

**Comment by shoothzj** [comment]
closed by #2401
