### ISSUE TITLE
zkServers & metadataServerUri are both specified in the config file by default

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#1920]
We should specify that the deprecated ones are only used if metadataServiceUri is not specified, and have them commented out in conf file by default.

**Comment by shoothzj** [comment]
I think it has been completed. We have marked zkServers deprecated, but keep the zkServers for compatible, close this issue, feel free to reopen it if you still have other questions. :) 

https://github.com/apache/bookkeeper/blob/c4fa8c20131fb5e52b7448ee6ee1491bf9e870fa/conf/bk_server.conf#L848-L852
