### ISSUE TITLE
dlog core pulls in log4j

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#1926]
dlog core is a client library. it shouldn't pull in log4j and the log4j slf4j adapter as that interferes with the logging of the application which is pulling it in.

**Comment by liketic** [comment]
Hi @ivankelly , I found the scope of those dependencies  log4j and slf4j is test. So they will not be pulled in user's environment if I'm not wrong. It that's right?

**Comment by ivankelly** [comment]
@liketic You're right. I must have been seeing things. Closing.
