### ISSUE TITLE
localbookie cannot be started with a ledger path which isn't on the root level

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#1927]
74bd92605bc4986705031aea8943905dbc9f9f85 allowed the client to overwrite localbookie configurations from conf/bk_server.conf

However, if you set the zkLedgersRootPath to something like /messaging/bookkeeper/ledgers, it will fail because it doesn't create the parent znodes (and there's no other way to do it since this is localbookie, and it only lives for the lifetime of the process).

**Comment by zhaohaidao** [comment]
Is there anyone working on it ? 
I want to give it a try.

**Comment by sijie** [comment]
@zhaohaidao I don't think so. Please go ahead. If you need any help, please let me know.
