### ISSUE TITLE
BookieStickyReadsTest.stickyReadsWithFailures is flaky

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#1935]
**BUG REPORT**

***Describe the bug***

BookieStickyReadsTest.stickyReadsWithFailures has been seen failing multiple times in jenkins CI.

***Expected behavior***

BookieStickyReadsTest should pass reliably

***Additional context***

**Comment by ivankelly** [comment]
@sijie please linnk failed build and mark keep forver.

**Comment by Ghatage** [comment]
@sijie @merlimat This doesn't seem to be flaky anymore. Do we still want to keep this issue open?

**Comment by shoothzj** [comment]
closed by no reproduce.
