### ISSUE TITLE
BP-38: Bypass journal ledger

### ISSUE THREAD

**Issue by ArvinDevel** [apache/bookkeeper#1945]
**BP**

> Follow the instructions at http://bookkeeper.apache.org/community/bookkeeper_proposals/ to create a proposal.

This is the master ticket for tracking BP-38 :

To guarantee high durability, BK write journal before flush data to persistent device which will cause two write of data.
At the presence of replicating and auto-recovery mechanism, the two-write is a bit waste of the persistent device bandwidth,
especially on the [scenarios](https://cwiki.apache.org/confluence/display/BOOKKEEPER/BP-14+Relax+durability) which prefer weak durability guarantee.

Proposal PR - #1944

**Comment by atris** [comment]
Hi -- Unless this is being actively worked on, can I take this one?

@sijie

**Comment by sijie** [comment]
@atris yes. I don't think @ArvinDevel is actively working on this. Feel free to take this one.

**Comment by shoothzj** [comment]
closed by #2401
