### ISSUE TITLE
Failed to load Circe JNI library

### ISSUE THREAD

**Issue by hamadodene** [apache/bookkeeper#1947]
**BUG REPORT**

`
Feb 15, 2019 12:11:27 PM com.scurrilous.circe.checksum.Crc32cIntChecksum <clinit>
WARNING: Failed to load Circe JNI library. Falling back to Java based CRC32c provider
`

i have this warning when i use bookie with herddb in cluster mode (https://github.com/diennea/herddb). 
i installed all dipendencies but it still doesn't work. 
```
readelf -d libcirce-checksum.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

Sytem information where i run bookie: 
`Linux  *********  3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`

What could be the cause?

**Comment by michaeljmarshall** [comment]
This PR https://github.com/apache/bookkeeper/pull/3309 might help. At the very least, it is going to remove the warning log.
