### ISSUE TITLE
Update JMX documentation

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#195]
Since we have dropped legacy JMX support the doc/bookkeeperJMX.textile page is to be updated.
We should talk about Stats Provider and maybe cite how to enable JMX monitoring using the Codahale Stats Provider

**Comment by sijie** [comment]
@eolivelli I assume this should be go into 4.5.0 release?

**Comment by sijie** [comment]
@eolivelli are you working on this? I am cleaning up the documentation task for 4.5.0.

**Comment by eolivelli** [comment]
This weekend I do not have time. I can do next week

**Comment by sijie** [comment]
This will be replaced with 'Metric Collection' in https://lucperkins.github.io/bookkeeper/docs/admin/metrics/ #293 

Close this as "Won't Fix"

**Comment by sijie** [comment]
Closed this as "Won't Fix"
