### ISSUE TITLE
Create Jenkins configuration using OpenStack Jenkins Job Builder

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#196]
The idea is to commit the configurations of Jenkins jobs directly on BookKeeper repository.
This will ease job configuration review.

We are going to use Jenkins Job Builder
https://docs.openstack.org/infra/jenkins-job-builder/

**Comment by fpj** [comment]
@eolivelli is there any change needed on the jenkins server or is it all client side? I like this proposal, btw.

**Comment by eolivelli** [comment]
I am investigating.
I will be back soon with news
