### ISSUE TITLE
Ledger creation and removal can return erroneous errors if there is a zk ConnectionLoss event while the update is inflight

### ISSUE THREAD

**Issue by athanatos** [apache/bookkeeper#1967]
The bookkeeper project ZooKeeperClient wrapper (not to be confused with ZooKeeper or the distributed log analogue) will resend zk node creations and removals upon reconnect after a ConnectionLoss event.  In the event that the original succeeded, the resent operation will erroneously return LedgerExistException or NoSuchLedgerExistsException for creation and removal respectively.

For removal, I propose limiting the operation to be idempotent by letting it succeed if the ledger does not exist.  This is by far the simplest solution if exclusive removal isn't important.

For creation, exclusive creation is genuinely important for correctness, so I suggest adding a unique nonce to the LedgerMetadata to disambiguate the above race from a real race.  For zk, this can simply be the zk session id.

**Comment by sijie** [comment]
+1

**Comment by eolivelli** [comment]
+1

**Comment by athanatos** [comment]
https://github.com/apache/bookkeeper/pull/1971
