### ISSUE TITLE
Broken "metrics" link in documentation

### ISSUE THREAD

**Issue by RaulGracia** [apache/bookkeeper#1979]
**BUG REPORT**

***Describe the bug***

The [`metrics.md`](https://github.com/apache/bookkeeper/blob/28dee8464764b0edceeb31ce24424f0947b5789b/site/docs/4.7.1/admin/metrics.md) file has a broken link pointing to an unknown site:
> For a full listing of available metrics, see the [Metrics](https://github.com/apache/bookkeeper/blob/28dee8464764b0edceeb31ce24424f0947b5789b/site/docs/reference/metrics) reference doc. <- (broken link)

This problem is also visible in the documentation page: https://bookkeeper.apache.org/docs/4.7.3/reference/metrics

***To Reproduce***

Just click the link posted above, you should see the problem.

***Expected behavior***

A "Metrics" page is expected with all the metrics that Bookkeeper exposes.

***Screenshots***

n/a.

***Additional context***

n/a.

**Comment by Jennifer88huang** [comment]
@RaulGracia thanks for raising the issue. It seems that the `metrics.md` file in the `reference` folder has no content.
