### ISSUE TITLE
BookKeeper CLI for writing and reading entries.

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#201]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

It would be good to have a CLI for interacting with bookkeeper (for development purpose). 

Something like:

`$ bookkeeper localbookie 6`
`$ bookkeeper-client create-ledger foo`
`$ bookkeeper-client add-entry foo "Here is some data"`

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Nice-to-Have**

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by ivankelly** [comment]
@sijie will this be done as part of the new CLI work?

**Comment by sijie** [comment]
the new CLI work is mainly for refactoring the existing one for now. this one can probably go after the new CLI is done.

**Comment by ivankelly** [comment]
Can you make a link between this and the refactor issue?

**Comment by sijie** [comment]
linked to the new CLI : #1000
