### ISSUE TITLE
Need Explicit error message if ledger is not present on ZK

### ISSUE THREAD

**Issue by jvrao** [apache/bookkeeper#2065]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Client can get no ledger error in the following two scenarios.
    1. When client attempted to read/open an extent that
       is not on ZK (metadata server)
    2. When client attempted to read an ledger which is on metadata
       server, but somehow missing on bookies

    It is quite confusing to get the same error, NoSuchLedgerExists
    for both these cases. This feature to introduce a new error at the
    BookKeeper level, NoSuchLedgerExistsOnMetadataServer if the ledger is not on zk.
    This helps the client knows to distinguish the difference.

**Comment by eolivelli** [comment]
+1 to be stated clearly in the release notes.
some application may break

**Comment by sijie** [comment]
This has been implemented and fixed.
