### ISSUE TITLE
ConcurrentLongHashSetTest.java: Math.abs does not always give a positive result (errorprone warning)

### ISSUE THREAD

**Issue by jirkadanek** [apache/bookkeeper#2077]
**BUG REPORT**

***Describe the bug***

When compiling the project using the ErrorProne compiler, the following warning is emitted.

[MathAbsoluteRandom] Math.abs does not always give a positive result. Please consider other methods for positive random numbers. (See https://errorprone.info/bugpattern/MathAbsoluteRandom)

It is related to code at

https://github.com/apache/bookkeeper/blob/28dee8464764b0edceeb31ce24424f0947b5789b/bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashSetTest.java#L162-L171

***To Reproduce***

1. Install the ErrorProne IntelliJ plugin https://plugins.jetbrains.com/plugin/7349-error-prone-compiler-integration
2. Enable it in Project settings
2. Rebuild the project
3. See error in log

***Additional context***

```
jshell> import java.lang.Math;

jshell> Math.abs(Long.MIN_VALUE)
$5 ==> -9223372036854775808
```

One solution is to use the `java.util.concurrent.ThreadLocalRandom#nextLong` which has variant to return only positive numbers.

I had a brief look at the test and I don't see why it is necessary for the random number to be positive, to tell the truth.

**Comment by sijie** [comment]
@merlimat can you take a look at this?
