### ISSUE TITLE
Implement getListOfEntriesOfLedger method for DbLedgerStorage

### ISSUE THREAD

**Issue by reddycharan** [apache/bookkeeper#2078]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Implement getListOfEntriesOfLedger method for DbLedgerStorage. This is needed for supporting DbLedgerStorage for Cluster Metadata Checker (https://github.com/apache/bookkeeper/blob/master/site/bps/BP-34-cluster-metadata-checker.md). 

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
   nice-to-have

3. Provide any additional detail on your proposed use case for this feature.
For InterleavedLedgerStorage and SortedLedgerStorage, it is being implemented but for DbLedgerStorage we are leaving it as TODO work item.

**Comment by sijie** [comment]
This is fixed by #1931
