### ISSUE TITLE
Entries must be acknowledged by bookies in multiple fault domains before being acknowledged to client

### ISSUE THREAD

**Issue by ankit-j** [apache/bookkeeper#2095]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Bookkeeper write logic makes sure that there are at least `ackQuorumSize` number of successful writes before sending ack back to the client. In many cases these may fall into the same fault domain. A mechanism to force bookkeeper to make sure that there are acks from at least `minNumRacksPerWriteQuorum` number of fault domains and a configuration to enforce this.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
   Are you currently using any workarounds to address this issue?
must-have

3. Provide any additional detail on your proposed use case for this feature.

**Comment by sijie** [comment]
this is fixed by #2096
