### ISSUE TITLE
Change bk-merge script to delete the last part of PR description.

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#211]
1. Please describe the feature you are requesting.
Change bk-merge script to delete the last part of PR description.
When pull request is created, the template contains the checking context, which is expected to be done by the contributor. It would be better to delete this part when we merge the pull request by bk-merge script.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
Nice-to-have. 
workaround: Contributor can manually do it.

3. Provide any additional detail on your proposed use case for this feature.
when merge the pull request by bk-merge script, delete the checking context in the pull request description.
The checking context is like this:
```
Be sure to do all of the following to help us incorporate your contribution
quickly and easily:

[ ] Make sure the PR title is formatted like:
<Issue #>: Description of pull request
e.g. Issue 123: Description ...
[ ] Make sure tests pass via mvn clean apache-rat:check install findbugs:check.
[ ] Replace <Issue #> in the title with the actual Issue number, if there is one.
```

**Comment by eolivelli** [comment]
I think we already did this

**Comment by sijie** [comment]
yes this is already one. closing it.
