### ISSUE TITLE
Add more more instructions for minorCompactionInterval in bookkeeper.conf

### ISSUE THREAD

**Issue by codelipenghui** [apache/bookkeeper#2115]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

In bookkeeper.conf, `minorCompactionInterval` value must greater than `gcWaitTime`, otherwise bookie can't startup success. Add more instructions for warning this would be welcome.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
 
nice-to-have

3. Provide any additional detail on your proposed use case for this feature.

**Comment by codelipenghui** [comment]
Relate to [pulsar-4558](https://github.com/apache/pulsar/issues/4558)

**Comment by codelipenghui** [comment]
@sijie I have added related issue in bookkeeper.

**Comment by eolivelli** [comment]
@sigee  @codelipenghui do you have cycles to provide a fix this week ?
I see this issue is marked for 4.10

**Comment by codelipenghui** [comment]
@eolivelli Thanks for reminding, there is some tests fails, i have rerun the failed tests, if you already started the release process, you can move it to the next release version.

**Comment by eolivelli** [comment]
The jobs fail due to infrastructure problems on CI.
We have not so much hurry.
Let's ship this change
