### ISSUE TITLE
how does the client choose the bookie to read?

### ISSUE THREAD

**Issue by sunjingji** [apache/bookkeeper#2140]
I'm newer to bookeeper. I wonder how the reader knows which bookie to read from for a given entry when striping writes(i.e., E > Qw) take place？

**Comment by sijie** [comment]
@sunjingji 

bookkeeper stores the ensemble of bookies as part of the metadata. so it will read the entries in the way how the entries are placed in the ensemble bookies. If it fails to read an entry from one replica, it will retry reading from other replicas.

**Comment by Ghatage** [comment]
@eolivelli @sijie should we close this?
