### ISSUE TITLE
Using shell generate an unexpected cookie

### ISSUE THREAD

**Issue by lsy180829** [apache/bookkeeper#2145]
**BUG REPORT**

***Describe the bug***

When I run the order "bookkeeper shell cookie_generate", I got a new cookie, but this new cookie is different from the other cookie in zk.

Order( It belongs to pulsar ) :
./bin/bookkeeper shell cookie_generate -j data2/bookkeeper/journal -l data2/bookkeeper/ledgers -i 9285da1b-e1be-471b-8d11-d30d80212e68 -o /tmp/cookie.x 10.254.3.60:3181

The generated cookie is this:
4
bookieHost: "10.254.17.8:3181"
journalDir: "data2/bookkeeper/journal"
ledgerDirs: "data2/bookkeeper/ledgers"
instanceId: "3ed785b5-eb93-498c-9d57-b38ab8846e7b"

The cookie in zk is this :
4
bookieHost: "10.254.17.8:3181"
journalDir: "data/bookkeeper/journal"
ledgerDirs: "1\tdata/bookkeeper/ledgers"
instanceId: "3ed785b5-eb93-498c-9d57-b38ab8846e7b"

We can find the difference is "1\t" in two ledgerDirs, because of it, After I changed the dir and others operation, starting bookie is fail.

09:26:07.829 [main] ERROR org.apache.bookkeeper.server.Main - Failed to build bookie server
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: Cookie [4
bookieHost: "10.254.17.8:3181"
journalDir: "data2/bookkeeper/journal"
ledgerDirs: "1\tdata2/bookkeeper/ledgers"
instanceId: "3ed785b5-eb93-498c-9d57-b38ab8846e7b"
] is not matching with [4
bookieHost: "10.254.17.8:3181"
journalDir: "data/bookkeeper/journal"
ledgerDirs: "1\tdata/bookkeeper/ledgers"
instanceId: "3ed785b5-eb93-498c-9d57-b38ab8846e7b"

***To Reproduce***

As BUG says

***Expected behavior***

When I generate the cookie by the shell way, It should include "1\t"

**Comment by eolivelli** [comment]
this is a nasty problem, I am sorry.
maybe you can work around the problem just by using a sym link from data2 to data.
if your original problem is to expand bookie capacity you can add the new directory to the configuration and enable 'storage expansion', this way the bookie will start using the new directory as well

**Comment by sijie** [comment]
@eolivelli I think this is a bug we should fix.

**Comment by eolivelli** [comment]
@sijie sure that is clear
