### ISSUE TITLE
Warning about lack of version in exec-maven-plugin

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2155]
**BUG REPORT**

***Describe the bug***
Maven is complaining about the lack of a specific version in org.apache.bookkeeper.tests:scripts

We should explicitly set a version

***To Reproduce***

just run
`mvn clean install -DskipTests -Dstream`

> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for org.apache.bookkeeper.tests:scripts:jar:4.10.0-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 55, column 15
> [WARNING] 'build.plugins.plugin.version' for com.googlecode.maven-download-plugin:download-maven-plugin is missing. @ line 36, column 15
> [WARNING] 
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING] 
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING] 

***Expected behavior***

No warning

**Comment by sudoHackIn** [comment]
@Shoothzj may be we can close this issue, if it was fixed in related pr?

**Comment by Shoothzj** [comment]
@sudoHackIn Thanks for your contribution.
