### ISSUE TITLE
decommissionbookie not  complete correctly

### ISSUE THREAD

**Issue by sydnash** [apache/bookkeeper#2162]
**BUG REPORT**

***Describe the bug***

I have four bookie for pulsar now, when i close one bookie, i want to know dose it ledger has been re-replicated to other bookie. so i use the command like this:

    ./bookkeeper shell decommissionbookie  --bookieid  closedbookieip:3181
and then i find that looply print the follow mesages:

10:34:53.292 [main] INFO  org.apache.bookkeeper.client.BookKeeperAdmin - Count of Ledgers which need to be rereplicated: 1

and never stop.

***To Reproduce***

1. start bookie at a new machine
2. pulsar produce some message
3. stop bookie at the new machine
4. run command:  ./bookkeeper shell decommissionbookie  --bookieid  closedbookieip:3181

***Expected behavior***

I would like the following information to confirm that the bookie has been backed up:
```
 the ledgers stored in the given decommissioning booki:xxx:3181 are properly replicated
    
 no cookie to remove for the decommissioning bookie: xxx:3181, it could be deleted already
```

**Comment by sydnash** [comment]
this may be the storage in bookie is to large.

**Comment by bleacha870721** [comment]
May I ask how this problem was solved @sydnash

**Comment by sydnash** [comment]
> May I ask how this problem was solved @sydnash

I wait a long time for it to complete. up to three hours.
