### ISSUE TITLE
JournalChannel should throw IOException if it cannot seek to desired position

### ISSUE THREAD

**Issue by karanmehta93** [apache/bookkeeper#2178]
**BUG REPORT**

***Describe the bug***

Here's a piece of code from `JournalChannel.java`
```
try {
    if (position == START_OF_FILE) {
        if (formatVersion >= V5) {
            fc.position(HEADER_SIZE);
        } else if (formatVersion >= V2) {
            fc.position(VERSION_HEADER_SIZE);
        } else {
            fc.position(0);
        }
    } else {
        fc.position(position);
    }
} catch (IOException e) {
    LOG.error("Bookie journal file can seek to position :", e); <-- Swallows IOException and moves on
}
```

***To Reproduce***

Create a corrupt journal file. Try seeking to the desired position.

***Expected behavior***

IOException should be thrown and bookie should be shutdown. Not sure if a retry would help. It's not really recoverable since journal file is corrupted. 

@reddycharan @jvrao @eolivelli Another potential problem?

**Comment by karanmehta93** [comment]
I discovered this earlier when one of my bug fixes moved the file pointer to LONG.MAX_VALUE to indicate as the EOF for any journal file. However I had hit this issue then in some docker based test and I had fixed it, but forgot to file this issue. This is especially critical, even though the fix might be trivial.

**Comment by atris** [comment]
Can I please be assigned this issue?

**Comment by sijie** [comment]
@atris yeah feel free to take it if no pull request was sent out before.
