### ISSUE TITLE
TestAuth#testCloseMethodCalledOnAuthProvider is failing 

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#221]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

Run TestAuth.

- What did you expect to see?

The test should pass.

- What did you see instead?

The test failed. Because the shutdown is called twice after this change 9ddd9e6f9e48b03a57a2c78ec2630303abd49782 . So the assertion fails.

**Comment by sijie** [comment]
@reddycharan I don't think the right approach is to change to the tests. we should just make the shutdown call idempotent.

**Comment by eolivelli** [comment]
@reddycharan @sijie the close method of the factory is expected to be called once.
I am OK with the fact that close methods should be idempotent too but if it is possible it is better to make the call to "close" once. It is cleaner and for the long term it is the best approch

**Comment by sijie** [comment]
sorry I typed the wrong issue id at #437. revert the labels and milestone.
