### ISSUE TITLE
Write customMetadata on ledgers created by DistributedLog

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2218]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
It is very common for BookKeeper based applications to tag ledgers with common custom metadata, like:
- application: "name of the application"
- component: "component of the application"

DistributedLog is an API over BookKeeper and we need to write such tags on ledgers created by DistributedLog, in this case application won't be "distributedlog" but the name of the application itself and so the component.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
   Are you currently using any workarounds to address this issue?
should-have

3. Provide any additional detail on your proposed use case for this feature.
We could make a set of base custom metadata to write at each createLedger, and also add some dlog specific metadata (this will ease debugging as well)

**Comment by eolivelli** [comment]
@diegosalvi @dmercuriali PTAL

**Comment by dmercuriali** [comment]
Started working on this. It's not done but I created a draft PR if someone wants to take a look.
