### ISSUE TITLE
Add support for https in Vertx HTTP server

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2221]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Currently default http server (Vertx) do not start an https endpoint, we need such feature in order to be able to expose Booke endpoint with a minimal level of security. 

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
   Are you currently using any workarounds to address this issue?

must-have

3. Provide any additional detail on your proposed use case for this feature.

Configuration:
- keystore (PKCS12 format is enough, anyway just use the Verx config API)
- keystorePassword
- certificate chain (truststore)
- client auth (none, supported, required)

there is no need to enable automatic reload of the certificate

**Comment by eolivelli** [comment]
@dmercuriali PTAL

**Comment by Shoothzj** [comment]
this can be closed by #2995
