### ISSUE TITLE
  Which method is recommended in BookKeeper

### ISSUE THREAD

**Issue by huangdx0726** [apache/bookkeeper#2223]
**QUESTION**

In BookKeeper the `setZookeeper` method is Deprecated and `zk` method is recommended, But `zk` is Deprecated ,so which method should we use.

**Comment by eolivelli** [comment]
We are deprecating those methods for two reasons:
- BK client create its own zk client and the built-in one handles session expire automatically (you have to recreate the zk handle and do some stuff in case of session expire event)
- we are trying to not depend on zk any more, infact now we have two metadata providers zookeeper and etcd (partially implemented)

Reason 1) is the most important in my opinion.
It makes sense to re use an existing zk client only in case of short lived operations

**Comment by huangdx0726** [comment]
I see,Thinks.
