### ISSUE TITLE
Document for Decommissioning Bookies Not Found

### ISSUE THREAD

**Issue by codelipenghui** [apache/bookkeeper#2225]
**BUG REPORT**

![image](https://user-images.githubusercontent.com/12592133/71513771-c4e9f200-28d6-11ea-81e5-98b38a12e784.png)
![image](https://user-images.githubusercontent.com/12592133/71513782-cca99680-28d6-11ea-84cd-0f7c0d7946eb.png)

**Comment by Ghatage** [comment]
Hi @codelipenghui,

Please check: https://bookkeeper.apache.org/docs/4.11.0/admin/decomission/

Thanks @eolivelli for rebuilding the website and fixing this! I think we can close this.

**Comment by eolivelli** [comment]
@Ghatage the weird fact is that I didn't do anything special, I have just run the same script that our bot does to build the website.
I hope your new version of the website will be released soon

**Comment by Ghatage** [comment]
Closing this as its been fixed. Verified with 4.11.1 release website as well.
Thanks for reporting this!
