### ISSUE TITLE
Topics/labels used for categorizing this repo do not represent Bookkeeper well

### ISSUE THREAD

**Issue by ravisharda** [apache/bookkeeper#2229]
**Problem:** 

Currently, this repo has these topics specified for it: `bookkeeper`, `java` and `big-data`. This set of labels/topics do not accurately represent what Apache Bookkeeper is about, perhaps making it a tad harder for people to locate this project. 

**Suggestion:**

Add a few more topics like `Distributed-Log`, `Distributed-Commit-Log`, `write-ahead-logging`, etc. to this repo.

**Comment by sijie** [comment]
Created an INFRA jira to update the topics: https://issues.apache.org/jira/browse/INFRA-19774
