### ISSUE TITLE
In some cases, Bookie obtained the local IP of 127.0.0.1, which caused an abnormal report status.

### ISSUE THREAD

**Issue by liudezhi2098** [apache/bookkeeper#2239]
In some cases, Bookie obtained the local IP of 127.0.0.1, which caused an abnormal report status.

get ip method: 
`InetAddress.getLocalHost().getHostAddress();`

host
```

 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
  ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

_Although it can be solved by setting up the host, but the customer does not necessarily set it when using it, so if you do not rely on this when obtaining the IP, it will be much more friendly_

**Comment by eolivelli** [comment]
The fix for this problem is in https://github.com/apache/bookkeeper/pull/2240
