### ISSUE TITLE
TLS support for Metrics API

### ISSUE THREAD

**Issue by irairdon** [apache/bookkeeper#2244]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
I would like to be able to grab metrics from the metrics API using https rather than on standard http.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
   Are you currently using any workarounds to address this issue? Currently I have to file an exception to our security team to use this endpoint without being secured. 

3. Provide any additional detail on your proposed use case for this feature.

**Comment by eolivelli** [comment]
@mino181295 @dmercuriali  are you interested in providing a fix ?

**Comment by shoothzj** [comment]
I think we have already supported. You can try with the latest version. Feel free to open a new issue if you face any problem.
