### ISSUE TITLE
Subscription metrics name error

### ISSUE THREAD

**Issue by yangwenjie88** [apache/bookkeeper#2247]
The metric name of the document is `pulse_subscription_unacked_messages` but Prometheus print is `pulsar_subscription_unacked_massages`  ,  word `messages` spelling mistakes

**Comment by eolivelli** [comment]
It looks like an issue in Pulsar and not on Bookkeeper

**Comment by yangwenjie88** [comment]
> It looks like an issue in Pulsar and not on Bookkeeper

Oh,yes!
