### ISSUE TITLE
Remove Parameterized from CompactionTest

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#225]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

CompactionTest is a parameterized test. It is a bit inconvenient to run individual test on a parameterized test. It would be good to split them. 

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**nice-to-have**

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by jiazhai** [comment]
Merged by PR #226
