### ISSUE TITLE
compile bookkeeper meet a linker question

### ISSUE THREAD

**Issue by chengchampion** [apache/bookkeeper#2270]
Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.5.2:nar-validate (default-nar-validate) on project circe-checksum: Could not launch cmd.exe /X /C "link /?"，compile bookkeeper meet this question，how to do?

**Comment by eolivelli** [comment]
Are you on Windows?
Are you using cygwin or git bash ?

**Comment by chengchampion** [comment]
> Are you on Windows?
> Are you using cygwin or git bash ?
yes i use windows. i just use ideal compile bookkeeper source code.and then meet this question.

**Comment by sijie** [comment]
@chengchampion Currently the bookkeeper project builds some native code. I don't think the build script supports windows yet.

**Comment by yahya99223** [comment]
Any ideas on how to overcome this issue on Win 10?

**Comment by liqi19950722** [comment]
compile in wsl, it works
