### ISSUE TITLE
Add ledger metadata to Ledger created by StreamStorage Module

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2288]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Please add meaningful information to ledger created by StreamStorage module.
Namely:
-  DLCheckpointStore
- AbstractStateStoreWithJournal

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
   Are you currently using any workarounds to address this issue?

nice-to-have

3. Provide any additional detail on your proposed use case for this feature.

With a visual tool that is able to inspect a BookKeeper Cluster we are seeing ledgers created by StreamStorage service that do not have metadata and it is not possible to understand which application created them.
Apache Pulsar is tagging its own ledgers with "application:pulsar" and other meaningful tags.
We should at least mark those ledgers with application: bk-stream-storage-service and some reference to the purpose of the ledger

**Comment by eolivelli** [comment]
a preparative work has been done by @dmercuriali  with b84178af53d631b268143f9b8b0a3c3f731bf68a

**Comment by dmercuriali** [comment]
Picking this up

**Comment by sijie** [comment]
It is fixed by #2296
