### ISSUE TITLE
distribute Python apache-bookkeeper-client as a Conda package

### ISSUE THREAD

**Issue by chairmank** [apache/bookkeeper#2289]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
I would like to be able to install the Python client library (`apache-bookkeeper-client`) using the [Conda](https://docs.conda.io/) package manager.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
Conda is the preferred package manager for a significant community of Python users. `apache-bookkeeper-client` is already distributed in Wheel format through [PyPI](https://pypi.org/project/apache-bookkeeper-client/). However, the Wheel format is not convenient for Conda users.

3. Provide any additional detail on your proposed use case for this feature.
The [Conda package format](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html) is well-documented. There are numerous examples of build recipes for Conda packages in the [conda-forge](https://conda-forge.org/) community.

There is a related feature request for [Pulsar](https://github.com/apache/pulsar-client-python/issues/32).

**Comment by chairmank** [comment]
I am familiar with Conda packages and volunteer to help.

**Comment by eolivelli** [comment]
@chairmank thank you, please send a PR.
If we have to update our release procedure please send a PR for that as well, you can find it on the "site" subdirectory

**Comment by shoothzj** [comment]
@chairmank Closed by no update. If you still want to work on it, feel free to reopen it.
