### ISSUE TITLE
Where to config quorum mode?

### ISSUE THREAD

**Issue by Shoothzj** [apache/bookkeeper#2304]
![image](https://user-images.githubusercontent.com/12933197/78623362-12a0ce00-78ba-11ea-9275-8572a146be84.png)

When I saw this, I search it for google, config file, 4.10 source code, I can't find where to config quorum type.

**Comment by sijie** [comment]
@Shoothzj can you point the link of the documentation page?

**Comment by Shoothzj** [comment]
![image](https://user-images.githubusercontent.com/12933197/79527602-9cab1c80-809a-11ea-85f3-f7d961097204.png)

https://bookkeeper.apache.org/docs/latest/admin/bookies/

**Comment by Shoothzj** [comment]
It's should be a out-dated doc. Close this issue.
