### ISSUE TITLE
Can not run localbookie on jdk 14

### ISSUE THREAD

**Issue by Shoothzj** [apache/bookkeeper#2308]
**BUG REPORT**

***Describe the bug***
Can not run localbookie on jdk 14. Bk can not connect to Zk.
The old version of zookeeper, org.apache.zookeeper.client.StaticHostProvider#getHostString can not read the right value. For the resaon:

Unresolved InetSocketAddress.toString in different jdk version return different value.
1. jdk8 localhost:2181
2.jdk14 localhost:2181/unresloved

I think the solution is to upgrade the zookeeper version.

**Comment by eolivelli** [comment]
It is due to Zookeeper 3.4 client.
We must upgrade to 3.5.7.
There is a pending PR for the upgrade.

The pr is not moving forward.
If you have time would you like to help with that patch?

**Comment by Shoothzj** [comment]
I would like to try this weekend and see if I can do it .I am freshly BookKeeper user

**Comment by eolivelli** [comment]
This is the pr #2112  
it is failing on Integration Tests and needs a rebase
cc @dmercuriali

**Comment by Ghatage** [comment]
@Shoothzj can you please rebase and try again since #2112 is merged?

**Comment by eolivelli** [comment]
this issue is solved in 4.11, as we upgrade ZK
