### ISSUE TITLE
[Doc] How do I add a new bookie? 

### ISSUE THREAD

**Issue by LiamClarkeNZ** [apache/bookkeeper#2328]
I am reading the documentation to advise a client on technical decisions. Scaling their system is part of that decision. The documentation neither explicitly or implicitly specifies how adding a new Bookie to a BookKeeper cluster works. Does it just work? Or do I need to take manual steps? Should I enable autorecovery? 

Etc. etc.

**Comment by eolivelli** [comment]
Just start it as the first bookie.
It is all automatic

**Comment by LiamClarkeNZ** [comment]
> Just start it as the first bookie.
> It is all automatic

Thanks @eolivelli - will the Autorecovery daemon redistribute ledger replicas when the cluster increases in size? Or does it maintain existing ensembles but utilise the new bookie for any new ledgers?

**Comment by eolivelli** [comment]
Ledgers will stay on the original bookies if they are available.
New ledgers will go to new bookies.
Broken ledgers will be replicated to new bookies.

You can create your own LedgerPlacementPolicy that drives the placement of data

**Comment by rvashishth** [comment]
@eolivelli,  How the cluster behave if we need to scale down?  [Docs explain the way to manually decommission bookies](https://bookkeeper.apache.org/docs/latest/admin/decomission/),  is there a way to auto-decommission the bookies when deployed on Kubernetes as Statefulset.

**Comment by sijie** [comment]
@rvashishth you can write a script to automate the process. You can check https://github.com/streamnative/charts/blob/master/scripts/pulsar/decommission_bookies.sh for example.
