### ISSUE TITLE
Configurable keep alive settings for the client

### ISSUE THREAD

**Issue by rivernate** [apache/bookkeeper#2335]
**FEATURE REQUEST**

1. The current keep alive setting for the BK client is just on or off using [ClientConfiguration.java#getClientSockKeepalive](https://github.com/apache/bookkeeper/blob/adf086d54f85fa5321574300360f7fd86d47fe8b/bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java#L358). The behavior of which is determined by the operating system. There should be a way to configure the keep alive timeout and other settings without having to change the defaults for the entire operating system

2. **"should-have"** 
   We are currently working around this by changing the OS default setting for TCP keep alive

3. For portability this could be solved either at the application level with a heartbeat message of some kind, or by closing the connection if enough timeouts are encountered.

**Comment by eolivelli** [comment]
@rivernate 
do you have time to send a PR ?

**Comment by rivernate** [comment]
@eolivelli: I don't right now, we are currently getting by using the OS TCP keep alive settings.  But wanted to surface the problem we where having for visibility.

**Comment by merlimat** [comment]
> using the OS TCP keep alive setting

The OS TCP keep-alive can be problematic, in that I believe the configuration might be tricky to adjust and the minimum time is anyway ~5min, which is a very long time.

**Comment by rivernate** [comment]
Yeah, it's not an ideal solution for sure. We have ours dialed back to 3 probes 11 seconds apart starting 1 second after a connection is idle, so ~45 sec timeout. That has solved the problems we were seeing but it would be nice to not rely on OS configuration for this, especially since it is a system wide configuration.

**Comment by karanmehta93** [comment]
@jvrao @reddycharan This might be of our interest.

**Comment by shoothzj** [comment]
closed by stale.
