### ISSUE TITLE
Is it possible to automatically check zookeeper and create bookkeeper metadata when starting bookkeeper?

### ISSUE THREAD

**Issue by coolbeevip** [apache/bookkeeper#2345]
[main:ZKRegistrationManager@379] - BookKeeper metadata doesn't exist in zookeeper. Has the cluster been initialized? Try running bin/bookkeeper shell metaformat

**Comment by eolivelli** [comment]
You can use BookkeeperAdmin class.
It has a meta format method that does nothing if the cluster has already been initialized

**Comment by coolbeevip** [comment]
Why not use BookkeeperAdmin in ZKRegistrationManager to automatically initialize the cluster, Any explanation for that?

```
    @Override
    public String getClusterInstanceId() throws BookieException {
        String instanceId = null;
        try {
            if (zk.exists(ledgersRootPath, null) == null) {
                try {
                    BookKeeperAdmin.initNewCluster(conf);
                } catch (Exception e) {
                    log.error("BookKeeper metadata doesn't exist in zookeeper. "
                        + "Has the cluster been initialized? "
                        + "Try running bin/bookkeeper shell metaformat");
                    throw new KeeperException.NoNodeException("BookKeeper metadata");
                }
            }
```

**Comment by sijie** [comment]
@coolbeevip adding initialization or format code into every bookie process is not a good idea. since every bookie will attempt to initialize or reformat the metadata. This usually would introduce many consistency problems. So we recommend administrators to initialize the metadata when setting up the cluster.

**Comment by coolbeevip** [comment]
> @coolbeevip adding initialization or format code into every bookie process is not a good idea. since every bookie will attempt to initialize or reformat the metadata. This usually would introduce many consistency problems. So we recommend administrators to initialize the metadata when setting up the cluster.

Thank you for your reply
