### ISSUE TITLE
Certificate role based authorization for Bookkeeper

### ISSUE THREAD

**Issue by Ghatage** [apache/bookkeeper#2354]
This is the master ticket for tracking BP-41.

Even with TLS/mTLS authentication, any other service with rootCA is able to access Bookkeeper which is unacceptable as Bookkeeper is the source or truth.

This feature allows a predefined set of roles to be 'whitelisted' to be able
to access bookkeeper based on their client certificates.
It also introduces a structure for these roles to adhere to in order to scale.

Proposal PR - [Link](https://docs.google.com/document/d/15atmnl3pS4HrhQ6fV-gSY7faIVlmU91KoApBaXPjEfg/edit?usp=sharing)

**Comment by EronWright** [comment]
Just a comment on the BP itself, it is described as BP-41 but another proposal uses that identifier ([BP-41: Separate BookieId from Bookie Network Address](http://bookkeeper.apache.org/bps/BP-41-bookieid/)).  Meanwhile this proposal is not listed on the community site ([ref](http://bookkeeper.apache.org/community/bookkeeper_proposals/)).

**Comment by shoothzj** [comment]
closed by #2429
