### ISSUE TITLE
Add a command to list the ledgers are still alive in entry log file

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#2358]
*Motivation*

For troubleshooting bookkeeper disk usage issues, having a tool to list the ledgers that are still alive in the entry log file is super useful.

**Comment by rudy2steiner** [comment]
I'd like to try it, please assign it to me !

**Comment by eolivelli** [comment]
Just start working and send the PR.
Actually we cannot assign the issue to you

**Comment by rudy2steiner** [comment]
Would you mind explaining in what case , how to use the command and what the input and output you expect, I'm interested to handle this issue @sijie

**Comment by rudy2steiner** [comment]
do you mean to dump CompactableLedgerStorage.getActiveLedgersInRange,is that right?

**Comment by sijie** [comment]
@rudy2steiner My requirement is simple - the command will list all the ledgers of an entry log file are still "active" (exists in metadata storage)

**Comment by rudy2steiner** [comment]
I notice there is a piece of code(BookieShell.printEntryLogMetadata): using a specific entry log file id to read the entry log file meta(EntryLogMetadata) which contains all ledger id, is that meet your requirement but without checking the ledger is active or not?

**Comment by sijie** [comment]
Your understanding is correct.

**Comment by rudy2steiner** [comment]
ok, thanks for your confirmation

**Comment by sijie** [comment]
This is fixed by #2369
