### ISSUE TITLE
When I start up bookie,I found an extra port I don’t know

### ISSUE THREAD

**Issue by Gray-Fullbuster** [apache/bookkeeper#2359]
***netstat -anp | grep -i 'tcp\|udp' | grep LISTEN***
 
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp &ensp;    0 &ensp;      0 0.0.0.0:44659  &ensp;          0.0.0.0:*  &ensp;              LISTEN&ensp;   26062/java
tcp &ensp;       0   &ensp;   0 0.0.0.0:32001        &ensp;   0.0.0.0:*     &ensp;          LISTEN      &ensp;26062/java
tcp  &ensp;      0  &ensp;    0 0.0.0.0:32002   &ensp;        0.0.0.0:*   &ensp;            LISTEN      &ensp;26062/java

Currently, we have enabled 2 ports,32001 is bookieport,32002 is prometheusport,but to 44659 ,I can't use this port,and when i restart bookie this port will change.I cant't understand where go wrong.
26062 is bookie's pid
bookkeeper version = 4.10.0

**Comment by jiazhai** [comment]
@Gray-Fullbuster Did you enabled HttpServer by set `httpServerEnabled=true`?

**Comment by jiazhai** [comment]
But it is strange since it will change after a restart. It does not seem like a config issue.
Does every bookie have the same issue?

**Comment by Gray-Fullbuster** [comment]
@jiazhai I set httpServerEnabled=false.Every bookie has its unknown,random port.

**Comment by eolivelli** [comment]
Are you enabling JMX? If so them it can be JMX

**Comment by Gray-Fullbuster** [comment]
Yes,I find this command in _bookkeeper_.
_exec ${JAVA} ${OPTS} ${JMX_ARGS} org.apache.bookkeeper.server.Main --conf ${BOOKIE_CONF} $@_
so,i delete _${JMX_ARGS}_,this port disappeared.thank you for the help

**Comment by eolivelli** [comment]
There should be a way to configure a fixed port.
But if you are not going to use JMX at all it is better to have it disabled.

**Comment by Gray-Fullbuster** [comment]
I want to bind 0.0.0.0 to native ip.How should i do?

**Comment by eolivelli** [comment]
Are you talking about JMX or about the Bookie endpoint ?
in the case of Bookie Endpoint it is not possible, because the ID of the bookie is made of pubblic-address + bookiePort
this fact will change in the future (hopefully 4.12) but now this is how it works.

So you can't bind to 0.0.0.0

You could bind to 0.0.0.0 but you have to configure the "advertised address" that is the public DNS name that the bookie advertises on discovery service. This address cannot be easily changed in teh future, because it is written on ledger metadata

**Comment by Gray-Fullbuster** [comment]
Sorry,My description is wrong.I want to change 0.0.0.0:32001 to 127.0.0.1:32001

**Comment by eolivelli** [comment]
@Gray-Fullbuster  please check this out
https://stackoverflow.com/questions/331615/how-to-have-jmx-bind-to-a-specific-interface

**Comment by eolivelli** [comment]
can we close this issue @Gray-Fullbuster  ? did you manage to achieve your goal ?
