### ISSUE TITLE
Is it better that the `listbookies` command return bookieIds?

### ISSUE THREAD

**Issue by mikecaat** [apache/bookkeeper#2376]
**BUG REPORT**

Since I'm not familiar with this product, 
please let me know if there are my misunderstood points.

***Describe the bug***

Since I want to test the scale in feature of bookkeeper,
I want to check which ledgers are stored on which server.

To do so, I decide to use `listledgers` command with `-bookieid` option.
But I misunderstood that `listbookies` don't output bookieIds.

( BTW, the option `-bookieid` is missing in the [latest document](
http://bookkeeper.apache.org/docs/latest/reference/cli/#bookkeeper-shell-listledgers). )

I think these behavior can confuse some users.
Is it better that `listbookies` return the unique bookieIds?

***To Reproduce***

1. build bookkeeper

I use the following commit source code.
commit : cd0970101306a2c031506ea9cea402803639e806 

2. start bookkeeper with default configuration

```
> bin/bookkeeper localbookie 10   
```

3. insert some data
 
```
> bin/bookkeeper shell simpletest --ensemble 3 --writeQuorum 2 --ackQuorum 1 --numEntries  1
```

4.  show list bookies

I misunderstood that the following output shows bookieIds.

```
> bin/bookkeeper shell listbookies -a  
...
All Bookies :
127.0.1.1(hostname):5000
..
```

5. get list ledgers written in the specific bookie.

My struggle point was the error was not occurred.
I think the reason is that specified bookieId have [colon and two parts](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/net/BookieSocketAddress.java#L65) .

```
> bin/bookkeeper shell listledgers -bookieid "127.0.1.1(hostname):5000"
```

The following code works. Is the "127.0.1.1:5000" real bookieId?

```
> bin/bookkeeper shell listledgers -bookieid "127.0.1.1:5000"
```

The main problem is [the match condition](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java#L1587
) does not work.

***Expected behavior***

If there is a unique bookieId, it's better that `listbookies` returns it and
`listledgers` should check using the id.

How do you think? If you are ok, I'll try to fix it.

**Comment by sijie** [comment]
@mikecaat I agreed that it is better to use bookieId across different places. Although sometime the bookie id can be an IP address, it would be good to also display the domain name. So your suggestion is great in general. But we should also consider including the domain information when listing bookies.

**Comment by mikecaat** [comment]
@sijie Thanks for replying. How about the following output?

```
> bin/bookkeeper shell listbookies -a  
...
All Bookies:
BookieID:127.0.1.1:5000,IP:127.0.1.1,Port:5000,Hostname:localhost
...
```

**Comment by sijie** [comment]
Sounds good.

**Comment by rudy2steiner** [comment]
I'd like to help

**Comment by Ghatage** [comment]
I think we can close this. @eolivelli's [BookieId client side change has this requirement satisfied](https://github.com/apache/bookkeeper/commit/057f85ec1b977379938350f12d7ec99ff1162f29#diff-cc8d018692ca6293f9d0cc157beb6c654f2519aab1ad3e83b8402f31c76eff7dR69).
Please let me know if we can close this issue @mikecaat

**Comment by mikecaat** [comment]
Great, we can close.
