### ISSUE TITLE
ContextualVersionConflict grpcio dependency conflict

### ISSUE THREAD

**Issue by lbenc135** [apache/bookkeeper#2377]
**BUG REPORT**

ORIGINAL ISSUE: https://github.com/apache/pulsar/issues/7477

***Describe the bug***

When installing `pulsar-client==2.6.0` there's a dependency conflict with grpcio library.

In `apache-bookkeeper-client==4.11.0` the dependency `grpcio<1.26.0` was introduced, but `pulsar-client` installs the latest version.

The dependency tree is (as I understand it):

- pulsar-client (2.6.0)
  - grpcio (any)
  - apache-bookkeeper-client (4.11.0)
    - grpcio >=1.8.2,<1.26.0

***To Reproduce***

1. pip install pulsar-client==2.6.0
2. grpcio==1.30.0 gets installed
3. If I try to build my own pip package with pulsar-client as dependency, and try to build it, I get the ContextualVersionConflict error

***Expected behavior***

I expect the correct version to be installed and/or the dependency tree to be fixed.

**Comment by nsriram13** [comment]
+1 for this issue. Can the dependency for be relaxed for bookkeeper Python client to be `grpcio (any)`?

**Comment by ca-simone-chiorazzo** [comment]
Is there any update on this? Due to the fact that bookkeeper requires grpcio==1.25.0, we are not able to install grpcio on a max os x environment with python3.8 because no wheel has been published. 

Is there a plan to relax this dependency?

**Comment by eolivelli** [comment]
@ca-simone-chiorazzo do you have time to provide a fix ?

**Comment by ca-simone-chiorazzo** [comment]
@eolivelli Yes, I'm going to open a PR with a fix on the requirements

**Comment by ca-simone-chiorazzo** [comment]
@eolivelli I've opened https://github.com/apache/bookkeeper/pull/2432
