### ISSUE TITLE
BookKeeper client should handle IP address changes of bookkeeper pods

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#2382]
When bookies are running on Kubernetes and are using `useHostNameAsBookieID` to advertise bookie address, bookies are using pod names as advertised addresses. When a bookie pod is restarted, the pod name is not changed but the IP address has been changed. The bookkeeper client doesn't have a mechanism to realize the IP address change. So the bookkeeper client has to wait until TCP timeout to re-establish the connections to the new bookie pod.

**Comment by eolivelli** [comment]
This issue will be covered by BP-41

**Comment by eolivelli** [comment]
this issue is covered by BP-41.

the fix is to set bookieId in your bk_server.conf.
we should document a possible upgrade story, but for new clusters it is quite easy to do it.

This is how we did it in HerdDB
https://github.com/diennea/herddb/commit/a77804d67cc4be1668f75dea040c356fa4542131
