### ISSUE TITLE
Create HTTP Server provider for Embedded Bookies

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2388]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
If you run the Bookie inside the same process of another storage system (like https://github.com/diennea/herddb or https://github.com/diennea/blobit) and you want to expose the Bookie API on the same Java Web Container, you need to implement it as a Java Servlet.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
   Are you currently using any workarounds to address this issue?

nice-to-have

3. Provide any additional detail on your proposed use case for this feature.
An example is here
https://github.com/diennea/blobit/blob/master/blobit-services/src/main/java/blobit/server/ServletHttpServer.java

**Comment by rudy2steiner** [comment]
Please assign it to me, I'll work on this!

**Comment by eolivelli** [comment]
@rudy2steiner thank you

With current github permission scheme I cannot assign the issue to you, but you can work on it, as you written it here I guess no one else will work on this task

This is an example, that code is working well on BlobIt and we are copy/pasted it in other products in my company :-) 
https://github.com/diennea/blobit/blob/master/blobit-services/src/main/java/blobit/server/ServletHttpServer.java

if you find a better way do it your way of course

**Comment by rudy2steiner** [comment]
ok
