### ISSUE TITLE
Static Source Code Security Scanner showing Command Injection vulnerability in Bookkeeper

### ISSUE THREAD

**Issue by deepanjanpal** [apache/bookkeeper#2391]
**Static Source Code Security Scanner showing Command Injection vulnerability in Bookkeeper**

***OS Command Injection in Bookkeeper***

***To Reproduce***

1. Launch a source code scan with Checkmarx Static Code Scanner
2. After completion of source code scan , tool throws OS command injection vulnerability against the files mentioned in the attached document.

***Expected behavior***

OS Command Injection vulnerability should not be present in any files of Bookkeeper. All user input should be sanitized to check for any OS commands and either whitelist or blacklist those commands.

[Pravega_Bookkeeper_OS Command Injection.xlsx](https://github.com/apache/bookkeeper/files/4994467/Pravega_Bookkeeper_OS.Command.Injection.xlsx)

**Comment by deepanjanpal** [comment]
Hi @sijie , 
Thanks for looking into it , may i please request in case any updates over here.

**Comment by deepanjanpal** [comment]
Hi ,
any updates on this?

**Comment by bmaluruEMC** [comment]
Any update on this please?

**Comment by eolivelli** [comment]
we are working on releasing BK 4.11.1 and also we are fixing the Docker autobuild (see #2446 )

**Comment by shoothzj** [comment]
@deepanjanpal Could you please try again with the latest image. I believe many security problems is solved and we have been switching to ubuntu 20.04.

**Comment by deepanjanpal** [comment]
Hi Team,

Can a CVE ID be raised against this security vulnerability now this is
confirmed as fixed. Will be very helpful, thanks.

Thanks and Regards
Deepanjan Pal.
