### ISSUE TITLE
Detected both log4j-over-slf4j.jar AND slf4j-log4j12.jar on the class path, preempting StackOverflowError.

### ISSUE THREAD

**Issue by Technoboy-** [apache/bookkeeper#2405]
I find that bk depends on log4j-over-slf4j and slf4j-log4j12, sometimes this will cause error. 
http://www.slf4j.org/codes.html#log4jDelegationLoop

**Comment by eolivelli** [comment]
@Technoboy- thanks for reporting this issue.
Do you mind trying to contribute a fix ?

**Comment by Technoboy-** [comment]
> @Technoboy- thanks for reporting this issue.
> Do you mind trying to contribute a fix ?

Sure, I will try to fix it , you can assign it to me.

**Comment by eolivelli** [comment]
Unfortunately we can "assign" an issue only to users with write permissions ('committers').
Feel free to work on the issue, when we merge your contribution to the repository you will be listed as author
