### ISSUE TITLE
[documentation] "The flat ledger manager is the default" is a false claim

### ISSUE THREAD

**Issue by lhotari** [apache/bookkeeper#2408]
The documentation claims that "The flat ledger manager is the default". 
https://github.com/apache/bookkeeper/blob/master/site/docs/latest/getting-started/concepts.md#use-the-flat-ledger-manager-in-most-cases

However, the default is HierarchicalLedgerManagerFactory and this can be seen at
https://github.com/apache/bookkeeper/blob/a0d49fcb65a40b2b49fbfb6c50f60c7a9f66f67f/bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/AbstractZkLedgerManagerFactory.java#L316

The documentation for configuration already mentions hierarchical as the default
https://github.com/apache/bookkeeper/blob/94912a9fdca68391866baf598c36708e406728f8/site/_data/config/bk_server.yaml#L485-L495 

However, It would be better to remove "The flat ledger manager is the default " from the sentence in concepts.md.

**Comment by eolivelli** [comment]
You are right 
It is also deprecated.

Can you please send PR? The website is in this repository

**Comment by WJL3333** [comment]
submit a pr here https://github.com/apache/bookkeeper/pull/2413
