### ISSUE TITLE
How to fence ledger from bookkeeper shell？

### ISSUE THREAD

**Issue by WJL3333** [apache/bookkeeper#2420]
for test propose, when use `./bookkeeper shell simpletest -ensemble 3 -writeQuorum 3 -ackQuorum 3 -numEntries 10000`
for some time. just kill the command. the ledger metadata left in OPEN status.

is there any way to fence ledger from command line ?

**Comment by eolivelli** [comment]
you can use the 'readledger' with -force-recovery option
something like`
bookkeeper shell readledger -ledgerid XXX -force-recovery `

please close this ticket if you see it works

**Comment by WJL3333** [comment]
tks, i'll close the issue.
