### ISSUE TITLE
Why DbLedgerStorage doesn't use indexDirectories to store index ？

### ISSUE THREAD

**Issue by lifepuzzlefun** [apache/bookkeeper#2421]
in this line just set basePath use ledgerDirsManager which only manage one dir
https://github.com/apache/bookkeeper/blob/2c3d8f55895890e73b58a43e337f7ff9ac140675/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java#L143

and just use variable basePath to initialize ledgerDirsManager and LedgerMetadataIndex
https://github.com/apache/bookkeeper/blob/2c3d8f55895890e73b58a43e337f7ff9ac140675/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java#L162

the indexDirectories is not use at all.

does this means indexDirectories will be ignored when use DbLedgerStorage ？

**Comment by jiazhai** [comment]
@WJL3333 right. indexDirectories will be ignored when use DbLedgerStorage .  indexDirectories is used in other type of ledgerstorage, such as interlivedLedgerStorage

**Comment by WJL3333** [comment]
@jiazhai thanks for reply. is there an plan to use this config? i wonder if rocksdb for index and entrylogger on the same disk 
harm the performance. if this is just ok. maybe i can fix the document.

**Comment by eolivelli** [comment]
I can't remember this request in the past.
We should definitely take care of this.

It will be necessary to handle backward compatibility, that is to let bookies that have RocksDB on the current folder work

**Comment by WJL3333** [comment]
@eolivelli thanks for reply. it seems a lot to take care. i need take a deep look inside.
