### ISSUE TITLE
asyncAddEntry fails with NPE with LedgerHandler created with createLedgerAdv

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#243]
It turns out on 4.5 that "asyncAddEntry" fails with NPE with LedgerHandler created with createLedgerAdv

This is a simple code to reproduce the error
```
LedgerHandle lh = bkc.createLedgerAdv(1, 1, 1, digestType, ledgerPassword);
lh.addEntry(data);

```
This is the error, it is due to the fact that the entryId has not been assigned

```
java.lang.NullPointerException
	at org.apache.bookkeeper.client.PendingAddOp.initiate(PendingAddOp.java:195)
	at org.apache.bookkeeper.client.LedgerHandleAdv$2.safeRun(LedgerHandleAdv.java:216)
```

I have marked the issue as blocker because it concerns the main function of BK, that is "addEntry"

**Comment by eolivelli** [comment]
The signature of asyncAddEntry is wrong, it does not throw BKException as it is an async function
```
public void asyncAddEntry(final long entryId, final byte[] data, final int offset, final int length,
            final AddCallback cb, final Object ctx) throws BKException
```

Maybe we can fix this error too

**Comment by sijie** [comment]
@eolivelli can you share the code that cause the NPE?

**Comment by eolivelli** [comment]
@sijie  I have modified the description, the new testcase in PR #244 demostrates the problem
