### ISSUE TITLE
Error about the data directories in the docker README.md

### ISSUE THREAD

**Issue by rdehouss** [apache/bookkeeper#2437]
**BUG REPORT**

***Describe the bug***

A typo slipped in the [README.md of the docker folder](https://github.com/apache/bookkeeper/tree/master/docker#bk_data_dir)

It says

> Default value is "/data/bookkeeper", which contains volumes /data/bookkeeper/journal, /data/bookkeeper/ledger and /data/bookkeeper/index to hold Bookkeeper data in docker.

The error is on `/data/bookkeeper/ledger` which should be `/data/bookkeeper/ledgers` (with a "s" at the end)

***To Reproduce***

1. Go to [README.md#L220](https://github.com/apache/bookkeeper/blob/master/docker/README.md#L220)
2. See error

***Expected behavior***

The documentation should say
> Default value is "/data/bookkeeper", which contains volumes `/data/bookkeeper/journal`, `/data/bookkeeper/ledgers` and `/data/bookkeeper/index` to hold Bookkeeper data in docker.

***Screenshots***

N/A

***Additional context***

None

**Comment by eolivelli** [comment]
@rdehouss thanks for your bug report. do you mind sending a simple PR to fix the issue ?
