### ISSUE TITLE
[Documentation] New website - Complete the 'Project' page

### ISSUE THREAD

**Issue by Ghatage** [apache/bookkeeper#2442]
### **Preamble**
The current Apache Bookkeeper website is a custom made and hard to maintain. Most frameworks and dependencies it uses are out of date, so we decided to move on to building a Docusaurus based website, inspired by our sister project Apache Pulsar's website.
For our new docusaurus based website, we have the initial skeleton of the code already merged (under `site2/`). We now need your help to flush out the website with its content and design.
<hr>

### **Task: Complete the 'Project' Page**
You can see our Privacy Policy declaration if you go to our current website at: https://bookkeeper.apache.org/project/privacy/
If you build our new website locally and go to the Project page, you can see that we are missing the 'Privacy Policy'.
The requirement of this task is to create a new markdown page for privacy policy with the same content as our current website and link it in the project page as a new panel besides the current 'Bylaws' panel.

**Steps:**
* Explore `site2/` to see how and where markdown pages are created, handled and linked
* Create one for privacy policy, link it in the project page
* Make sure that your changes can build and run the website by testing it locally (how to mentioned below).
* Then open a pull request and reference this issue in the pull request.

**How to build and test your changes to the website locally** <br>
You will need `Node >= 8.x` and `Yarn >= 1.5`.

```
git clone https://github.com/apache/bookkeeper.git
cd bookkeeper/site2/website
yarn install
yarn start
```

Use the [Apache Pulsar website code](https://github.com/apache/pulsar/tree/master/site2) as a north star for our development.

**Comment by rudy2steiner** [comment]
I will work on it

**Comment by Ghatage** [comment]
Hi @rudy2steiner any update?

**Comment by rudy2steiner** [comment]
sorry, for late response, i will complete it in this week!
