### ISSUE TITLE
[Documentation] New Website - Complete the 'Community' Page

### ISSUE THREAD

**Issue by Ghatage** [apache/bookkeeper#2443]
### **Preamble**
The current Apache Bookkeeper website is a custom made and hard to maintain. Most frameworks and dependencies it uses are out of date, so we decided to move on to building a Docusaurus based website, inspired by our sister project Apache Pulsar's website.
For our new docusaurus based website, we have the initial skeleton of the code already merged (under `site2/`). We now need your help to flush out the website with its content and design.
<hr>

### **Task: Complete the 'Community' page**
You can see our current community page if you go to our current website at: https://bookkeeper.apache.org/community/
If you build our new website locally and go to the Community page, you can see that we are missing sections such as the 
* '[Mailing Lists](https://bookkeeper.apache.org/community/mailing-lists/)' page and a link to it in a panel
* '[Slack](https://bookkeeper.apache.org/community/slack/)' panel (All content of this page can be in the panel itself, no need for a new page)
* '[Release Management](https://bookkeeper.apache.org/community/releases/)' page and a link to it in a panel
* '[Community Meetings](https://bookkeeper.apache.org/community/meeting/)' page and a link to it in a panel
* '[Contribution guide](https://bookkeeper.apache.org/community/contributing/)' page and a link to it in a panel
* '[Coding guide](https://bookkeeper.apache.org/community/coding_guide/)' page and a link to it in a panel
* '[Testing guide](https://bookkeeper.apache.org/community/testing/)' page and a link to it in a panel
* '[Issue report guide](https://bookkeeper.apache.org/community/issue-report/)' page and a link to it in a panel
* '[Release guide](https://bookkeeper.apache.org/community/release_guide/)' page and a link to it in a panel
* '[Presentations](https://bookkeeper.apache.org/community/presentations/)' page and a link to it in a panel
* '[BookKeeper Proposals](https://bookkeeper.apache.org/community/bookkeeper_proposals/)' page and a link to it in a panel

The requirement of this task is to create a new markdown pages for the above mentioned links with the same content as our current website and link it in the community page as a new panels.

**Steps:**
* Explore `site2/` to see how and where markdown pages are created, handled and linked
* Create one for Mailing Lists, link it in the community page
* Make sure that your changes can build and run the website by testing it locally (how to mentioned below).
* Create the rest of the pages similar to the Mailing List page, confirm builds happen properly
* Then open a pull request and reference this issue in the pull request.

**How to build and test your changes to the website locally** <br>
You will need `Node >= 8.x` and `Yarn >= 1.5`.

```
git clone https://github.com/apache/bookkeeper.git
cd bookkeeper/site2/website
yarn install
yarn start
```

Use the [Apache Pulsar website code](https://github.com/apache/pulsar/tree/master/site2) as a north star for our development.

**Comment by Abhey** [comment]
@Ghatage I would like to work on this one.
