### ISSUE TITLE
Auditor#startAudit seems a bug.

### ISSUE THREAD

**Issue by Technoboy-** [apache/bookkeeper#2444]
https://github.com/apache/bookkeeper/blob/b95c753a87a97114012e0af2b11972c3df01d48d/bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java#L1040
Auditor#startAudit will set shutDownTask to false , 
![image](https://user-images.githubusercontent.com/6297296/96358044-76dbfe80-1135-11eb-98e7-865a808a1341.png)

and let  https://github.com/apache/bookkeeper/blob/b95c753a87a97114012e0af2b11972c3df01d48d/bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java#L1985
never do submitShutdownTask.
![image](https://user-images.githubusercontent.com/6297296/96358059-a8ed6080-1135-11eb-83a1-82343cb55165.png)

**Comment by Technoboy-** [comment]
cc @eolivelli @sijie

**Comment by eolivelli** [comment]
Why did you close this issue?
