### ISSUE TITLE
[Documentation] New website - Add sidebar to the documentation page

### ISSUE THREAD

**Issue by Ghatage** [apache/bookkeeper#2451]
### **Preamble**
The current Apache Bookkeeper website is a custom made and hard to maintain. Most frameworks and dependencies it uses are out of date, so we decided to move on to building a Docusaurus based website, inspired by our sister project Apache Pulsar's website.
For our new docusaurus based website, we have the initial skeleton of the code already merged (under `site2/`). We now need your help to flush out the website with its content and design.
<hr>

### **Task: Add sidebar to the Documentation Page**
The documentation page is perhaps the most important page for our new website.
We want to add in side bars to the documentation sections. [As seen on the left hand side of Pulsar's website](https://pulsar.apache.org/docs/en/standalone/).
Docusaurus comes with built in sidebar functionality in which we have to add the details about the `.md` files to `sidebars.json`.
The goal of this work is to simply setup the sidebar with one or two dummy markdown files so that the documentation page renders them.
Next steps will be creating a versions page to handle past version documentation etc. 

**Steps:**
* Explore `site2/` to see how and where markdown pages are created, handled and linked
* Create one for privacy policy, link it in the project page
* Make sure that your changes can build and run the website by testing it locally (how to mentioned below).
* Then open a pull request and reference this issue in the pull request.

**How to build and test your changes to the website locally** <br>
You will need `Node >= 8.x` and `Yarn >= 1.5`.

```
git clone https://github.com/apache/bookkeeper.git
cd bookkeeper/site2/website
yarn install
yarn start
```

Use the [Apache Pulsar website code](https://github.com/apache/pulsar/tree/master/site2) as a north star for our development.

**Comment by Ghatage** [comment]
@Abhey @rudy2steiner @nicoloboschi and anyone who might be interested!

**Comment by Abhey** [comment]
@Ghatage I can pick this one up.

**Comment by Abhey** [comment]
@Ghatage Sorry last week I was working on a priority task at my organization and hence couldn't get much time to work on this. Will work on the issue this week and will keep you posted.
