### ISSUE TITLE
Question about EntryMemTable

### ISSUE THREAD

**Issue by Technoboy-** [apache/bookkeeper#2461]
Question 1.
It seems that no need to create SkipListArena in snapshot every time.
https://github.com/apache/bookkeeper/blob/b1e602afc93cfd6299c43f99d26c9a6b7bcd27a7/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTable.java#L184

Question 2.
From the comment, we return the checkpoint of the snapshot, but it's the newSkipList.
https://github.com/apache/bookkeeper/blob/b1e602afc93cfd6299c43f99d26c9a6b7bcd27a7/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryMemTable.java#L180
Below may be more accurate.
```
cp = this.snapshot.cp;
```

Could some help to give some ideas?

**Comment by Technoboy-** [comment]
@eolivelli

**Comment by eolivelli** [comment]
```
    // Reset allocator so we get a fresh buffer for the new EntryMemTable
                    this.allocator = new SkipListArena(conf);
```
@Technoboy-  probably if you do not create a new SkipListArena the old one would be dirty and it is more effective (better performance) to start with a brand new one.
Probably you can try to remove that line and run all of the tests and see if something breaks, then it the change is "safe" you should run some perf test that exercise that code path (I don't know how to do it, it is to be designed)

**Comment by eolivelli** [comment]
// get the checkpoint of the memtable.
                    cp = this.kvmap.cp;

probably the comment "get the checkpoint of the memtable" is to be moved a few lines above,
in this point we are simply updating the reference to the new kvmap

**Comment by eolivelli** [comment]
@Technoboy- please close this issue if I have answered to your question
