### ISSUE TITLE
BookKeeper code coverage is broken because of Jenkins migration

### ISSUE THREAD

**Issue by Ghatage** [apache/bookkeeper#2466]
**BUG REPORT**

We recently have initiated a move to the new jenkins at -> https://ci-hadoop.apache.org/job/BookKeeper/
However, the code coverage job we have at coveralls is still synced to the old jenkins at -> https://builds.apache.org/job/bookkeeper_codecoverage/

***To Reproduce***

Last run job at https://coveralls.io/github/apache/bookkeeper is from August 17 2020

cc @sijie @eolivelli @jiazhai

**Comment by eolivelli** [comment]
I am not sure anyone ever taken those reports into consideration, apart from the days when we set them up.

Btw it would be cool to resume that work.

I would find it more useful during pull requests validation, because you can easily check if the new code is covered by tests

**Comment by Ghatage** [comment]
Yes my thoughts exactly.
Code coverage driven testing has proven to reduce bugs. I've been
championing this at work and want to bring the same aspect to the community.

Code coverage per pull request commit.
Optional merge barrier based on % coverage of the commit vs a preset
threshold.

**Comment by shoothzj** [comment]
@eolivelli I think we haven't use code coverage for a long time? Can we close this issue?

**Comment by shoothzj** [comment]
closed for stale, and we haven't focus on coverage for a real long time.
