### ISSUE TITLE
Remove redundant synchronized

### ISSUE THREAD

**Issue by Technoboy-** [apache/bookkeeper#2467]
In FileInfo#setFenced
![image](https://user-images.githubusercontent.com/6297296/97542000-010f4700-1a01-11eb-9012-c1cb8cb9d206.png)
It's no need to synchronized anymore.

**Comment by codelipenghui** [comment]
@Technoboy- Are you interested in pushing a PR?

**Comment by Technoboy-** [comment]
> @Technoboy- Are you interested in pushing a PR?

#2468
