### ISSUE TITLE
Missing JavaDoc for classes

### ISSUE THREAD

**Issue by sigee** [apache/bookkeeper#247]
**JavaDoc needed**
The classes should have JavaDoc comment. There are a couple of places where it is missing. Those places are marked by @TODO: Write JavaDoc comment.

**Comment by sijie** [comment]
marked this as a blocker because we can't have such TODO in javadoc for 4.5.0

**Comment by sijie** [comment]
any volunteers?

**Comment by sijie** [comment]
picking this up for unblocking 4.5.0 release.
