### ISSUE TITLE
[Bug] The metric 'bookie_journal_JOURNAL_QUEUE_SIZE' has been growing negatively

### ISSUE THREAD

**Issue by 4onni** [apache/bookkeeper#2483]
***Describe the bug***

The metric 'bookie_journal_JOURNAL_QUEUE_SIZE' has been growing negatively.

Bookkeeper version: 4.10.0

***Screenshots***

Metrics:
![image](https://user-images.githubusercontent.com/5661665/98760318-01024480-240e-11eb-999b-620edfedbdf1.png)
Dashboard:
![image](https://user-images.githubusercontent.com/5661665/98760430-373fc400-240e-11eb-8a55-86bf4522185a.png)

**Comment by eolivelli** [comment]
IIRC we should have fixed this issue in 4.11 or in current 4.12.
Do you have a way to try ?

**Comment by Technoboy-** [comment]
Yes, please refer to #2290 .
