### ISSUE TITLE
Bug in ArrayGroupSort.java (in line 88, keySize shall be groupSize)

### ISSUE THREAD

**Issue by brianjcj** [apache/bookkeeper#2492]
**BUG REPORT**

***Describe the bug***

I am browsing the codes and just suspecting there is a bug in ArrayGroupSort.java(https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/ArrayGroupSort.java#L88)

in line 88, keySize shall be groupSize instead?

```java
    private boolean isLess(long[] array, int idx1, int idx2) {
        for (int i = 0; i < keySize; i++) {     // bug? keySize shall be groupSize instead?
            long k1 = array[idx1 + i];
            long k2 = array[idx2 + i];
            if (k1 < k2) {
                return true;
            } else if (k1 > k2) {
                return false;
            }
        }

        return false;
    }
```

***To Reproduce***

N/A

***Expected behavior***

***Screenshots***

N/A

***Additional context***

N/A

**Comment by eolivelli** [comment]
thank you @brianjcj 

can you create a test case that reproduces a problem ?
this way if there is a bug it would be easy to fix it

**Comment by brianjcj** [comment]
> thank you @brianjcj
> 
> can you create a test case that reproduces a problem ?
> this way if there is a bug it would be easy to fix it

I am very new to bookkeeper. I has never run the program yet. I were just randomly browsing the codes and found some logic problems here. so....

**Comment by brianjcj** [comment]
> thank you @brianjcj
> 
> can you create a test case that reproduces a problem ?
> this way if there is a bug it would be easy to fix it

sorry. the code is correct. my mistake!

**Comment by eolivelli** [comment]
@brianjcj  no problem
thanks for checking
