### ISSUE TITLE
circe-checksum(mvn clean package -DskipTests) in ARM64 platform error: cpuid.h: No such file or directory

### ISSUE THREAD

**Issue by zxc190615** [apache/bookkeeper#2499]
[INFO] --- nar-maven-plugin:3.5.2:nar-javah (default-nar-javah) @ circe-checksum ---
[INFO] Running /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-1.el7_9.aarch64/bin/javah compiler on 2 classes...
[INFO] + /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.272.b10-1.el7_9.aarch64/bin/javah -classpath /home/zxc/shandong/bookkeeper-master/circe-checksum/target/      classes:/root/.m2/repository/com/google/guava/guava/30.0-jre/guava-30.0-jre.jar:/root/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess      -1.0.1.jar:/root/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conf      lict-with-guava.jar:/root/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/root/.m2/repository/org/checkerframework/checker-qual/      3.5.0/checker-qual-3.5.0.jar:/root/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.2/error_prone_annotations-2.1.2.jar:/root/.m2/repos      itory/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/root/.m2/repository/io/netty/netty-buffer/4.1.50.Final/netty-buffer-4.1.50.F      inal.jar:/root/.m2/repository/io/netty/netty-common/4.1.50.Final/netty-common-4.1.50.Final.jar:/root/.m2/repository/org/projectlombok/lombok/1.18.10/lo      mbok-1.18.10.jar:/root/.m2/repository/com/github/spotbugs/spotbugs-annotations/3.1.8/spotbugs-annotations-3.1.8.jar:/root/.m2/repository/org/slf4j/slf4      j-api/1.7.25/slf4j-api-1.7.25.jar:/root/.m2/repository/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar:/root/.m2/reposi      tory/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/root/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar -d /home/z      xc/shandong/bookkeeper-master/circe-checksum/target/nar/javah-include com.scurrilous.circe.crc.Sse42Crc32C com.scurrilous.circe.checksum.NarSystem
[INFO]
[INFO] --- nar-maven-plugin:3.5.2:nar-gnu-make (default-nar-gnu-make) @ circe-checksum ---
[INFO]
[INFO] --- nar-maven-plugin:3.5.2:nar-compile (default-nar-compile) @ circe-checksum ---
[INFO] Compiling 2 native files
[WARNING] No file matching patterns ("librt.a, librt.so) for library name "rt" was found.
[INFO] 2 total files to be compiled.
[INFO] Found 128 processors available
[INFO] Limited used processors to 2
[INFO]
Starting Core 0 with 1 source files...
[INFO]
Starting Core 1 with 1 source files...
[ERROR] circe/cpp/crc32c_sse42.cpp:26:11: fatal error: cpuid.h: No such file or directory
[ERROR]    26 | # include <cpuid.h>
[ERROR]       |           ^~~~~~~~~
[ERROR] compilation terminated.
[INFO] Core 1 interrupted
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.913 s
[INFO] Finished at: 2020-11-27T09:22:56+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.5.2:nar-compile (default-nar-compile) on project circe-checksum: NAR: Compile fa      iled: g++ failed with return code 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

how to solve it? thanks

**Comment by eolivelli** [comment]
I am not sure we can do anything,
probably it would be better to break the build with some maven-enforcer rule.

it would be great to support this architecture, but we need some expert

**Comment by laystao** [comment]
> I am not sure we can do anything,
> probably it would be better to break the build with some maven-enforcer rule.
> 
> it would be great to support this architecture, but we need some expert

so.Do you have other solutions now?

**Comment by laystao** [comment]
Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.5.2:nar-validate (default-nar-validate) on project circe-checksum: NAR: One of two things may be wrong here:
[ERROR] 
[ERROR] 1. <Name> tag is missing inside the <Linker> tag of your NAR configuration
[ERROR] 
[ERROR] 2. no linker is defined in the aol.properties file for 'aarch64.MacOSX.linker'

**Comment by zengguan** [comment]
i fixed this in my M1 MacOS

step 1: I added this section to my aol.properties file

`#
# MacOSX ("Mac OS X" => MacOSX) Apple Silicon M1 (64 bits)
#
aarch64.MacOSX.linker=g++

aarch64.MacOSX.g++.cpp.compiler=g++
aarch64.MacOSX.g++.cpp.defines=Darwin GNU_GCC 
aarch64.MacOSX.g++.cpp.options=-Wall -Wno-long-long -Wpointer-arith -Wconversion
aarch64.MacOSX.g++.cpp.includes=**/*.cc **/*.cpp **/*.cxx
aarch64.MacOSX.g++.cpp.excludes=

aarch64.MacOSX.g++.c.compiler=gcc
aarch64.MacOSX.g++.c.defines=Darwin GNU_GCC 
aarch64.MacOSX.g++.c.options=-Wall -Wno-long-long -Wpointer-arith -Wconversion
aarch64.MacOSX.g++.c.includes=**/*.c
aarch64.MacOSX.g++.c.excludes=

aarch64.MacOSX.g++.fortran.compiler=gfortran
aarch64.MacOSX.g++.fortran.defines=Darwin GNU_GCC 
aarch64.MacOSX.g++.fortran.options=-Wall -fno-automatic -fno-second-underscore
aarch64.MacOSX.g++.fortran.includes=**/*.f **/*.for
aarch64.MacOSX.g++.fortran.excludes=

aarch64.MacOSX.g++.java.include=include
aarch64.MacOSX.g++.java.runtimeDirectory=IGNORED

aarch64.MacOSX.g++.lib.prefix=lib
aarch64.MacOSX.g++.shared.prefix=lib
aarch64.MacOSX.g++.static.extension=a
aarch64.MacOSX.g++.shared.extension=dylib
aarch64.MacOSX.g++.plugin.extension=bundle
aarch64.MacOSX.g++.jni.extension=jnilib
aarch64.MacOSX.g++.executable.extension=`

step 2: To use a custom aol properties file, you have to set a property like this in your pom.xml:
  <properties>
    <nar.aolProperties>${project.basedir}/bookkeeper/circe-checksum/aol.properties</nar.aolProperties>
  </properties>

and then I build success:

`[INFO] Apache BookKeeper :: Parent ........................ SUCCESS [  0.703 s]
[INFO] Apache BookKeeper :: Build Tools ................... SUCCESS [  0.323 s]
[INFO] Apache BookKeeper :: Circe Checksum Library ........ SUCCESS [  4.413 s]
[INFO] Apache BookKeeper :: Stats API ..................... SUCCESS [  1.172 s]
[INFO] Apache BookKeeper :: CPU Affinity Library .......... SUCCESS [  0.975 s]
[INFO] Apache BookKeeper :: Common ........................ SUCCESS [  1.426 s]
[INFO] Apache BookKeeper :: Common :: Allocator ........... SUCCESS [  0.362 s]
[INFO] Apache BookKeeper :: Stats :: Parent ............... SUCCESS [  0.021 s]
[INFO] Apache BookKeeper :: Stats :: Utils ................ SUCCESS [  0.230 s]
[INFO] Apache BookKeeper :: Protocols ..................... SUCCESS [  1.875 s]
[INFO] Apache BookKeeper :: Tools :: Parent ............... SUCCESS [  0.022 s]
[INFO] Apache BookKeeper :: Tools :: Framework ............ SUCCESS [  0.502 s]
[INFO] Apache BookKeeper :: Http :: Http Server ........... SUCCESS [  0.207 s]
[INFO] Apache BookKeeper :: Stats Providers :: Prometheus . SUCCESS [  0.482 s]
[INFO] Apache BookKeeper :: Bookkeeper Http :: Vertx Http Server SUCCESS [  0.461 s]
......`

**Comment by 3286360470** [comment]
> ```java
> Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.5.2:nar-validate (default-nar-validate) on project circe-checksum: NAR: One of two things may be wrong here:
> [ERROR]
> [ERROR] 1. tag is missing inside the tag of your NAR configuration
> [ERROR]
> [ERROR] 2. no linker is defined in the aol.properties file for 'aarch64.MacOSX.linker'
> ```
> 
> i fixed this in my M1 MacOS
> 
> step 1: I added this section to my aol.properties file
> 
> aol.properties:
> 
> ```java
> #
> # MacOSX ("Mac OS X" => MacOSX) Apple Silicon M1 (64 bits)
> #
> aarch64.MacOSX.linker=g++
> 
> aarch64.MacOSX.g++.cpp.compiler=g++
> aarch64.MacOSX.g++.cpp.defines=Darwin GNU_GCC 
> aarch64.MacOSX.g++.cpp.options=-Wall -Wno-long-long -Wpointer-arith -Wconversion
> aarch64.MacOSX.g++.cpp.includes=**/*.cc **/*.cpp **/*.cxx
> aarch64.MacOSX.g++.cpp.excludes=
> 
> aarch64.MacOSX.g++.c.compiler=gcc
> aarch64.MacOSX.g++.c.defines=Darwin GNU_GCC 
> aarch64.MacOSX.g++.c.options=-Wall -Wno-long-long -Wpointer-arith -Wconversion
> aarch64.MacOSX.g++.c.includes=**/*.c
> aarch64.MacOSX.g++.c.excludes=
> 
> aarch64.MacOSX.g++.fortran.compiler=gfortran
> aarch64.MacOSX.g++.fortran.defines=Darwin GNU_GCC 
> aarch64.MacOSX.g++.fortran.options=-Wall -fno-automatic -fno-second-underscore
> aarch64.MacOSX.g++.fortran.includes=**/*.f **/*.for
> aarch64.MacOSX.g++.fortran.excludes=
> 
> aarch64.MacOSX.g++.java.include=include
> aarch64.MacOSX.g++.java.runtimeDirectory=IGNORED
> 
> aarch64.MacOSX.g++.lib.prefix=lib
> aarch64.MacOSX.g++.shared.prefix=lib
> aarch64.MacOSX.g++.static.extension=a
> aarch64.MacOSX.g++.shared.extension=dylib
> aarch64.MacOSX.g++.plugin.extension=bundle
> aarch64.MacOSX.g++.jni.extension=jnilib
> aarch64.MacOSX.g++.executable.extension=
> ```
> 
> step 2: To use a custom aol properties file, you have to set a property like this in your pom.xml: <nar.aolProperties>${project.basedir}/bookkeeper/circe-checksum/aol.properties</nar.aolProperties>
> 
> and then I build success:
> 
> ```java
> [INFO] Apache BookKeeper :: Parent ........................ SUCCESS [  0.703 s]
> [INFO] Apache BookKeeper :: Build Tools ................... SUCCESS [  0.323 s]
> [INFO] Apache BookKeeper :: Circe Checksum Library ........ SUCCESS [  4.413 s]
> [INFO] Apache BookKeeper :: Stats API ..................... SUCCESS [  1.172 s]
> [INFO] Apache BookKeeper :: CPU Affinity Library .......... SUCCESS [  0.975 s]
> [INFO] Apache BookKeeper :: Common ........................ SUCCESS [  1.426 s]
> [INFO] Apache BookKeeper :: Common :: Allocator ........... SUCCESS [  0.362 s]
> [INFO] Apache BookKeeper :: Stats :: Parent ............... SUCCESS [  0.021 s]
> [INFO] Apache BookKeeper :: Stats :: Utils ................ SUCCESS [  0.230 s]
> [INFO] Apache BookKeeper :: Protocols ..................... SUCCESS [  1.875 s]
> [INFO] Apache BookKeeper :: Tools :: Parent ............... SUCCESS [  0.022 s]
> [INFO] Apache BookKeeper :: Tools :: Framework ............ SUCCESS [  0.502 s]
> [INFO] Apache BookKeeper :: Http :: Http Server ........... SUCCESS [  0.207 s]
> [INFO] Apache BookKeeper :: Stats Providers :: Prometheus . SUCCESS [  0.482 s]
> [INFO] Apache BookKeeper :: Bookkeeper Http :: Vertx Http Server SUCCESS [  0.461 s]
> ......
> ```

thanks for your solution, it's worked for me. I build bk on M1, there're to many questions.

**Comment by shoothzj** [comment]
I think it's fixed now, free feel to reopen it if there exists any problem.
