### ISSUE TITLE
Documentation Clarification for dbStorage_writeCacheMaxSizeMb Config

### ISSUE THREAD

**Issue by michaeljmarshall** [apache/bookkeeper#2500]
In the `bk_server.conf` file, the description of `dbStorage_writeCacheMaxSizeMb` says that "it should be big enough to hold a sub". Here is the exact reference:

https://github.com/apache/bookkeeper/blob/3a8f4b4d3e762ac24a0563eeaffd068efaab2b81/conf/bk_server.conf#L660-L663

I have two questions: what is a sub and how do I calculate the likely size of my sub to ensure good performance?

**Comment by sijie** [comment]
@michaeljmarshall It should be:

```
# Size of Write Cache. Memory is allocated from JVM direct memory.
# Write cache is used to buffer entries before flushing into the entry log
# For good performance, it should be big enough to hold a substantial amount
# of entries in the flush interval
#  By default it will be allocated to 1/4th of the available direct memory
```

@Jennifer88huang Can you take a look at this documentation issue?

**Comment by michaeljmarshall** [comment]
@sijie - thanks for the clarification. That certainly helps.

**Comment by Jennifer88huang** [comment]
@michaeljmarshall Thanks for raising the issue. Fixed in the docs in https://github.com/apache/pulsar/pull/8756/
