### ISSUE TITLE
Define dependency versions in root pom

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#251]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Currently some dependencies' versions are defined in root pom, some are not.
We should define all versions in root pom, so it is easier to manage the dependencies' versions.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*nice-to-have*

3. Provide any additional detail on your proposed use case for this feature.

This should be done for both dependencies and plugin-dependencies.

**Comment by eolivelli** [comment]
@sijie I was going to create a similar issue. I was waiting for 4.6

**Comment by sijie** [comment]
@eolivelli creating issue doesn't have to wait for a release. you can create an issue and leave it open to any releases. when there are contributors willing to contribute, they can take it.

I am also suggesting leaving some non-critical issues open and marked as 'help-needed', so new contributors can pick them up.
