### ISSUE TITLE
[website] The links in the doc body do not work

### ISSUE THREAD

**Issue by xuesongxs** [apache/bookkeeper#2514]
**BUG REPORT**

***Describe the bug***
![image](https://user-images.githubusercontent.com/54351417/101561101-a9043100-39ff-11eb-9f9e-bf3fd0d221b9.png)

**Comment by eolivelli** [comment]
it looks like any link on the page cannot be clicked

you can reach the release notes from the download page
http://bookkeeper.apache.org/releases/

We are working on a new website, I hope we can set it up soon
