### ISSUE TITLE
Broken link (basic concepts) under Getting started  in the readme documentation

### ISSUE THREAD

**Issue by amitvc** [apache/bookkeeper#2518]
**BUG REPORT**

***Describe the bug***
The  **basic concepts** is broken in the Getting started section in the readme on the project's github page.

***To Reproduce***
Click on **basic concepts** link on the readme 

1. Click ** basic concepts** link.
2. Takes you to https://bookkeeper.apache.org/docs/master/bookkeeperOverview.html link. This link shows Not found

***Expected behavior***
Should show the actual content and not show Not found
***Screenshots***

***Additional context***

**Comment by amitvc** [comment]
Also this link is broken - https://bookkeeper.apache.org/docs/master/bookkeeperInternals.html

**Comment by eolivelli** [comment]
@amitvc  with @Ghatage and @nicoloboschi we are working on a new website.
if you want you can join the effort, I am sure that @Ghatage  and @nicoloboschi will be happy to introduce to this important effort,
feel we to ping them on slack

**Comment by amitvc** [comment]
Sounds good @eolivelli . I will ping them on slack channel.

**Comment by michaeljmarshall** [comment]
Same as https://github.com/apache/bookkeeper/issues/2508
