### ISSUE TITLE
Some content do not display

### ISSUE THREAD

**Issue by Jennifer88huang-zz** [apache/bookkeeper#2530]
**BUG REPORT**

The following content do not display well or have "URL not found" error.

***To Reproduce***

1. Some community member could not open [this page](https://bookkeeper.apache.org/docs/master/bookkeeperStarted.html), when I open it, I found that some content is not displayed fully, see screenshot below. 
![image](https://user-images.githubusercontent.com/47805623/104266532-c4fd6580-54ca-11eb-84ba-ef5898c7534a.png)

2. Open this page https://bookkeeper.apache.org/docs/master/bookkeeperOverview.html, "Not Found" error is displayed.

![image](https://user-images.githubusercontent.com/47805623/104266676-08f06a80-54cb-11eb-9341-c16284f22903.png)

**Comment by shoothzj** [comment]
there is no root now. I think it's fixed.
