### ISSUE TITLE
Noisy stacktrace always printed at boot

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2531]
**BUG REPORT**

Here an user reported a spammy log
https://github.com/apache/pulsar/issues/9138

Basically the problem is here:
https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/DefaultBookieAddressResolver.java#L59
we are printing the stacktrace of the Exception, but we should not, it is only a problem in the log line

***Expected behavior***

No stacktrace and probably no log at level "info", but only at "debug" level

**Comment by dianacle** [comment]
I can commit a fix
