### ISSUE TITLE
ConcurrentModificationException when print LinkedList

### ISSUE THREAD

**Issue by Shoothzj** [apache/bookkeeper#2544]
**BUG REPORT**

***Describe the bug***

![image](https://user-images.githubusercontent.com/12933197/104894609-e0c3a880-59af-11eb-963e-2245f234507c.png)

***To Reproduce***
![image](https://user-images.githubusercontent.com/12933197/104894485-be318f80-59af-11eb-8b7e-14a7e4a196af.png)

### What should we do ?
Do not print the linkedList
or
use read write lock to protect the list

By the way, will it cause ledger clean up failed ? My test environment got disk full, and I found this log

**Comment by WJL3333** [comment]
LinkedList is not thread safe. Any Bookie error log or some other information? @Shoothzj

**Comment by Shoothzj** [comment]
> LinkedList is not thread safe. Any Bookie error log or some other information? @Shoothzj

Currently I have not log according to it. Maybe concurrently open the ledger  and flush?

**Comment by eolivelli** [comment]
that variable should be a CopyOnWriteArrayList and not a simple LinkedList

see here:
https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForEntryLogPerLedger.java#L277

probably this issue is a result of a refactor

**Comment by Shoothzj** [comment]
> that variable should be a CopyOnWriteArrayList and not a simple LinkedList
> 
> see here:
> https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForEntryLogPerLedger.java#L277
> 
> probably this issue is a result of a refactor
> 
> otherwise we should take care of synchronization in all of the accesses to the variable.
> given the hierarchy of classes I suggest to change the type to CopyOnWriteArrayList here
> https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogManagerForSingleEntryLog.java#L53

Apparently, change it to CopyOnWriteArrayList can fix this problem.
But may be there is another solution, see these code:
![image](https://user-images.githubusercontent.com/12933197/104929911-7b87ab80-59df-11eb-97a6-5cb8e351c722.png)
![image](https://user-images.githubusercontent.com/12933197/104929985-8e01e500-59df-11eb-8054-afd29aeca086.png)

May be we should add synchronize on method **commitEntryMemTableFlush** and **prepareSortedLedgerStorageCheckpoint** in class EntryLogManagerForSingleEntryLog.
These code are committed in year 2018. I don't think it's a refactor probleam

**Comment by eolivelli** [comment]
probably add those new synchronization points may cause additional issues

**Comment by Shoothzj** [comment]
> probably add those new synchronization points may cause additional issues

The two children class of EntryLogManagerBase use different trick of sync.
One **EntryLogManagerForEntryLogPerLedger** use CopyOnWriteArrayList,
Another class EntryLogManagerForSingleEntryLog use volatile for replace reference, and synchronize for add

If we change **EntryLogManagerForSingleEntryLog** to CopyOnWriteArrayList, the other synchronize block like 
![image](https://user-images.githubusercontent.com/12933197/104933198-94925b80-59e3-11eb-9954-571fa5f8963f.png)
seems useless, can be replace as 
```java
rotatedLogChannels.clear();
```

**Comment by Shoothzj** [comment]
> probably add those new synchronization points may cause additional issues

This annotation may prove that add sync is right, how about put sync on this method
![image](https://user-images.githubusercontent.com/12933197/104974427-f201c900-5a32-11eb-9ffd-7e572128e919.png)

**Comment by Shoothzj** [comment]
> probably add those new synchronization points may cause additional issues

Refer to the addEntry method,
**EntryLogManagerForEntryLogPerLedger** locks per ledger
**EntryLogManagerForSingleEntryLog** locks itself

How about make the synchronization points only on call of **createNewLog** in class EntryLogManagerForSingleEntryLog.
Why **createNewLog** can't treat equality?
