### ISSUE TITLE
Out of direct memory. Bookkeeper's log only 50MB, but being consider as over 1G by bookie.

### ISSUE THREAD

**Issue by Shoothzj** [apache/bookkeeper#2584]
**BUG REPORT**
In my environment, has one log. The gc can't handle this log.
The extractEntryLogMetadataFromIndex method first throw an exception,
which is "Cannot deserialize ledgers map from entryId",
And then the scanEntryLog method disjudge the packet size.

***To Reproduce***
Currently, I don't know what reason.

***Screenshots***

![image](https://user-images.githubusercontent.com/12933197/107165943-81c1e400-69ef-11eb-8cbb-328ff342be27.png)

***Additional context***

bookkeeper verson 4.12.1
pulsar version 2.7.0
[ec49.zip](https://github.com/apache/bookkeeper/files/5940865/ec49.zip)

**Comment by Shoothzj** [comment]
I hava uploaded the probleam log. Sorry for forgeting.

**Comment by jiazhai** [comment]
Discussed with @Shoothzj. It happened after force shutdown the Bookie, and the log file not flushed entirely.  then when the bookie restarted, the log file could not be recovered.
