### ISSUE TITLE
How does ledger open with recovery works internal ?

### ISSUE THREAD

**Issue by WJL3333** [apache/bookkeeper#2585]
when ledger open with recovery. which data range will be recovery?

all entry data before LAC in the ensemble? 

or 

all the data available in the ensemble include those not reach Qa but already write in some bookie?

need some material on the consistent protocol.

**Comment by Vanlightly** [comment]
You can find the protocol described concisely in a TLA+ specification here: https://github.com/Vanlightly/bookkeeper-tlaplus/blob/main/BookKeeperProtocol.tla

To answer your specific question, ledger recovery focuses on the last ensemble of the ledger. It starts at the highest known LAC of the ensemble of bookies and stops when it reaches the last unrecoverable entry. Unrecoverable means that no Ack Quorum of bookies have the entry. All entries up to that point get rewritten back to the ledger, and recovery completes when those entries have been committed (reached AQ).

**Comment by WJL3333** [comment]
thanks for explain : - ) TLA+ is a good material to understand bookkeeper !
