### ISSUE TITLE
Licenses check finds multiple problems

### ISSUE THREAD

**Issue by dlg99** [apache/bookkeeper#2592]
**BUG REPORT**

***Describe the bug***

Licenses check finds multiple problems.

***To Reproduce***

```
$ mvn clean package -DskipTests

$ dev/check-binary-license bookkeeper-dist/server/target/bookkeeper-server-4.13.0-SNAPSHOT-bin.tar.gz

$ dev/check-binary-license bookkeeper-dist/all/target/bookkeeper-all-4.13.0-SNAPSHOT-bin.tar.gz

$ dev/check-binary-license bookkeeper-dist/bkctl/target/bkctl-4.13.0-SNAPSHOT-bin.tar.gz
```

get bunch of problems listed by every run of the `dev/check-binary-license`

***Expected behavior***

Licenses up-to-date.

***Additional context***

http://bookkeeper.apache.org/community/licensing/
https://github.com/apache/bookkeeper/pull/2582#issuecomment-775578408

**Comment by eolivelli** [comment]
It is a blocker for 4.13.0 release

**Comment by dianacle** [comment]
I can try to pick up this issue

**Comment by eolivelli** [comment]
sure, thank you @dianacle  !
