### ISSUE TITLE
Docker image: provide a way to pass any desired configuration property via ENV vars

### ISSUE THREAD

**Issue by caiok** [apache/bookkeeper#260]
In the first docker image PR (#197) emerged that could be useful to have a way to pass any desired configuration property at docker container creation.

@merlimat Proposed to use [this python script](https://github.com/apache/incubator-pulsar/blob/master/docker/scripts/apply-config-from-env.py), but it currently lacks the ability to substitute commented out properties. This could lead to undesired and difficult to debug issues for the end user.

This issue requires to import and enhance the script (and maybe to create a PR on the original repo) and update docker build files accordingly.

**Comment by jiazhai** [comment]
Based on Pulsar's script, I have already done a change satisfy our need, once PR 197 merged, I could do the PR.

**Comment by caiok** [comment]
It's awesome, thanks @jiazhai

**Comment by jiazhai** [comment]
fixed in #342
