### ISSUE TITLE
How to upgrade Bookkeeper to use TLS with Zookeepers?

### ISSUE THREAD

**Issue by ShPrajpati** [apache/bookkeeper#2606]
I run a bookkeeper cluster that is back-end for pulsar. I am specifically using **mTLS** here and want to upgrade the **Bookkeepers** to use the **TLS** with **Zookeepers**.
Please advice what all configuration changes would bee needed in order to achieve that.

**Comment by shoothzj** [comment]
Thanks for @zyj5340 reply, feel free to reopen if you still have questions.
