### ISSUE TITLE
Docker image: create a tutorial dice application docker build

### ISSUE THREAD

**Issue by caiok** [apache/bookkeeper#261]
Like emerged in #197, it's could be useful to have the tutorial code under bookkeeper official repo and to have the docker build of the tutorial application in the repo too.

These are the steps:
- Bring in [Ivan Kelly tutorial code](https://github.com/ivankelly/bookkeeper-tutorial). I created this updated and working fork for this tutorial: https://github.com/caiok/bookkeeper-tutorial.
- Set up a docker build (the one in the forked repo is a good starting point)
- Publish an automated build on docker hub
- Change the current docker image example to use this new image

**Comment by sijie** [comment]
Closed this issue, since it is lacking activities and there is no need for a docker image for a tutorial. or if we do need a docker image, it doesn't have to be an apache released docker.
