### ISSUE TITLE
Useless option "explicitLacInterval" is set to 1 in default bk_server.conf file

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#262]
The default bk_server.conf reports

```
# Interval between sending an explicit LAC in seconds
explicitLacInterval = 1
```

This option is only useful on the client side, it should be removed from this file

**Comment by eolivelli** [comment]
@sijie  @zhaijack should be include this in 4.5 ?

**Comment by sijie** [comment]
yes we should include this in 4.5. can you help with that?

**Comment by eolivelli** [comment]
I will send a PR
