### ISSUE TITLE
Rocksdb logs configurable write location. 

### ISSUE THREAD

**Issue by klwilson227** [apache/bookkeeper#2620]
**FEATURE REQUEST**

1. The rocksdb appears to write LOG files to ../data/bookkeeper/ledgers/current/ledgers/LOG and data/bookkeeper/ledgers/current/locations/LOG These log files roll and multiple of the LOG.XXX files can be seen on the disk after a few days. We would like to have the ability to write these logs to a different disk and keep the fast disk space allocated for the data in motion. 

2. we see this as  must-have solution to optimize the disks usages appropriately. If we are asking customers to purchase special fast disks for holding the in process data, then this should be the only usage of the drives. Logging based entries should be writing to a separate disk optimized for writing log files. 

3. Provide any additional detail on your proposed use case for this feature.

It appears that there exists a environment variable already to control the LOG level of the ROCKS db. We are looking for similar controls for the location or directory being written.

**Comment by dinghram** [comment]
Fixed in PR https://github.com/apache/bookkeeper/pull/2698

**Comment by merlimat** [comment]
#2698 was merged
