### ISSUE TITLE
Can we upgrade SortedLedgerStorage to DbLedgerStorage in production environment

### ISSUE THREAD

**Issue by Shoothzj** [apache/bookkeeper#2634]
Can we upgrade SortedLedgerStorage to DbLedgerStorage in production environment ?
Is there any problem?

**Comment by codelipenghui** [comment]
I think you need to decommission the bookie first and then cleanup the bookie, change to DbLedgerStorage and then add it back to the cluster, seems we can change the LedgerStorage directly.

**Comment by eolivelli** [comment]
There are command line tools to perform the upgrade.

Check this command
bin/bookkeeper shell

**Comment by codelipenghui** [comment]
Oh, cool. Got it, bin/bookkeeper shell convert-to-db-storage.

**Comment by Shoothzj** [comment]
Cool. Thanks
