### ISSUE TITLE
Run bookies locally

### ISSUE THREAD

**Issue by tieke1121** [apache/bookkeeper#2702]
ronganxia@C02FGF1HMD6M bookkeeper-4.11.1 % pwd
/Users/ronganxia/soft/bookkeeper/bookie1/bookkeeper-4.11.1
ronganxia@C02FGF1HMD6M bookkeeper-4.11.1 % bin/bookkeeper localbookie 10
Couldn't find module '(org.apache.bookkeeper-)?bookkeeper-server' jar.
Do you want me to run `mvn package -DskipTests` for you ? (y|n) y
see output at /Users/ronganxia/soft/bookkeeper/bookie1/bookkeeper-4.11.1/logs/build.out for the progress ...
the classpath of module 'bookkeeper-server' is not found, generating it ...
see output at /Users/ronganxia/soft/bookkeeper/bookie1/bookkeeper-4.11.1/bookkeeper-server/target/build_classpath.out for the progress ...
the classpath of module 'bookkeeper-server' is generated at '/Users/ronganxia/soft/bookkeeper/bookie1/bookkeeper-4.11.1/bookkeeper-server/target/cached_classpath.txt'.
Error: Could not find or load main class org.apache.bookkeeper.util.LocalBookKeepe

**Comment by tieke1121** [comment]
run bookies locally error

**Comment by Sunny-Island** [comment]
Try to check ` bookkeeper-4.11.1/bookkeeper-server/target/build_classpath.out` file, if it shows you can't find `Could not resolve dependencies for project`, you may need to change `settings.xml` file for maven. After that, run `mvn clean install -U
`
