### ISSUE TITLE
Bookkeeper doesn't create a log file

### ISSUE THREAD

**Issue by stanbog** [apache/bookkeeper#2704]
Hello,

We have a bookkeeper cluster made from 3 nodes.
We would like to forward the logs into splunk but the bookkeeper service doesn't generate any logs files other than journalctl.

Those are the log properties that we currently have:

```
BOOKIE_LOG_DIR=${BOOKIE_LOG_DIR:-"$BK_HOME/logs"}
BOOKIE_LOG_FILE=${BOOKIE_LOG_FILE:-"bookkeeper-server.log"}
BOOKIE_ROOT_LOGGER=${BOOKIE_ROOT_LOGGER:-"INFO,CONSOLE"}
```

I would expect to find the log `bookkeeper-server.log` under `$BK_HOME/logs` but that doesn't exist.

Any help would be appreciated.

Thank you.

**Comment by Ghatage** [comment]
That's very weird.
Can you check if you have the proper permissions on the log directory for the process?

**Comment by stanbog** [comment]
Hello,

Thank you for your answer.

Yes, the permissions seem to be correct.

This is what I have in the `$BK_HOME`:

```
[root@svevertpulsar01 bookkeeper]# ls -lart
total 84
drwxr-xr-x 6 root       root          73 Apr 23  2020 ..
drwxr-xr-x 2 bookkeeper bookkeeper     6 Dec 18 10:14 deps
drwxr-xr-x 2 bookkeeper bookkeeper   214 Feb 23 16:37 bin
drwxr-xr-x 2 bookkeeper bookkeeper   266 Feb 23 16:37 conf
drwxr-xr-x 2 bookkeeper bookkeeper  8192 Feb 23 16:37 lib
drwxr-xr-x 7 bookkeeper bookkeeper    64 May 25 13:05 .
drwxr-xr-x 2 bookkeeper bookkeeper 49152 May 25 13:05 logs
```

Under `logs` directory I have a bunch of `gc_xxxxxx.log` files , but no `bookkeeper-server.log`

```
[root@svevertpulsar01 logs]# ls -lart
total 22800
-rw-r--r-- 1 bookkeeper bookkeeper      869 Feb 23 16:37 gc_9020.log
-rw-r--r-- 1 bookkeeper bookkeeper      869 Feb 23 16:38 gc_9786.log
-rw-r--r-- 1 bookkeeper bookkeeper      869 Feb 23 16:53 gc_12662.log
-rw-r--r-- 1 bookkeeper bookkeeper      869 Feb 23 17:08 gc_15730.log
-rw-r--r-- 1 bookkeeper bookkeeper      864 Feb 23 17:23 gc_18820.log
-rw-r--r-- 1 bookkeeper bookkeeper      864 Feb 23 17:38 gc_21934.log
```

**Comment by stanbog** [comment]
This was fixed with the following adjustments:
Copy `/opt/bookkeeper/conf/log4j2.xml` in `/etc/bookkeeper`
Remove the original `log4j.properties`
Change in `/etc/sysconfig/bookkeeper`:
`BOOKIE_LOG_CONF=/etc/bookkeeper/log4j.properties`
`BOOKIE_ROOT_LOGGER="CONSOLE,ROLLINGFILE`
To:
`BOOKIE_LOG_CONF=/etc/bookkeeper/log4j2.xml`
`BOOKIE_ROOT_LOG_APPENDER="ROLLINGFILE"`
