### ISSUE TITLE
lost last entry?

### ISSUE THREAD

**Issue by greatle** [apache/bookkeeper#2709]
**QUESTION**
In test class：
https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/test/java/org/apache/bookkeeper/client/TestReadLastConfirmedAndEntry.java
testAdvancedLacWithEmptyResponse（）
![image](https://user-images.githubusercontent.com/17866905/117382472-3006f800-af11-11eb-9281-3f6c1f6fc098.png)
A total of  "expectedEntryIdToFail + 1" entries are written here, but only "expectedEntryIdToFail"  entries are read 
Where is the last entry and how to get it？

**Comment by greatle** [comment]
In a real bookkeeper cluster, the same is . If writer is close, the last entry can be read. Otherwise, the last entry can't be read all the time, no matter how long wait or call the "force()" method of writer. In actual production environment, it is possible to write N entries in a period of time, but only N -1 entries can be read immediately. The N-th entry can be read only when it is written to other data next time or close writes. This should be a bug?

**Comment by ArvinDevel** [comment]
This is not a bug. Original BK protocol only piggyback LAC when appending new entry, so when you write the last entry, the writer can only piggyback (lastEntryId - 1) as LAC to the server. The newest  BK protocol support write LAC intermittently by setting  `explicitLacInterval` parameter.
