### ISSUE TITLE
Sometimes bin/bookkeeper localbookie does not work from source code

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2725]
When you run the command `bin/bookkeeper localbookie 1` from the source code it may happen that it does not work and finished with
`Error: Could not find or load main class org.apache.bookkeeper.util.LocalBookKeeper`

This is because the `find_module_jar` function finds these files as main BK server jar:
```
/PATH-TO-CODE/bookkeeper-server/target/bookkeeper-server-4.14.1-javadoc.jar
/PATH-TO-CODE/bookkeeper-server/target/bookkeeper-server-4.14.1-sources.jar
/PATH-TO-CODE/bookkeeper-server/target/bookkeeper-server-4.14.1-tests.jar
```

***To Reproduce***

Run 
```
mvn clean install -DskipTests
bin/bookkeeper localbookie 1
```

***Suggested fix***
Enhance `find_module_jar` in order to skip additional artifacts or use some mvn plugin to get the path of the jar file

**Comment by shoothzj** [comment]
Now we have switched to `REGEX="^${MODULE}-[0-9\\.]*((-[a-zA-Z]*(-[0-9]*)?)|(-SNAPSHOT))?.jar$"`
