### ISSUE TITLE
Run failed with JAVA_HOME env containing space(s)

### ISSUE THREAD

**Issue by 10fish** [apache/bookkeeper#2726]
**BUG REPORT**

***Describe the bug***

ran locally with `$ ./bin/bookkeeper localbookie 10` on my mac, failed.

***To Reproduce***

1. run `mvn clean install` with a success.
2. run `./bin/bookkeeper localbookie 10` just under the root of the project 

***Expected behavior***

output looks like:
```text
$ ./bin/bookkeeper localbookie 10                                        
./bin/bookkeeper: line 166: /Library/Internet: No such file or directory

```

***Additional context***

after printing variables before the line where error occurs, I find out JAVA_HOME variable on my mac as following:

```text
$ echo $JAVA_HOME
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

```

**Comment by Sunny-Island** [comment]
I have reproduced this error.
It seems caused by the space in `JAVA_HOME`.
Try to install new java in MacOS and change `JAVA_HOME` path.

**Comment by Sunny-Island** [comment]
I think adding double quotation can also works.
open bin/bookkeeper in vim or other editor, change 166 line:
`  exec ${JAVA} ${OPTS} ${JMX_ARGS} -Dzookeeper.4lw.commands.whitelist='*' org.apache.bookkeeper.util.LocalBookKeeper ${NUMBER} ${BOOKIE_CONF} $@`
to
`  exec "${JAVA}" ${OPTS} ${JMX_ARGS} -Dzookeeper.4lw.commands.whitelist='*' org.apache.bookkeeper.util.LocalBookKeeper ${NUMBER} ${BOOKIE_CONF} $@`

just add double quotation around `${JAVA}`

**Comment by 10fish** [comment]
Yeah, I just did that, and it worked. I just wonder whether there should be a fix.

**Comment by Sunny-Island** [comment]
[#2727](https://github.com/apache/bookkeeper/pull/2727)
