### ISSUE TITLE
[Security] org.inferred:freebuilder:1.14.9 dependency causes Bookkeeper to be flagged for jQuery vulnerabilities

### ISSUE THREAD

**Issue by lhotari** [apache/bookkeeper#2732]
**BUG REPORT**

The org.inferred:freebuilder:1.14.9 dependency causes Bookkeeper to be flagged for jQuery vulnerabilities.
This happens in the Sonatype IQ vulnerability scanner which will also scan embedded js files. For example, it finds jQuery at the path `org/inferred/freebuilder/shaded/org/openjdk/tools/javadoc/internal/doclets/formats/html/resources/jquery/external/jquery
jquery-1.10.2.js` inside the freebuilder jar file.

***Expected behavior***

Bookkeeper shouldn't expose freebuilder as a dependency at all. It's an annotation processor which should be [defined as optional dependency in maven](https://github.com/inferred/FreeBuilder#maven) and [with `compileOnly` in gradle](https://github.com/inferred/FreeBuilder#gradle).

**Comment by eolivelli** [comment]
BookKEeper does not have a Web UI
this is a false positive

btw I agree that we can mark it as "optional" or exclude it at all
