### ISSUE TITLE
bookies hosts by metrics grow exponentially.

### ISSUE THREAD

**Issue by thinker0** [apache/bookkeeper#2736]
**BUG REPORT**
There are many, many, many Prometheus Metrics names.

***Describe the bug***
```
^(bookkeeper_client_per_channel_bookie_client|bookkeeper_server_BookieHighPriorityThread|replication_bookkeeper_client_per_channel_bookie_client)_hostnames_port_.*
```

bookies hosts by metrics grow exponentially.

***To Reproduce***

***Expected behavior***
Prometheus OOM (200Gbyte)

***Screenshots***
![image](https://user-images.githubusercontent.com/357785/121538948-2ad12780-ca40-11eb-92e4-4041b5efe785.png)
![image](https://user-images.githubusercontent.com/357785/121539143-5e13b680-ca40-11eb-9883-fdf8874853e5.png)

***Additional context***

**Comment by eolivelli** [comment]
which version of BK are you using ?
how many bookies ?
do bookies have a dynamic address ?

**Comment by thinker0** [comment]
- pulsar-2.7.2
- 120ea bookies
- yes (apache mesos/aurora)

**Comment by thinker0** [comment]
Can change this ?
https://github.com/apache/incubator-heron/pull/3493

**Comment by sursingh** [comment]
I think this has already been addressed: https://github.com/apache/bookkeeper/blame/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/PerChannelBookieClient.java#L407

4.14.1 release should have this change

**Comment by thinker0** [comment]
@sursingh Is it compatible with Pulsar 2.7.2 version?

**Comment by sursingh** [comment]
2.7.2 is using bookkeeper 4.12.x so doesn't have this change. You may need to backport this to 4.12.x bookkeeper.

**Comment by thinker0** [comment]
https://github.com/apache/bookkeeper/releases/tag/release-4.14.1

Nothing binary ?

**Comment by sursingh** [comment]
Binary jars can be downloaded from maven. https://mvnrepository.com/artifact/org.apache.bookkeeper/bookkeeper-server

**Comment by sijie** [comment]
@thinker0 Can you create an issue in Pulsar? We can upgrade the bookkeeper version for Pulsar 2.7.3 release.
