### ISSUE TITLE
Bookkeeper image 4.14.1 not available in DockerHub

### ISSUE THREAD

**Issue by RaulGracia** [apache/bookkeeper#2737]
**BUG REPORT**

***Describe the bug***

Bookkeeper 4.14.1 is not available in DockerHub for download: https://hub.docker.com/r/apache/bookkeeper/tags?page=1&ordering=last_updated

***To Reproduce***

See https://hub.docker.com/r/apache/bookkeeper/tags?page=1&ordering=last_updated 

***Expected behavior***

n/a

***Screenshots***

n/a

***Additional context***

n/a

**Comment by eolivelli** [comment]
@dlg99 you succeeded to have the docker image 4.14.0 published.
it should be similar to 4.14.11.
do you have any idea ?

@merlimat you were the release manager for 4.14.1, did you notice something strange during the execution of the procedure ?

more context:
docker images are built by a ASF infra bot, that scans the tags and then builds the docker image for dockerhub using this script
https://github.com/apache/bookkeeper/blob/master/docker/hooks/build

**Comment by eolivelli** [comment]
I am trying with

```
cd docker
DOCKER_TAG=4.14.1 IMAGE_NAME=eolivelli/bk4141 hooks/build
```

**Comment by eolivelli** [comment]
and I am able to build the image correctly

**Comment by AndreyKoltsov1997** [comment]
I've noticed that `BK_VERSION` variable within [Dockerfile](https://github.com/apache/bookkeeper/blob/master/docker/Dockerfile) hadn't been changed since 4.12.1.
Could it cause an issue within any of CI / automated Docker image build processes?

**Comment by eolivelli** [comment]
I started a conversation on the Slack channel of the ASF Infra
https://the-asf.slack.com/archives/CBX4TSBQ8/p1623408711319700

**Comment by eolivelli** [comment]
> I've noticed that `BK_VERSION` variable within [Dockerfile](https://github.com/apache/bookkeeper/blob/master/docker/Dockerfile) hadn't been changed since 4.12.1.
> Could it cause an issue within any of CI / automated Docker image build processes?

This is something we should update at every release.
That variable drives the 'latest' tag.
you can see how the script works https://github.com/apache/bookkeeper/blob/master/docker/hooks/build 

do you mind sending a PR for the update ? @AndreyKoltsov1997

**Comment by eolivelli** [comment]
JIRA ticket 
https://issues.apache.org/jira/browse/INFRA-21985

**Comment by eolivelli** [comment]
docker image is ready
https://hub.docker.com/layers/apache/bookkeeper/4.14.1/images/sha256-633216094f61036eb92333b9f602571f32c7d91d276a59659c0f792c5d7b2a3f?context=repo

@RaulGracia thank you for sharing your findings
