### ISSUE TITLE
BK_VERSION variable doesn't match release version in some branches.

### ISSUE THREAD

**Issue by AndreyKoltsov1997** [apache/bookkeeper#2738]
**BUG REPORT**

***Describe the bug***

BK_VERSION environment variable hadn't been updated within Dockerfiles on some of the branches.
On `branch-*` branches, the last update had been made for `4.12.1`, on `release-*` branches - `4.9.0`.

***To Reproduce***

****See Dockerfile for the following branches:****
* [4.13](https://github.com/apache/bookkeeper/blob/branch-4.13/docker/Dockerfile) - `BK_VERSION=4.12.1`
* [4.14](https://github.com/apache/bookkeeper/blob/branch-4.14/docker/Dockerfile) - `BK_VERSION=4.12.1`
* [Release 4.10.0](https://github.com/apache/bookkeeper/blob/release-4.10.0/docker/Dockerfile) - `ARG BK_VERSION=4.9.0`
* [Release 4.11.0](https://github.com/apache/bookkeeper/blob/release-4.11.0/docker/Dockerfile) - `ARG BK_VERSION=4.9.0`
* [Release 4.14.0](https://github.com/apache/bookkeeper/blob/release-4.14.0/docker/Dockerfile) - `BK_VERSION=4.12.1`
* [Release 4.14.1](https://github.com/apache/bookkeeper/blob/release-4.14.1/docker/Dockerfile) - `BK_VERSION=4.12.1`

***Expected behavior***

I except the `BK_VERSION` variable to match target BookKeeper release. Otherwise, while building Docker image of a particular release, the incorrect version could be misleading for the user.

***Screenshots***

The links to Dockerfiles and their associated `BK_VERSION` variables have been attached above.

***Additional context***

N/A

**Comment by AndreyKoltsov1997** [comment]
Hi, @eolivelli!
Currently, I'm thinking about sending multiple PRs to all of the branches listed within the issue. 
Would it make sense to send a PRs to all of the branches or we should rather focus on a particular ones?

**Comment by shoothzj** [comment]
@AndreyKoltsov1997 Andrey, sorry for my late reply, you can go ahead. branch version beyond 4.14 is more important because they are actively maintaining.

**Comment by shoothzj** [comment]
I revisisted this issue, it's not a problem `BK_VERSION` mismatch, but it can be a little confused. In code, `BK_VERSION` reflects current latest release version.

During release, it will be overrided by git tag. See

https://github.com/apache/bookkeeper/blob/ca9a455ef1e164c2b49cc335d0fd99dec1868b82/docker/hooks/build#L1-L9

I would close this issue, feel free to reopen it if you still have other problems.
