### ISSUE TITLE
Why lac is always less than entryId?

### ISSUE THREAD

**Issue by HashZhang** [apache/bookkeeper#2748]
Why lac is always less than entryId? If the ledger is not closed and currently no more entries are produced, the last one will not be read forever unless there is a new entry or ledger is closed?

**Comment by eolivelli** [comment]
the LAC is piggybacked by default during writes

but you can configure `explicitLacInterval` and the BK client will send in background updates about the LAC even without any writes.

https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java#L128

**Comment by HashZhang** [comment]
I see, Generally LACs are piggy-backed on writes
