### ISSUE TITLE
TestPerChannelBookieClient.testEpollChannelTcpUserTimeout fails

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#2787]
**BUG REPORT**
After we committed https://github.com/apache/bookkeeper/commit/c8d4086697f85c9093f4da2c907a13e17c198914 I see this test failing very often on DataStax CI, that run the tests against current BookKeeper master, on JDK8.

***Describe the bug***
This is the error

[ERROR] Failures: 
[ERROR] org.apache.bookkeeper.proto.TestPerChannelBookieClient.testEpollChannelTcpUserTimeout
[ERROR]   Run 1: TestPerChannelBookieClient.testEpollChannelTcpUserTimeout:337 expected:<1236> but was:<1234>
[ERROR]   Run 2: TestPerChannelBookieClient.testEpollChannelTcpUserTimeout:337 expected:<1236> but was:<1234>
[ERROR]   Run 3: TestPerChannelBookieClient.testEpollChannelTcpUserTimeout:337 expected:<1236> but was:<1234>

This is the line
https://github.com/apache/bookkeeper/commit/c8d4086697f85c9093f4da2c907a13e17c198914#diff-271106bdb4f954bd92d6de6e38f2e9dfa542754e611001050350a72bd7a0b9acR338

**Comment by eolivelli** [comment]
@RaulGracia can you please take a look ?
is it possible that Netty adapts the value ?

**Comment by eolivelli** [comment]
for reference:
[ApacheBookKeeper] $ mvn -s /tmp/settings10138559118398016608.xml -v
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_292, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-64-generic", arch: "amd64", family: "unix"

**Comment by RaulGracia** [comment]
@eolivelli sure, will allocate some time soon to fix this flaky test.

**Comment by eolivelli** [comment]
@RaulGracia did you have time to take a look ?

**Comment by RaulGracia** [comment]
@eolivelli not yet, my plan is to address this one after the release of Pravega 0.10 (going on right now).
