### ISSUE TITLE
How to add a new disk to an exists bookie node?

### ISSUE THREAD

**Issue by TimXu0713** [apache/bookkeeper#2789]
**QUESTION**

The remaining disk space of my bookkeeper cluster is running out. How can I expand the storage capacity by increasing the existing node disks instead of increasing the number of nodes? Because I don't have more machines. Is there any guid docment?

**Comment by fantapsody** [comment]
The command [`bin/bookkeeper shell expandstorage`](https://bookkeeper.apache.org/docs/latest/reference/cli/#bookkeeper-shell-expandstorage) may help you. It has a REST API as well.
