### ISSUE TITLE
Record metadata store version somewhere

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#282]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Address the TODO item in MSLedgerManagerFactory

        // load metadata store
        String msName = conf.getMetastoreImplClass();
        try {
            metastore = MetastoreFactory.createMetaStore(msName);

            // TODO: should record version in somewhere. e.g. ZooKeeper
            int msVersion = metastore.getVersion();
            metastore.init(conf, msVersion);
        } catch (Throwable t) {
            throw new IOException("Failed to initialize metastore " + msName + " : ", t);
        }

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**nice-to-have**

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by sijie** [comment]
removed the milestone, can revisit in 4.7

**Comment by ivankelly** [comment]
@sijie Can we close this since we're planning to deprecate metadata store anyhow?

**Comment by sijie** [comment]
close the issue as "won't fix", since metadata store api is not used and will be replaced with metadata service api.
