### ISSUE TITLE
Why KeyValueStorageRocksDB set the table format version as 2 explicitly?

### ISSUE THREAD

**Issue by Myasuka** [apache/bookkeeper#2823]
**QUESTION**

`KeyValueStorageRocksDB` sets the table format version as 2 explicitly:
`tableOptions.setFormatVersion(2);`

From my experience, newly format could suppory partitioned index&filter, which could help improve performance much better with limited block cache, and the newer version sould be compatiable with older version. Why bookkeeper must set the version as 2?

**Comment by dlg99** [comment]
@merlimat @sijie do you have any context for this?
