### ISSUE TITLE
V2 ReadEntryProcessor should handle asynchronous fence like what V3 does

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#283]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Address TODO item in *ReadEntryProcessor*:

                // TODO:
                // currently we don't have readCallback to run in separated read
                // threads. after BOOKKEEPER-429 is complete, we could improve
                // following code to make it not wait here
                //
                // For now, since we only try to wait after read entry. so writing
                // to journal and read entry are executed in different thread
                // it would be fine.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*nice-to-have*

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by ivankelly** [comment]
In general ReadEntryProcessor#processPacket needs a bit of a refactor to use java 8 features. This change should be pretty straightforward though.

**Comment by liketic** [comment]
Hi @sijie , I opened #2021 , could you please take a look?
