### ISSUE TITLE
Any suggestions for optimizing rocksdb parameters in huge throughput scenarios?

### ISSUE THREAD

**Issue by wuzhanpeng** [apache/bookkeeper#2878]
**QUESTION**

In our usage scenario, in the case of high-throughput writes, we found that the cpu utilization of rokskdb:low:XX thread can easily reach 100%. Are there any good suggestions for optimizing the rocksdb parameters in this situation?

As you can see from the screenshot:
![image](https://user-images.githubusercontent.com/14341827/140466861-65049771-71df-459b-9753-aba865c079d1.png)

We have tried turning off the compression, but nothing seems to have changed.
```
dbStorage_rocksDB_lz4CompressionEnabled=false
```

Any suggestions would be greatly appreciated~

**Comment by wuzhanpeng** [comment]
@merlimat @eolivelli @dlg99 Would you mind to take a look?

**Comment by dlg99** [comment]
@wuzhanpeng I suggest starting with profiling.

JFR (java flight recorder) is packaged with the JDK. It is an easy to use profiler (cpu/memory/GC).
In case you haven't used it:

```jcmd <PID_HERE> JFR.start duration=60s settings=profile filename=flight.jfr```

This will collect the profile into the file. If the systems is too busy the profile can get quite large (but it compresses well), you can try to decrease duration.
In some cases longer durations help.

this should work on java 11
pre-java11 requires
`jcmd <PID_HERE> VM.unlock_commercial_features`
before running jfr

to find the pid: run `jcmd`

the jfr file can be opened with jmc (UI app)  https://github.com/openjdk/jmc#downloading-builds or https://www.oracle.com/java/technologies/javase/products-jmc8-downloads.html (used to be included in the jdk)
