### ISSUE TITLE
Docker image: provide a template related way to handle different version

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#288]
In the first docker image PR (#197), there is a suggestion to use template and generate Docker images based on different image base, such as centos, alpine, ubuntu, etc.

**Comment by caiok** [comment]
Simple placeholders substitution is not enough for having a common template for centos and alpine. We need something that could conditionally put pieces of code. The simplest idea that comes to my mind is to use C preprocessor and instruct makefile for "compile" target platform-version dirs.

**Comment by caiok** [comment]
@jiazhai Should this issue be dropped after the community meeting decisions or it's still needed?
