### ISSUE TITLE
Docker image: make docker image build based on master latest code 

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#289]
In the first docker image PR (#197), there is a suggestion to make docker image build based on master's latest code

**Comment by caiok** [comment]
@jiazhai This issue is meant to creating an additional build or replace the existing one? I tend for the former.

**Comment by jiazhai** [comment]
They should be in the same CI process. But let's delay this work. 
As discussed in the meeting- "dockerfile is to download official bk release image", From my view,  the first version will use the official 4.4.0 or 4.5.0, not building from the latest.

**Comment by ivankelly** [comment]
One thing to note is that we cannot publish docker images which are not built from official releases.

https://lists.apache.org/thread.html/d281c8386f44a9eecb98f5606d04bba8aa028860ff683519b8a2c6c3@%3Clegal-discuss.apache.org%3E

A lot of the work for building an image from master is already done in the test images. We could just pull that in.

**Comment by sijie** [comment]
This is done by current-version-image test image. So closed it.
