### ISSUE TITLE
Is it possible to automatically check zookeeper and create bookkeeper metadata when starting bookkeeper?

### ISSUE THREAD

**Issue by StevenLuMT** [apache/bookkeeper#2904]
same like the old question：https://github.com/apache/bookkeeper/issues/2345

hi, I have another question，if the automatically create bookkeeper metadata  can  avoid to introduce many consistency problems,
then whether is  it necessary to submit the codes for this automation function?
 
Looking forward to your reply, thank you

**Comment by StevenLuMT** [comment]
@coolbeevip @sijie

**Comment by shoothzj** [comment]
closed by #2907
