### ISSUE TITLE
Do not throw NoEntryException when failing to read entry log

### ISSUE THREAD

**Issue by Vanlightly** [apache/bookkeeper#2908]
Ledger recovery counts on bookies to respond with OK or an error when a client performing recovery reads an entry that was previously acknowledged to the original client. If a bookie responds with a NoSuchEntry or NoSuchLedger for such an entry, then recovery may close the ledger at that point, truncating it (data loss).

The EntryLogger can throw a NoEntryException if a log file is corrupted, thus leaving BookKeeper vulnerable to ledger truncation when a log file gets corrupted, turning a recoverable data loss situation into an unrecoverable data loss.

PR #2909.

**Comment by anchal0997** [comment]
Hi @Vanlightly , I would like to work on this issue.

**Comment by Shoothzj** [comment]
closed by #2909
