### ISSUE TITLE
Docker image: setup docker automated build on Apache DockerHub account 

### ISSUE THREAD

**Issue by caiok** [apache/bookkeeper#292]
This issue is just for tracking progresses on this matter. It depends on #197.

**Comment by zhaijack** [comment]
Infra ticket opened for it: https://issues.apache.org/jira/browse/INFRA-14756

**Comment by zhaijack** [comment]
INFRA ticket closed. Now we have the docker images under apache dockerhub: https://hub.docker.com/r/apache/bookkeeper/
