### ISSUE TITLE
Enable backward-compatibility tests

### ISSUE THREAD

**Issue by nicoloboschi** [apache/bookkeeper#2930]
Currently, building BookKeeper with Maven doesn't trigger the tests under `tests/backward-compat`. (neither with `-PintegrationTests` and `-DintegrationTests` 
With Gradle these tests run in the test phase but they fail due to timeout while connecting to ZK container.

We need to
1) make sure the tests are run during build (both Maven and Gradle)
2) fix all the tests

I will start a discussion on dev@ for moving to TestContainers and remove the Arquillian Cube framework from the codebase.

This will lead to:
1. Add test-containers setup; starts ZK and _n_ bookie containers (upgrading ZK container to the current used version by BK)
2. Remove Arquillian Cube dependency and setup files (arquillian.xml)
3. Put together all these tests in a single module to increase readability - code reusability - decrease verbosity

**Comment by hsaputra** [comment]
FYI @Vanlightly , @pkumar-singh , @ivankelly

**Comment by pkumar-singh** [comment]
@nicoloboschi Very good idea. Giving some pointers. We are already using gradle to run integration tests with test container. Kindly see If you can lift something from there and reuse.
