### ISSUE TITLE
Change `org.apache.bookkeeper.server.Main` classname，for better recognition.

### ISSUE THREAD

**Issue by gaozhangmin** [apache/bookkeeper#2950]
I suggest change classname `org.apache.bookkeeper.server.Main` to some  more related with bookkeeper.

When using  `jps` commands. it outputs:
![image](https://user-images.githubusercontent.com/9278488/146771377-4c49635a-00be-41c4-8334-054e21a0928e.png)

**Comment by shoothzj** [comment]
+1 for this change. I think change Main class name will not breaking compatible. cc @dlg99 @eolivelli @hangc0276 @merlimat @nicoloboschi @StevenLuMT @zhaijack

**Comment by shoothzj** [comment]
See #4328
