### ISSUE TITLE
waitBackOffTime does not take effect while BKException occurred in ReplicationWorker

### ISSUE THREAD

**Issue by sunshujie1990** [apache/bookkeeper#2956]
**BUG REPORT**

pulsar version 2.8.1
bookkeeper version 4.1.42

***Describe the bug***

org.apache.bookkeeper.replication.ReplicationWorker

BKException cached and return false(org.apache.bookkeeper.replication.ReplicationWorker#rereplicate(long)), this leads to waitBackOffTime does not take effect(org.apache.bookkeeper.replication.ReplicationWorker#run).

![image](https://user-images.githubusercontent.com/24857248/147215051-37e0ab12-9d57-47f4-af04-0ffbff3bcb1b.png)

![image](https://user-images.githubusercontent.com/24857248/147215302-81073505-e237-4434-87db-2f8ed083aa48.png)

This results in a large number of repeated log prints and increased disk load.  In my env it prints 180+ logs per second.

**Comment by StevenLuMT** [comment]
bugfix in this pr:   #2967

**Comment by shoothzj** [comment]
closed by #2967
