### ISSUE TITLE
Pulsar is producing and consuming messages, the bookie_READ_BYTES indicator does not change

### ISSUE THREAD

**Issue by czhfe** [apache/bookkeeper#2960]
**BUG REPORT**

***Describe the bug***

I am using pulsar 2.7.2 and Bookkeeper version is 4.12.0

I am using pulsar 2.7.2 and Bookkeeper version is 4.12.0

I am using the pulsar-perf tool for pulsar performance testing, and in the process I found that the read entry metric of the grafana panel Throughput(MB/s) has been zero

By accessing the Bookkeeper metrics interface at http://Bookkeeper_IP:metrics_port/metrics it was found that the value of the BOOKIE_READ_BYTES metric has not changed. actually does produce and consume messages

***To Reproduce***

Performance stress testing with the pulsar-perf tool, while producing and consuming messages

***Expected behavior***

read entry is not zero

***Screenshots***

![image](https://user-images.githubusercontent.com/19341806/147310817-8064c2d9-8c39-4101-98ba-a4f7a392a988.png)
![image](https://user-images.githubusercontent.com/19341806/147310870-bd53ce82-4fbc-4555-916f-62951e4d8913.png)

***Additional context***

**Comment by 3286360470** [comment]
pulsar has broker cache, can you show the broker cache miss metrics(pulsar_ml_cache_misses_throughput), if the cache miss metrics is 0, so bookie's read entry should be 0.
