### ISSUE TITLE
Could not delete old journal file

### ISSUE THREAD

**Issue by Shawyeok** [apache/bookkeeper#2990]
**BUG REPORT**

***Describe the bug***
Unexpected log by logger `org.apache.bookkeeper.bookie.Journal`
```
Could not delete old journal file /data/journals/01/current/176d24c164b.txn
```

***Additional context***
- bookkeeper version: `4.14.2`
- pulsar version: `2.8.1`
- os: `CentOS Linux release 7.9.2009 (Core)`
- kernel: `3.10.0-1160.45.1.el7.x86_64`

cc @codelipenghui

**Comment by shoothzj** [comment]
Is there any method to reproduce?

**Comment by shoothzj** [comment]
closed by no updates, if you find any new information or way to reproduce, feel free to reopen this issue
