### ISSUE TITLE
[security] Can I change the permission of `.log` and `.idx`

### ISSUE THREAD

**Issue by Shoothzj** [apache/bookkeeper#3000]
Current, in my test environment, I have
- .idx file with permission, 644
- .log file with permission, 755

I want to change the permission to 
- .idx file 640
- .log file 740

How can I make it ?
If there is code needs to change. I'd like to submit a PR.

**Comment by Shoothzj** [comment]
@eolivelli @dlg99 @merlimat @pkumar-singh could you please give me some adivce, thank you

**Comment by dlg99** [comment]
I think it is enough to run bookie under the account that has access to the files/directories (and the cookie file). Stop the bookie, chmod/chown as needed, start the bookie. Also, why do you need 740 (includes execute permission for the user) on the log files if 640 is enough for the idx? FWIW I didn't have to deal with this for a few years, my memory might be murky

@reddycharan do you have any suggestions here?
