### ISSUE TITLE
[website] Update release process guide to Gradle 

### ISSUE THREAD

**Issue by nicoloboschi** [apache/bookkeeper#3019]
We need to edit the [release process guide](https://bookkeeper.apache.org/community/release_guide/) removing maven commands and then explain how cut to and push the release using gradle

Reference: https://github.com/apache/bookkeeper/pull/2681

**Comment by nicoloboschi** [comment]
@pkumar-singh do you have time to work on that ?

**Comment by pkumar-singh** [comment]
Yes sure.

**Comment by lujiwen** [comment]
@pkumar-singh I am developing this project locally, and I want to release for my own project, what is the gradle command to release? Thank you!
