### ISSUE TITLE
[SECURITY] Weak security algorithm used by MacDigestManager

### ISSUE THREAD

**Issue by AliIoT** [apache/bookkeeper#3057]
https://github.com/apache/bookkeeper/blob/7018d2fff35de96a90a1008366e38580e448fb84/bookkeeper-server/src/main/java/org/apache/bookkeeper/proto/checksum/MacDigestManager.java#L43-L44

**Comment by mauricebarnum** [comment]
This is required by the V2 wire protocol.   I don't know what's required to remove that, but at the least I see that Pulsar is still defaulting to v2.

Maybe there's some sort of "yeah, sorry" annotation that can be added so code scanners wouldn't complain?

**Comment by dlg99** [comment]
DigestManager isn't used for the security but for the checksum/checksum validation.

CRC32 should be the default: https://github.com/apache/bookkeeper/blob/7018d2fff35de96a90a1008366e38580e448fb84/conf/bk_server.conf#L883-L884 and https://github.com/apache/bookkeeper/blob/7018d2fff35de96a90a1008366e38580e448fb84/bookkeeper-server/src/main/java/org/apache/bookkeeper/conf/ClientConfiguration.java#L276-L284

CRC32c is recommended for performance.

If you have use case for some other checksuming algorithm you can add it by extending DigestManager class and use configuration to set it.
