### ISSUE TITLE
[SECURITY] Hardcode the password in DigestTypeBenchmark

### ISSUE THREAD

**Issue by AliIoT** [apache/bookkeeper#3058]
https://github.com/apache/bookkeeper/blob/7018d2fff35de96a90a1008366e38580e448fb84/microbenchmarks/src/main/java/org/apache/bookkeeper/proto/checksum/DigestTypeBenchmark.java#L109

Is it ok to hardcode the password in DigestTypeBenchmark? It seems to be a benchmark class, won't use in production. Am I right?
Thanks for your help.

**Comment by dlg99** [comment]
Correct, this is just for the benchmarks.
