### ISSUE TITLE
Bookeeper disk space is not freed

### ISSUE THREAD

**Issue by czhfe** [apache/bookkeeper#3079]
**BUG REPORT**

***Describe the bug***

Bookkeeper disk space is not freed, through troubleshooting found that the file handle is not freed.

***Expected behavior***

Release file handles normally to free up disk space.

***Screenshots***
![image](https://user-images.githubusercontent.com/19341806/156498122-8cbd08e7-e8d2-4d29-829d-4bf6148ecaa1.png)

**Comment by shoothzj** [comment]
Closing this issue since no way to reproduce it. Feel free to reopen it if you find way to reproduce.
