### ISSUE TITLE
support some thread pool associated with CPU cores

### ISSUE THREAD

**Issue by leizhiyuan** [apache/bookkeeper#3098]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

```
numAddWorkerThreads   

numHighPriorityWorkerThreads

numJournalCallbackThreads

numReadWorkerThreads
```

this thread pool is hard code, we use 16/32/64core cpu, it was small for performance.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
   Are you currently using any workarounds to address this issue?

4. Provide any additional detail on your proposed use case for this feature.

**Comment by shoothzj** [comment]
I think as the #3099 describes. It's a breaking change. We can take a consider in next major version.
