### ISSUE TITLE
Recycled LedgerEntryImpl instances are corrupted due to invalid recycling in BK client

### ISSUE THREAD

**Issue by lhotari** [apache/bookkeeper#3104]
**BUG REPORT**

***Describe the bug***

See https://github.com/apache/pulsar/issues/14436#issuecomment-1064758710 for a detailed analysis by @congbobo184 about the symptoms of the thread safety issue.

***To Reproduce***

Follow instructions in https://github.com/apache/pulsar/issues/14436

***Expected behavior***

BK client should handle LedgerEntryImpl instances correctly so that it would prevent the issue where entries are used in 2 threads concurrently, perhaps due to "double recycling".

**Comment by eolivelli** [comment]
Makes sense to me.
I am fine with reverting #3105

data corruption is a bad problem, "being faster" is only an enhancement.

we should revert that change on master branch and on other active branches and possibly cut a new release

**Comment by eolivelli** [comment]
PR for the revert:
https://github.com/apache/bookkeeper/pull/3106

great work @lhotari @congbo1984

**Comment by lhotari** [comment]
This will be fixed by #3110

**Comment by lhotari** [comment]
Fixed by #3110
