### ISSUE TITLE
Tests: suspect warnings like java.lang.LinkageError: loader constraint violation: loader (instance of org/powermock/core/classloader/javassist/JavassistMockClassLoader) previously initiated loading for a different type with name "javax/management/MBeanServer"

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#3115]
***Describe the bug***

I am running locally BookKeeper test and I see warning like the one below, we should take a look

> 
>   Test testRebuildIncludesAllLedgersAndSetToFenced PASSED (2.5s)
> 
>     SLF4J: Class path contains multiple SLF4J bindings.
>     SLF4J: Found binding in [jar:file:/Users/enrico.olivelli/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.17.1/84692d456bcce689355d33d68167875e486954dd/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
>     SLF4J: Found binding in [jar:file:/Users/enrico.olivelli/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
>     SLF4J: Found binding in [jar:file:/Users/enrico.olivelli/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.25/110cefe2df103412849d72ef7a67e4e91e4266b4/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
>     SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
>     SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
>     ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not a subtype
>     ERROR StatusLogger Could not reconfigure JMX
>      java.lang.LinkageError: loader constraint violation: loader (instance of org/powermock/core/classloader/javassist/JavassistMockClassLoader) previously initiated loading for a different type with name "javax/management/MBeanServer"
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
>         at org.powermock.core.classloader.javassist.JavassistMockClassLoader.loadUnmockedClass(JavassistMockClassLoader.java:90)
>         at org.powermock.core.classloader.MockClassLoader.loadClassByThisClassLoader(MockClassLoader.java:104)
>         at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:147)
>         at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:98)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
>         at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:337)
>         at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:261)
>         at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:165)
>         at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:141)
>         at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:637)
>         at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:699)
>         at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
>         at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
>         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
>         at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
>         at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
>         at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
>         at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:55)
>         at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
>         at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
>         at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
>         at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
>         at org.apache.bookkeeper.bookie.BookieThread.<clinit>(BookieThread.java:34)
> 

***To Reproduce***
run
`./gradlew build `

**Comment by nicoloboschi** [comment]
It looks like a problem with Powermockito, we should remove it and use mockito-inline
