### ISSUE TITLE
About apache bookeeper in the parameter unit problem

### ISSUE THREAD

**Issue by czhfe** [apache/bookkeeper#3121]
**QUESTION**

> The unit of dbStorage_writeCacheMaxSizeMb and dbStorage_readAheadCacheMaxSizeMb is Bytes or bit, I understand it is bit, which is not detailed in the documentation.

**Comment by Shoothzj** [comment]
usually, Mb means bytes, I don't think it needs to address in the doc.
I think this issue can be closed. @eolivelli @dlg99

**Comment by eolivelli** [comment]
Yes it is bytes
