### ISSUE TITLE
Need an api interface for the process to start working normally for rolling restart of booklie

### ISSUE THREAD

**Issue by zcola** [apache/bookkeeper#3128]
The official website documentation tells us that we can restart one by one after the canary test.

But in extreme cases, is it possible that the updated bookie process starts too slowly or crashes shortly after startup?

Therefore, when we make operation and maintenance scripts, we need to consider that once the previous update fails to cancel all update tasks, we need an api for detection and judgment. If we observe from monitoring traffic, this method is not universal and provides business.

Or is there an existing way to do it now?

**Comment by gaozhangmin** [comment]
Api `/api/v1/bookie/is_ready` is used to check if bookies are ready
