### ISSUE TITLE
Gradle Build: bad file bookkeeper-4.15.0-SNAPSHOT-src-bin.tar.gz instead of bookkeeper-4.15.0-SNAPSHOT-src.tar.gz

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#3129]
When I build BookKeeper from current master I see that the bookkeeper-dist project generates a file `bookkeeper-4.15.0-SNAPSHOT-src-bin.tar.gz` I would expect `bookkeeper-4.15.0-SNAPSHOT-src.tar.gz`

**Comment by shoothzj** [comment]
gradle is removed now, close the issue.
