### ISSUE TITLE
change compactionRateByBytes or compactionRateByEntries  dynamically

### ISSUE THREAD

**Issue by junedo** [apache/bookkeeper#3147]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

 when  compactionRate  is too small to compact many dirty entry log files  ,we hope  change compactionRateByBytes and compactionRateByEntries dynamically by  rest api  update config and effective immediately
  
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).

should-have

3. Provide any additional detail on your proposed use case for this feature.

we hope add resetRate method for org.apache.bookkeeper.bookie.AbstractLogCompactor.Throttler
and change the rate of rateLimiter before  compact any entry log file.

**Comment by shoothzj** [comment]
closed by no updates. Feel free to reopen it.
