### ISSUE TITLE
remove duplicate metrics TYPE on bookeeper prometheus stats

### ISSUE THREAD

**Issue by shenqianjin** [apache/bookkeeper#3168]
**BP**

> As Prometheus https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information mentioned: "Only one TYPE line may exist for a given metric name". When I started up a bookeeper with pulsar bookie, I found a several TYPE in my metrics are duplicate like below:
```
# TYPE replication_bookkeeper_client_per_channel_bookie_client_ADD_OP_OUTSTANDING counter
replication_bookkeeper_client_per_channel_bookie_client_ADD_OP_OUTSTANDING{bookie="192.168.20.10:3181"} 0
# TYPE replication_bookkeeper_client_per_channel_bookie_client_ADD_OP_OUTSTANDING counter
replication_bookkeeper_client_per_channel_bookie_client_ADD_OP_OUTSTANDING{bookie="192.168.20.15:3181"} 0
```
More than one TYPE with different tags should be blong to the same metrics name. Therefore, I make this proposal to suggest bookeeper to follow the same TYPE name rule of Prometheus.

This is the master ticket for tracking BP-xyz :

[a short description for this BP]

Proposal PR - #abc

**Comment by Shoothzj** [comment]
@shenqianjin does #3137 solves your problem?

**Comment by Shoothzj** [comment]
@dlg99 I think we can close this issue by #3137
