### ISSUE TITLE
Missing label in issue labels list

### ISSUE THREAD

**Issue by sulunemre** [apache/bookkeeper#3209]
Hi, although the flaky test issue [template ](https://github.com/apache/bookkeeper/blob/master/.github/ISSUE_TEMPLATE/flaky_test.md)has `flaky-tests` in its labels, that label is not added automatically to the new issues because `flaky-tests` label doesn't [exist](https://github.com/apache/bookkeeper/labels). It should be created by a project admin.
Example: https://github.com/apache/bookkeeper/issues/3206

**Comment by nicoloboschi** [comment]
Thanks @sulunemre . I created the label and added it to all the recent flaky-tests issues
