### ISSUE TITLE
[website] ci job to automatically publish website to apache once the pull request is merged

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#323]
Pushing website to live should be automated. A CI job can be triggered to do this once the source file change is done.

**Comment by eolivelli** [comment]
O can pickup this if you want.
We can integrate with job builder too

**Comment by sijie** [comment]
@eolivelli I added the scripts at #332 and created https://builds.apache.org/view/BK/job/bookkeeper-postcommit-publish-website/configure job.

feel free to help with the job builder, I am not an expert on jenkins though.
