### ISSUE TITLE
Can't directly run LocalBookkeeper from `bookkeeper-server` module

### ISSUE THREAD

**Issue by Shoothzj** [apache/bookkeeper#3243]
Currently, we can't run LocalBookKeeper  directly from the bookkeeper-server module, because the `snappy-java` and `metrics-core` are marked as test dependency, the LocalBookKeeper needs them. Should we make these dependency to compile?

**Comment by nicoloboschi** [comment]
What's the advantage of the possibility to run it from the server module?

**Comment by Shoothzj** [comment]
@nicoloboschi the advantage is that allow people can run it directly from ide
<img width="719" alt="image" src="https://user-images.githubusercontent.com/12933197/164909141-95244d0f-6bcd-4bbd-8d81-148d74f8b18b.png">

**Comment by dlg99** [comment]
I haven't looked at this closely, in case you have: how does it get these dependencies when runs from the command line? What's different in the jar built there/shell scripts that launch it?

**Comment by Shoothzj** [comment]
@dlg99 In command line case, we have dependency in `bookkeeper-dist-server`, which scope is `compile`
