### ISSUE TITLE
Should we shutdown the bookie or retry when registration failure

### ISSUE THREAD

**Issue by Shoothzj** [apache/bookkeeper#3250]
about the flaky test https://github.com/apache/bookkeeper/issues/3206

I have figured out why testBookieServerZKExpireBehaviour falky.

It's due to Registration task, bookie will retry to registration when zk session expires. If the registration fail, it will cause the bookie shutdown ExitCode.ZK_REG_FAIL.

@dlg99 @eolivelli @merlimat PTAL

**Comment by dlg99** [comment]
de-facto doc:
https://github.com/apache/bookkeeper/blob/6b03b012f731536af56cc63ba29511f09994d11b/conf/bk_server.conf#L804-L809

BK will exit on SessionExpiredException from zk client; it is hard to recover from it (have to re-create the zk client + redo all initialization steps of all subcomponents) so better to exit and let k8s/supervisord restart the service.
