### ISSUE TITLE
Docker image: Drop versions and Alpine support

### ISSUE THREAD

**Issue by caiok** [apache/bookkeeper#327]
We need to drop alpine support and multiple versions support and move all docker related files in docker  main directory.

On master we will only support the current unreleased version of bookkeeper. This build will not be buildable until the release procedure occurs (and release package has been uploaded to apache mirror). If we want to add support to previous bk releases or we need to change something in previous released docker files, we need to commit changes in the appropriate release branch.

Questions: 
- how to achieve #289 without any sub dir? Maybe it could be a more organized to keep doc files in main dirs (e.g. Readme, docker compose, etc) and have two dirs for builds, e.g. "release" and "onbuild".
- which versions should we initially support?

**Comment by jiazhai** [comment]
fixed in PR #342
