### ISSUE TITLE
[Doc] Invalid hyperlink for Apache Pulsar in the OverView page

### ISSUE THREAD

**Issue by zwOvO** [apache/bookkeeper#3270]
**BUG REPORT**

***Describe the bug***

Invalid hyperlink for Apache Pulsar#persistent-storage

***To Reproduce***

1. Go to [OverView](https://bookkeeper.apache.org/docs/overview)
2. Click on 'Apache Pulsar'

***Expected behavior***

404 error page

***Screenshots***
![image](https://user-images.githubusercontent.com/18533252/167837853-5c91daa8-3b1f-4c6a-abfd-0114f47efcf7.png)

**Comment by shoothzj** [comment]
closed by #3271
