### ISSUE TITLE
[website]Invalid hyperlink for bookkeeper.apache.org

### ISSUE THREAD

**Issue by zwOvO** [apache/bookkeeper#3275]
**BUG REPORT**

***Describe the bug***

The hyperlink to bookkeeper.apache.org is out of date

***To Reproduce***
**visit website**
[installation guide](https://bookkeeper.apache.org/docs/latest/getting-started/installation/)
[documentation](http://bookkeeper.apache.org/docs/latest/)

***Expected behavior***

1、404 error page
2、outdated FTP page

***Screenshots***
![image](https://user-images.githubusercontent.com/18533252/168042971-97d4c0a7-67f5-402e-8569-1b96f8201293.png)

![image](https://user-images.githubusercontent.com/18533252/168043024-99a5fafc-7d4b-45e4-94be-4bf01ca21578.png)

**Comment by shoothzj** [comment]
closed by #3276
