### ISSUE TITLE
Docker image: gracefully handle start and stop bookie gracefully

### ISSUE THREAD

**Issue by caiok** [apache/bookkeeper#329]
We should modify run.sh to do a deleteCookie before bookie start and an autorecovery after its end, like done in @kishorekasi code:

`CMD /bookkeeper/bookkeeper-server/bin/bookkeeper shell bookieformat -nonInteractive -force -deleteCookie; /bookkeeper/bookkeeper-server/bin/ bookkeeper bookie; /bookkeeper/bookkeeper-server/bin/bookkeeper autorecovery`

**Comment by sijie** [comment]
I just happen to see this issue. I don't think we should do bookieformat at the entrypoint. this command basically destroys the data. 

also I don't think we need to run bookie and autorecovery together. this also limits the way how people want to deploy. when we have a docker image, it can be used for deploying in multiple ways.

- deploy a bookie cluster: only run bookie deamon
- deploy an `autorecovery` cluster: only run `autorecovery`
- deploy a bookie cluster along with `autorecovery`.

from this purpose, I don't see a value for having an entrypoint.sh then.

@kishorekasi do you mind clarifying more about the entrypoint.sh piece?

**Comment by zhaijack** [comment]
I have recorded these command into README in PR #342 .  And these command could be an alternative to the default [bookkeeper bokie] command, if the user want to do autorecovery, or do a fresh deploy of new bookies.

**Comment by jiazhai** [comment]
recorded in README, in PR #342
