### ISSUE TITLE
missing video link(possibly) in documentation

### ISSUE THREAD

**Issue by sudoHackIn** [apache/bookkeeper#3293]
In documentation about Paxos
https://bookkeeper.apache.org/docs/api/ledger-api/#leaders-and-followers-and-a-bit-of-background

in 
Paxos is an abstract algorithm to implement this kind of agreement, while Zab and Raft are more practical protocols. **This video gives** a good overview about how these algorithms usually look

There possibly missing link to video (for example like this https://www.youtube.com/watch?v=d7nAGI_NZPk)

**Comment by nicoloboschi** [comment]
I checked the website git history and that video has never been there. 
@sudoHackIn would you mind to add it ? the file to modify is https://github.com/apache/bookkeeper/blob/master/site3/website/docs/api/ledger-api.md

**Comment by sudoHackIn** [comment]
> I checked the website git history and that video has never been there. 
> @sudoHackIn would you mind to add it ? the file to modify is https://github.com/apache/bookkeeper/blob/master/site3/website/docs/api/ledger-api.md 

No problem, but i'm not sure what is the best source for link. Is provided video good enough?
