### ISSUE TITLE
JVM exited when running localbookie

### ISSUE THREAD

**Issue by boatrainlsz** [apache/bookkeeper#3295]
***Describe the bug***
JVM exited when running localbookie
bk version : latest
jdk version: 
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)
***To Reproduce***

1. download latest bin zip from release page and upzip it
2. execute `bin/bookkeeper localbookie 10` command
3. JVM can't be created, and got this error message:
```
Unrecognized VM option 'AggressiveOpts'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

***Expected behavior***
local bk can run normally
***Screenshots***

![image](https://user-images.githubusercontent.com/18243785/170850343-49afb519-be46-4f57-ada9-fc9524cae78b.png)
***Additional context***

I did some some research and I find a [solution](https://github.com/pravega/bookkeeper-operator/blob/master/doc/troubleshooting.md#unrecognized-vm-option), so I add the `-XX:+IgnoreUnrecognizedVMOptions` to `bookkeeper` shell, and problem solved:
![image](https://user-images.githubusercontent.com/18243785/170850542-4e686dfb-a9bc-427f-a3d3-3a2170967e56.png)

I wonder can this parameter be added to standard options? a update to doc would save others time too.

**Comment by sudoHackIn** [comment]
This flag (-XX:+AggressiveOpts) was deprecated in JDK 11 and removed in JDK 12(https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8199778), and according to link

> The only effect that the flag currently has is setting AutoBoxCacheMax = 20000 and BiasedLockingStartupDelay = 500. Both can be done manually by setting the corresponding flags on the command line.
So, may be the best solution - to remove AggressiveOpts and define AutoBoxCacheMax and BiasedLockingStartupDelay explicitly. According to [Java’s -XX:+AggressiveOpts: Can it slow you down?](https://www.opsian.com/blog/aggressive-opts/)](https://www.opsian.com/blog/aggressive-opts/) - AggressiveOpts in java 8 also include only this flags

**Comment by weiping-code** [comment]
I can work on this
