### ISSUE TITLE
BookKeeper Benchmarks suite cannot run on non-English machines

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#331]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
I was trying to run bookkeeper benchmarks using a terminal with LANG=it_IT.UTF-8

- What did you expect to see?
The bench running

- What did you see instead?

bin/benchmark writes --help
Errore: impossibile trovare o caricare la classe principale org.apache.bookkeeper.benchmark.BenchThroughputLatency

Workaround:
if I run the command with english locale the program is loading
LANG=en_EN,UTF-8 bin/benchmark writes --help

**Comment by shoothzj** [comment]
Now we have `bin/bkperf` instead of `bin/benchmark`. And it doesn't reproduce
