### ISSUE TITLE
Add Pravega to use-cases in Readme/Documentation

### ISSUE THREAD

**Issue by RaulGracia** [apache/bookkeeper#3327]
**BUG REPORT**

***Describe the bug***

We could add Pravega to the use-cases documentation of Bookkeeper, as it is an important dependency for Pravega.

***To Reproduce***
n/a

***Expected behavior***

Add Pravega to the use cases in doc.

***Screenshots***

n/a

***Additional context***

n/a

**Comment by Shoothzj** [comment]
closed by #3328
