### ISSUE TITLE
backward-compat test in CI doesn't run at all

### ISSUE THREAD

**Issue by hangc0276** [apache/bookkeeper#3345]
The PR https://github.com/apache/bookkeeper/pull/3340 breaks the `backward-compact` test, after this PR merged, the `backward-compact-tests` in CI don't run at all.

https://github.com/apache/bookkeeper/runs/6928923882?check_suite_focus=true

**Comment by shoothzj** [comment]
It's fixed now. See recently builds. https://github.com/apache/bookkeeper/actions/runs/8930107233/job/24529719878
