### ISSUE TITLE
Docker image: DCOS package update and instructions

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#336]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Update DCOS package by using latest docker image;
Update instructions on how to use it.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have

3. Provide any additional detail on your proposed use case for this feature.

**Comment by jiazhai** [comment]
https://github.com/mesosphere/universe/issues/1544 has update the BookKeeper package to version 4.5.1

**Comment by sijie** [comment]
@jiazhai can you write a documentation page about the steps on updating DCOS Universe package? It would be good to make it part of release process.

**Comment by sijie** [comment]
@jiazhai can you update an instruction on release page about the process of updating DCOS universe package?

**Comment by jiazhai** [comment]
@sijie 
It is simple if only for version, the main change is in [mesosphere repo](https://github.com/mesosphere/universe). 
1.  make a copy of [old version](https://github.com/mesosphere/universe/tree/version-3.x/repo/packages/B/bookkeeper/1)
2.  change 2 files related to version, once we have new version of bookkeeper docker image available at apache/bookkeeper:
- [resource.json](https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/B/bookkeeper/1/resource.json#L5)
- [package.json](https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/B/bookkeeper/1/package.json#L4)
3. create a Pull Request and wait for approve and merge.

Will update the instruction on release page.

**Comment by sijie** [comment]
thank you @jiazhai
