### ISSUE TITLE
Use ephemeral port for bookkeeper tests

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#339]
*Problem*

Ephemeral port was introduced at #296 . It would be good if we can use ephmeral port in bookkeeper tests to improve the stability of unit tests.

**Comment by eolivelli** [comment]
@zhaijack maybe we can get this into 4.6, I would like not to apply this important change now that we are close to the release, what do you think ?

**Comment by zhaijack** [comment]
@eolivelli the main reason for this is to ensure we have a stable test for cutting 4.5.0. If we can't get the unit test back to stable, we don't really have any confidence on 4.5.0. /cc @sijie

**Comment by eolivelli** [comment]
@zhaijack do you think that 'flakyness' is due to TCP port which are not closed correctly ?
IMHO tests used to run smoothly last month, if we have introduced bugs we should address the problems.

For instance the backward compat tests use the v2 protocol and you told that my recent commit broke the v2 protocol.

I will be happy to have the full suite running without changes

**Comment by zhaijack** [comment]
@eolivelli I've fixed most of the issues in #340 please take a look. 

I addressed the broken tests not by adding ephemeral port. Those broken tests were correctly fixed. Using the ephemeral port is to provide even more stable build, otherwise we will never be able to cut a successful release.

There are also two benefits on running with ephemeral port: 1) a unit test will be come less impacted by a bad unit test not shutting down bookie correctly. it would help identify the problem. 2) it will allow individual unit test running at a more isolated environment. this would allow potentially run tests in parallel in future. currently jenkins run modules in parallel, however bookkeeper-server can't not be run in parallel, because of the port problem.

**Comment by sijie** [comment]
thank you @eolivelli @zhaijack . it is a good conversation. I marked this in 4.5.0. Let's try to include this for the release.
