### ISSUE TITLE
Upgrade JNA dependency

### ISSUE THREAD

**Issue by aluccaroni** [apache/bookkeeper#3394]
**FEATURE REQUEST**

BookKeeper currently depend from JNA 3.2.7 (https://github.com/java-native-access/jna), released in 2010: we are a lot behind the current release.

We embed BK in our application and recently we encountered an issue with another peace of software that needs JNA 5.8.0+ in it's latest version, so we are stuck. There are no security issue on the JNA side (that I'm aware off) but my request is to upgrade to the latest version.

Please note that there are breaking changes in JNA 5.0.0, so we cannot simply upgrade the lib and be done with it.

**Comment by eolivelli** [comment]
Do you have some error to share ? did you try to upgrade ?

**Comment by dlg99** [comment]
let's see if this works: https://github.com/apache/bookkeeper/pull/3400
It built locally but I didn't run the tests
