### ISSUE TITLE
Prs need to be included in 4.16.0

### ISSUE THREAD

**Issue by hangc0276** [apache/bookkeeper#3412]
This issue is used to track Prs that need to be included in the BookKeeper 4.16.0 release.
  - [x] https://github.com/apache/bookkeeper/pull/3406
  - [x] https://github.com/apache/bookkeeper/pull/3361
  - [x] https://github.com/apache/bookkeeper/pull/3383
  - [x] https://github.com/apache/bookkeeper/pull/3384
  - [x] https://github.com/apache/bookkeeper/pull/3390
  - [x] https://github.com/apache/bookkeeper/pull/3325
  - [ ] https://github.com/apache/bookkeeper/pull/3329
  - [x] https://github.com/apache/bookkeeper/pull/3330
  - [ ] https://github.com/apache/bookkeeper/pull/3359
  - [x] https://github.com/apache/bookkeeper/pull/3212
  - [x] https://github.com/apache/bookkeeper/pull/3194

If you have more Prs that need to be included, please add them to the above list.

**Comment by Shoothzj** [comment]
https://github.com/apache/bookkeeper/pull/3435 I think this PR should be included in 4.16.0. It's useful for embedded bookkeeper users
