### ISSUE TITLE
Standardize the check process of bookkeeper's workflow like pulsar project

### ISSUE THREAD

**Issue by StevenLuMT** [apache/bookkeeper#3447]
TestTLS.testConnectToLocalTLSClusterTLSClient can't run all successfully in branch master and 4.15.1-rc0,
it seems that this problem has appeared long ago, rather than being introduced separately in this 4.15.1-rc0 

this picture is the result for 4.15.1-rc0's testcase result:
<img width="2248" alt="image" src="https://user-images.githubusercontent.com/42990025/185054556-c285197a-4494-429e-befb-c83332e183ae.png">

this picture is the result for master's testcase result:
<img width="2546" alt="image" src="https://user-images.githubusercontent.com/42990025/185054680-4d8ceffa-59e3-4eb0-9fb7-19fc570d68ae.png">

As for why the testcase run failed,it's caused by #3310 , we can revert #3310 or fix the bug
but I think it is necessary to standardize the check process of bookkeeper's workflow like pulsar project
change some checks to required instead of artificially strong merge

for example pr #3435 's workflow run [failed](https://github.com/apache/bookkeeper/pull/3435/checks), but be merged
<img width="944" alt="image" src="https://user-images.githubusercontent.com/42990025/185199297-3fa9b3e9-3a31-4171-865f-7b20a57e3489.png">

this picture is bookkeeper's workflow check,no check is required:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/42990025/185053187-1e19855b-2562-4e51-800d-c4d6ab6db875.png">

this picture is pulsar's workflow check,checks are required:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/42990025/185055765-a2305f2e-d3b0-47b9-a10f-928f6b1c5853.png">

**Comment by zymap** [comment]
https://github.com/apache/bookkeeper/pull/3439
this PR is for this

**Comment by StevenLuMT** [comment]
> 

yes, look good to me,thanks @zymap

**Comment by StevenLuMT** [comment]
#3439  #3451 and #3453 
fix for this

**Comment by nicoloboschi** [comment]
@zymap @StevenLuMT I guess we can close this issue now
