### ISSUE TITLE
Apache rat check failed on master

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#351]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

run `apache-rat:check`

- What did you expect to see?

the task should pass

- What did you see instead?

The task passed locally on mac, but failed on jenkins: https://builds.apache.org/job/bookkeeper-master/ws/bookkeeper-server/target/rat.txt

**Comment by zhaijack** [comment]
The cacerts introduced in #183 is supposed to be binary. however the behavior on jenkins is a bit different from on mac.

The fix should be simple and straightforward by excluding cacerts from rat check.

**Comment by sijie** [comment]
nice caught @zhaijack

**Comment by sijie** [comment]
reopen this issue. I think the fix doesn't actually work. looking into it now.
