### ISSUE TITLE
github contributing guidelines

### ISSUE THREAD

**Issue by zwOvO** [apache/bookkeeper#3532]
**QUESTION**
Why not write the github contribution guide to communicate how people should contribute to the bookkeeper project?

![image](https://user-images.githubusercontent.com/18533252/195984576-15cbd25e-6ae4-4315-8c84-dcbd301a73f5.png)

[github.com/setting-guidelines-for-repository-contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)

**Comment by shoothzj** [comment]
closed by #3533
