### ISSUE TITLE
[documentation] configuration settings

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#360]
1) for the configuration file

- make sure `bk_server.conf` contains all the settings in ServerConfiguration.java
- add `autorecovery.conf` to include all the settings required for `autorecovery`, basically the settings from ClientConfiguration.java and some `autorecovery` settings in ServerConfiguration.java

2) update `site/docs/reference/config.md` (http://bookkeeper.apache.org/test/content/docs/reference/config/)

All the configuration settings are listed in `site/_data/config/bk_server.yaml`. Make sure it contains all the settings in ServerConfiguration.java

Also add a section for `autorecovery` settings.

**Comment by jiazhai** [comment]
@sijie Regarding autorecovery, there seems only few paremeters, how about ignore them at this time?
