### ISSUE TITLE
Error in parsing entrylog file causes GC failure

### ISSUE THREAD

**Issue by 1559924775** [apache/bookkeeper#3607]
**BUG REPORT**

***Describe the bug***

When bookie GC encounters an entryLog file with disordered data, a IllegalArgumentException are not caught, resulting in the death of the GC thread and the end of the GC process.
This problem is encountered again in the next GC, resulting in the subsequent entrylog being unable to GC.
The problem described in this issue(#3604) will cause the entryLog file to be disordered, and will cause the IllegalArgumentException when parsing the entrylog file.

![image](https://user-images.githubusercontent.com/35036009/199923547-367a1c0c-8eac-426d-ad7d-50769849efce.png)
In our case, due to the disorder of the entrylog file, the exception in the above figure appeared. This exception is not a subclass of IOException and cannot be caught.
@hangc0276

**Comment by shoothzj** [comment]
This only affects branch-4.14. master change is #3263
