### ISSUE TITLE
Specify Zookeeper tag in Docker Compose

### ISSUE THREAD

**Issue by tomaszmichalak** [apache/bookkeeper#3657]
**BUG REPORT**

The `pom.xml` file specifies Zookeeper version:
```xml
    <zookeeper.version>3.8.0</zookeeper.version>
```

However, Docker Compose `docker/docker-compose.yml` configuration points to the latest tag, which can be a different version. 

***Expected behavior***

Please replace: `image: zookeeper` with `image: zookeeper:3.8.0`.

***Additional context***

Can not start Docker Compose from `docker`.

**Comment by eolivelli** [comment]
could you please send a PR ?
thanks
