### ISSUE TITLE
javac.target inconsistent with JDK used for compilation?

### ISSUE THREAD

**Issue by Ghatage** [apache/bookkeeper#3667]
**QUESTION**

Hi @sijie @eolivelli @dlg99,

I noticed that the root pom has [javac.target set to 1.8 ](https://github.com/apache/bookkeeper/blob/034e8997ab43850d2968d8780abf9bb6e57dabd5/pom.xml#L110)(jdk8) but we support compilation on jdk11 and jdk17 as well.
So wondering how that works if the javac.target is hard coded?

Does that infer that our code does not use any 11 / 17 specific features and its OK to cross compile using the 1.8 compiler?

**Comment by nicoloboschi** [comment]
All the CI tests BK using jdk11. 
However jdk 1.8 compilation is still supported both for bookies and clients.

I'm not aware of any plan to drop jdk8 compatibility in the near future
