### ISSUE TITLE
Bookie decommission blocked due to OPEN state empty ledgers

### ISSUE THREAD

**Issue by hangc0276** [apache/bookkeeper#3692]
**BUG REPORT**

***Describe the bug***

When we decommission a bookie, the decommissioning process will be blocked when encountering an `OPEN` state of empty ledgers. 

***Expected behavior***

The ledger's metadata should be changed to new bookies even though the ledger is empty.

**Comment by dlg99** [comment]
The "open" part is probably related to openLedgerRereplicationGracePeriod setting.

The empty part should be fixed by https://github.com/apache/bookkeeper/pull/3239

**Comment by hangc0276** [comment]
> The "open" part is probably related to openLedgerRereplicationGracePeriod setting.
> 
> The empty part should be fixed by #3239

@dlg99 Thanks for your suggeston. It can be resolved by the above change.
