### ISSUE TITLE
Non-deterministic tests

### ISSUE THREAD

**Issue by priyanka-28** [apache/bookkeeper#3701]
**BUG REPORT**

***Describe the bug***

The test org.apache.bookkeeper.slogger.SloggerTest#testMap passed using normal maven-test, but showed Non-deterministic behavior under NonDex(https://github.com/TestingResearchIllinois/NonDex) and thus failed.

***To Reproduce***

https://github.com/TestingResearchIllinois/NonDex
Nondex is order-dependent flaky tests detection tool developed by a research group led professor Darko at UIUC
Navigate to the project repo, compile and run the following -

mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex

***Expected behavior***

Tests should show stable and deterministic behaviour.

***Screenshots***

Some of the error messages are as follows-

<img width="465" alt="image" src="https://user-images.githubusercontent.com/52324780/206885171-c868a485-61e2-4b2f-bf46-315ad9c550d6.png">

***Additional context***

**Comment by shoothzj** [comment]
closed by #3702
