### ISSUE TITLE
latest docker image run failed because /usr/lib/jvm/java-17-openjdk-/bin/java : No such file or directory

### ISSUE THREAD

**Issue by Shoothzj** [apache/bookkeeper#3752]
**BUG REPORT**

```bash
winpty docker run -p 2181:2181 -p 8080:8080 --rm apache/bookkeeper:latest
```
`apache/bookkeeper:latest` docker image run failed because /usr/lib/jvm/java-17-openjdk-/bin/java : No such file or directory

**Comment by xuthus5** [comment]
on the latest version of bookkeeper, I get a correct feedback.
![截图_2023-03-27_21-34-12](https://user-images.githubusercontent.com/22839236/227954340-4e31debb-b089-4943-b6bc-66c7dc90ef6c.png)
![截图_2023-03-27_21-34-31](https://user-images.githubusercontent.com/22839236/227954408-a6f53e79-a037-43e2-8b00-1e83a3696318.png)
