### ISSUE TITLE
Force GC API PUT Call fails with Internal Server Error

### ISSUE THREAD

**Issue by Apurva007** [apache/bookkeeper#3845]
**BUG REPORT**

Force GC API PUT call fails with Internal Server Error

1. Create a Bookkeeper cluster of 5 nodes
2. Run the PUT request: curl  --request PUT '{IP}:8000/api/v1/bookie/gc'

Expected Behavior:
200 should be returned by the bookie

Bookie Version: 4.15.3

**Comment by BewareMyPower** [comment]
You have to pass the JSON data, e.g.

```bash
curl -L http://localhost:8009/api/v1/bookie/gc -X PUT -H 'Content-Type: application/json' -d '{"is_in_force_gc": "true"}'
```

P.S. My BK HTTP server listens on port 8009.

BTW, there is no log in the bookie server. /cc @hangc0276

**Comment by Apurva007** [comment]
@BewareMyPower Thanks for the response. The curl command worked on my cluster and the GC was triggered.

@hangc0276 I can also confirm that there were no error logs on the bookie server when the "internal server error" was thrown.

I really appreciate the help. @BewareMyPower / @hangc0276 .

I am happy to help with a PR for the documentation changes if you point me to the location.

**Comment by fantastywusheng** [comment]
"Why am I getting '<html><body><h1>Resource not found</h1></body></html>'? My Pulsar version is 2.3.0."

**Comment by fantastywusheng** [comment]
Why am I getting 'Resource not found'? My Pulsar version is 2.3.0.
