### ISSUE TITLE
[Homepage] Broken links on overview page

### ISSUE THREAD

**Issue by bossenti** [apache/bookkeeper#3868]
**BUG REPORT**

***Describe the bug***

On the project's homepage several links are broken on the overview page (https://bookkeeper.apache.org/docs/overview).

***To Reproduce***

Visit https://bookkeeper.apache.org/docs/overview with the current version `4.15.4` and click on internal links, e.g.,
`Admin Guide` or `design details` (see more examples in the screenshot section)

***Expected behavior***

The hyperlinks provided should resolve

***Screenshots***
![bookkeeper-issue](https://user-images.githubusercontent.com/50115603/225383021-6292a0e7-a336-4e1b-bd23-c5d7e7309e7c.gif)

**Comment by nicoloboschi** [comment]
@bossenti I'm not reproducing it, what is the url you're redirect to ?

**Comment by bossenti** [comment]
@nicoloboschi now it works for me too 🙈
Maybe just a quick hick-up...
Sorry for bothering!
