### ISSUE TITLE
Should we upgrade the test framework from JUnit to TestNG?

### ISSUE THREAD

**Issue by gaozhangmin** [apache/bookkeeper#3870]
JUnit has limited functions, such as don't support @DataProvider annotations, it's not convenient for unit-test.
The more extensive and specialised annotations that are available in TestNG give it an advantage over JUnit in terms of power.
Does the community consider upgrading test framework from JUnit to TestNG?

**Comment by Shoothzj** [comment]
I would not recommend switching to TestNG. JUnit is sufficient and currently, developers can easily maintain it. There doesn't seem to be a strong reason to switch to a different testing framework at this time.
