### ISSUE TITLE
BookKeeperDiskSpaceWeightedLedgerPlacementTest.testDiskSpaceWeightedBookieSelectionWithBookiesDying failed

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#399]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

ci job ran

- What did you expect to see?

ci passed

- What did you see instead?

```
java.lang.AssertionError: Weigheted placement is not honored1
	at org.apache.bookkeeper.client.BookKeeperDiskSpaceWeightedLedgerPlacementTest.testDiskSpaceWeightedBookieSelectionWithBookiesDying(BookKeeperDiskSpaceWeightedLedgerPlacementTest.java:330)
```

https://builds.apache.org/job/bookkeeper-release-nightly-snapshot/org.apache.bookkeeper$bookkeeper-server/7/testReport/junit/org.apache.bookkeeper.client/BookKeeperDiskSpaceWeightedLedgerPlacementTest/testDiskSpaceWeightedBookieSelectionWithBookiesDying/

**Comment by ivankelly** [comment]
@sijie Closing this. There's not enough info to go on. We can reopen again if we find that this test is flaking.
