### ISSUE TITLE
Docker image: fix non-privileged user execution

### ISSUE THREAD

**Issue by caiok** [apache/bookkeeper#405]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

I run bookkeeper using "--user $(id -u)" option in "docker run" 

- What did you expect to see?

Bookeeper process owned by the current user in the host system.  

- What did you see instead?

Process is owned by root

**Comment by caiok** [comment]
I've already fixed, but I can't assign this issue to me. I'll submit a PR asap.

/cc @jiazhai

**Comment by caiok** [comment]
Created PR #406

**Comment by sijie** [comment]
@caiok I assigned this to you. 

(I think only committers can assign the issues. I need to figure out to how to make contributors able to self-assign issues)

**Comment by jiazhai** [comment]
Thanks a lot for the fix @caiok , have already merged it.
