### ISSUE TITLE
BookKeeper Server distribution contains useless jar guava-20.0.jar

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#409]
While checking Apache BookKeeper 4.5.0 rc0 for release I have noticed that in "lib" directory there is a 
file named guava-20.0.jar. This jar is not useful as we are "shading" guava.
It should be removed

**Comment by sijie** [comment]
@eolivelli 
currently we are relying mvn plugins to build the packages. the guava-20.0.jar is placed on mvn package. If it is easy to configure mvn plugin to exclude shaded dependencies, we can do it. If it is not easy to do or it makes release procedure complicated, I would prefer not doing that.

**Comment by eolivelli** [comment]
This is not a shostopper for 4.5 release.
I will take a look for next release this is really a minor issue.

**Comment by sijie** [comment]
sure.

**Comment by sijie** [comment]
@eolivelli I am making this a blocker for 4.6.

**Comment by eolivelli** [comment]
Ok I will send patch soon. Today I am on vacation it should be an easy patch.

**Comment by sijie** [comment]
closed this as "won't fix"
