### ISSUE TITLE
BookKeeper 4.5 binary distribution package contains a legacy CHANGES.txt file 

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#410]
The bookkeeper 4.5 binary package contains a stale CHANGES.txt file about 4.4.
We should drop it or update it in the future, maybe for 4.6

**Comment by sijie** [comment]
@eolivelli where did you find the stale README?

**Comment by eolivelli** [comment]
@sijie my bad, it is a CHANGES.txt file, in the binary distribution file 
https://dist.apache.org/repos/dist/dev/bookkeeper/4.5.0-rc0/
bookkeeper-server-4.5.0-bin.tar.gz

**Comment by sijie** [comment]
okay. we should drop `CHANGES.txt` in future (next release or next rc if we need one more).
