### ISSUE TITLE
BookieNettyServer#listenOn  netty WRITE_BUFFER_WATER_MARK setting does not take effect

### ISSUE THREAD

**Issue by keyboardbobo** [apache/bookkeeper#4107]
**BUG REPORT**

***Describe the bug***

```
bootstrap.option(ChannelOption.WRITE_BUFFER_WATER_MARK, new WriteBufferWaterMark(
                    conf.getServerWriteBufferLowWaterMark(), conf.getServerWriteBufferHighWaterMark()));

```
should be :

```
            bootstrap.childOption(ChannelOption.WRITE_BUFFER_WATER_MARK, new WriteBufferWaterMark(
                    conf.getServerWriteBufferLowWaterMark(), conf.getServerWriteBufferHighWaterMark()));

```

Instead of setting the parameters of option, set the parameters of childOption. Otherwise it will not take effect

**Comment by lhotari** [comment]
> Instead of setting the parameters of option, set the parameters of childOption. Otherwise it will not take effect

@keyboardbobo Yes that's correct. Have you run across a problem that this has caused?

**Comment by lhotari** [comment]
The impact of this bug is that the Netty defaults have been used (low 32kB, high 64kB) instead of the expected defaults low 384kB high 512kB.
