### ISSUE TITLE
Bookie OutOfDirectMemoryError when using DirectEntryLogger

### ISSUE THREAD

**Issue by graysonzeng** [apache/bookkeeper#4134]
**BUG REPORT**

***Describe the bug***
`2023-11-25T14:29:27,343+0800 [BookieReadThreadPool-OrderedExecutor-5-0] ERROR org.apache.bookkeeper.server.service.BookieService - Unable to allocate memory, exiting bookie 
 io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 8392704 byte(s) of direct memory (used: 15024140317, max: 15032385536)`

***To Reproduce***

This issue occurs when using high throughput for writing and reading (e.g., 1GB/s), and when a catch up read occurs.

Bookie Version: 4.16.2

***Expected behavior***

***Screenshots***

***Additional context***

**Comment by shoothzj** [comment]
closed by #4135
