### ISSUE TITLE
[improve][stats] Enhance bookie metrics to support URL parameter filtering

### ISSUE THREAD

**Issue by zwOvO** [apache/bookkeeper#4143]
### Feature Request for Bookkeeper Issue

**Feature Request:**
I would like to request an improvement to the bookie metrics interface, allowing it to filter metrics by URL parameters. This is important to me as we are currently facing an issue with an excessive amount of temporarily unused metrics being collected by our alerting platform. These metrics are useful for monitoring purposes, but not for the alerting platform.

**Proposed Improvement:**
Allow filtering of metrics using URL parameters, for example:
   - `/metrics?m_regex=bookkeeper_server_thread_executor_queue`
   - `/metrics?m_regex=.*_thread_executor_queue`

**Are you willing to submit a PR?**
 I'm willing to submit a PR!

**Comment by miton18** [comment]
Can't you filtre metrics on the collector side ?

**Comment by zwOvO** [comment]
> I would like to request an improvement to the bookie metrics interface, allowing it to filter metrics by URL parameters. This is important to me as we are currently facing an issue with an excessive amount of temporarily unused metrics being collected by our alerting platform. These metrics are useful for monitoring purposes, but not for the alerting platform.

Our alarm platform only needs to configure a Prometheus export port to complete indicator collection, and the large number of indicators currently exposed by Bookie do not need to be collected and saved in the alarm platform.
