### ISSUE TITLE
[website] content overlap under some view

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#417]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
view the [website](http://bookkeeper.apache.org/docs/latest/getting-started/installation/), and narrow the browser. 

- What did you expect to see?
no content overlap

- What did you see instead?
content overlap

---------------------------------------------------------------------------------
<img width="889" alt="default" src="https://user-images.githubusercontent.com/26834121/29062400-26c49ae8-7c54-11e7-9f76-b96ff0b57114.png">

**Comment by sijie** [comment]
@jiazhai I think @lucperkins fixed this in #426 . can you check?

**Comment by lucperkins** [comment]
@jiazhai @sijie Unfortunately I haven't been able to address this just yet, as it's pretty tricky in CSS. Hopefully I'll be able to tackle it next week.
