### ISSUE TITLE
No dockerhub image for 4.15.5

### ISSUE THREAD

**Issue by marcio-absmartly** [apache/bookkeeper#4170]
**QUESTION**

There is no image for 4.15.5 on dockerhub, did the build fail?

**Comment by eolivelli** [comment]
Thanks for reporting the problem, we missed to create the tag in git that triggers the build

the build now succeeded, can you please double check ?
https://hub.docker.com/layers/apache/bookkeeper/4.15.5/images/sha256-7217c5f50ef2531972914e451252b0ce5d1e169f58f743b5ac8b849e242b3d0c?context=repo
