### ISSUE TITLE
Bump Docker to use 4.5.0 binarary

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#418]
Since it is near to bk 4.5.0 release, would like to bump the docker image to use 4.5.0 binary.

in 4.4.0 binary, `bin/bookkeeper org.apache.zookeeper.ZooKeeperMain` will met issue 'Will not attempt to authenticate using SASL (unknown error)'.

**Comment by eolivelli** [comment]
I think that that message is normal for zk clients without auth. It is somehow scary but it is not a problem

**Comment by eolivelli** [comment]
I am ok with this change, it will be possible once we promote a rc to general availability

**Comment by zhaijack** [comment]
@eolivelli. Thanks for the comments. 
In our use case it is a problem. I have verified the zk binary that contained in bookkeeper-4.4.0, with command "bin/bookkeeper org.apache.zookeeper.ZooKeeperMain", the wanted operation could not success, such as the command `ls /` and `create /new_root_dir`.
