### ISSUE TITLE
[improve][docker] fix yaml and dockerfile

### ISSUE THREAD

**Issue by zwOvO** [apache/bookkeeper#4185]
**FEATURE REQUEST**
![image](https://github.com/apache/bookkeeper/assets/18533252/ef8194e6-7815-4dff-aa91-24300fbac6a5)

![image](https://github.com/apache/bookkeeper/assets/18533252/daff156f-f03f-49e3-b4d7-c7058f0e858b)

**Comment by lhotari** [comment]
This issue can be closed since the PR has been merged. /cc @hangc0276
