### ISSUE TITLE
Dockerfile: automatic the signature verification

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#419]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
currently, in the Dockerfile, we have to manually set the public Key, would like to make it automatic. 

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have

3. Provide any additional detail on your proposed use case for this feature.
currently, in the Dockerfile, we have to manually set the public Key, it is not very friendly when bump the version of binary files, e.g. from bk 4.4.0 to 4.5.0, we will have to set the public Key for bin-4.4.0.tgz and bin-4.5.0.tgz individually.

**Comment by caiok** [comment]
@jiazhai Are you sure that the public key used to sign the release packages vary from one version to another? I think that usually should not.

Anyway, I'm not sure that there is a simpler way to achieve this. When you create the image with that key you are saying that you and developers who approved that image trust that key and even if an attacker succeed in providing you a fake package at build time this package won't pass the validation.
If you for instance download that key somewhere (maybe at the same location that the packets) you substantially invalidate that precaution.

Have you already had an implementation idea for this proposal?

**Comment by sijie** [comment]
@caiok 

FYI

- the sign key will vary for every releases. the signing key is the release manager's pgp key.
- here is the verification process: http://www.apache.org/info/verification.html
- here is the bookkeeper's key file: https://dist.apache.org/repos/dist/release/bookkeeper/KEYS

**Comment by jiazhai** [comment]
@caiok @sijie Thanks for the info.  forget to mention, the PR was there: https://github.com/apache/bookkeeper/pull/420

**Comment by zhaijack** [comment]
After discussion in https://github.com/apache/bookkeeper/pull/420, manually provide the key is more security.
Would like to close this issue here. Thanks @caiok and @sijie
