### ISSUE TITLE
Replace the usage of PowerMock with Mockito in the Bookkeeper tests

### ISSUE THREAD

**Issue by lhotari** [apache/bookkeeper#4201]
[PowerMock](https://github.com/powermock/powermock/releases) is no longer maintained. The last release way in January 2020.
It should be replaced with Mockito. A similar replacement was done in Pulsar in these PRs:

- https://github.com/apache/pulsar/pull/14098
- https://github.com/apache/pulsar/pull/14250
- https://github.com/apache/pulsar/pull/17696

PowerMock / PowerMockito is holding back from upgrading to Mockito 4.11.0 . Mockito 4.11.x is the last version to support Java 8.
Getting rid of PowerMock will be needed for upgrading some other libraries for supporting newer JDK versions (Java 17 & Java 21).

**Comment by nodece** [comment]
Could you assign this issue to me?
