### ISSUE TITLE
HTTP 504 Gateway timeout

### ISSUE THREAD

**Issue by jyotirmoy112** [apache/bookkeeper#4242]
**BUG REPORT**
While removing subscription we are getting this error.
***Describe the bug***
Apache pulsar supports CLI commands and pulsarctl to perform some admin task ex. creating topics , subscription etc. but while performing those operation from a client node we saw 504 gateway timeout error most of the cases. while manually running those CLI commands from broker nodes it works successfully. 
pulsar admin commands or pulsarctl does not work properly from a client node. Below is the screenshot or error page. 
![image](https://github.com/apache/bookkeeper/assets/161158027/6f1fd2fe-21c9-43a7-8b4c-97c687237703)

***To Reproduce***
Please set up a client node and perform admin operation. It will come sometime when you have a heavy task to perform at a time. 

***Expected behavior***

The expected behavior should be it should not throw error 504 gateway timeout.  

***Screenshots***

***Additional context***

**Comment by shoothzj** [comment]
Refer to the description, maybe you should report this issue to Apache pulsar community. Feel free to reopen this issue. :)
