### ISSUE TITLE
Useless BookieCheckTask.

### ISSUE THREAD

**Issue by thetumbled** [apache/bookkeeper#4255]
We have listen for the changes of the list of available bookies and readonly bookies. Once changed, we will call `org.apache.bookkeeper.replication.Auditor#submitAuditTask` to start audit task.

But we have another perodic task for audit bookies.
`org.apache.bookkeeper.replication.Auditor#scheduleBookieCheckTask`

I doubt with the meaning of such a periodic task as we can get the notification as soon as we receive the event from zookeeper.

**Comment by shoothzj** [comment]
what if zookeeper shutdown ungracefully？what if notification lost？I think perodic would work will in this scenario. WDYT?

**Comment by thetumbled** [comment]
> what if zookeeper shutdown ungracefully？what if notification lost？I think perodic would work will in this scenario. WDYT?

Make sense, thanks for reply.
