### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by ahgbaa** [apache/bookkeeper#4386]
**QUESTION**

I want to ask a seemingly foolish question, but it does hinder my understanding of BookKeeper. After pulling down the code, there are many classes that cannot be found. I don't know how to solve this problem?How should problems like this be solved？
![e9449e3bd20ebd94f9f3b379b95499b](https://github.com/apache/bookkeeper/assets/89904773/263b5b0e-3c44-4a84-baf1-eb81e4ff6d76)
![a2de6b072ed8014e357812cfbbbc5ea](https://github.com/apache/bookkeeper/assets/89904773/1bc6f034-e7a8-4268-8830-d4af1b6aef14)
![01b38d60f8b5f9ee5eb2c1ee9d4bb9e](https://github.com/apache/bookkeeper/assets/89904773/5a895acf-8327-424f-b5b2-d52247554bbf)

**Comment by shoothzj** [comment]
It's generated by `protobuf-maven-plugin`, it will auto generated when `package` or `install`
