### ISSUE TITLE
4.17.0 tag is missing for apache/bookkeeper image on Docker Hub

### ISSUE THREAD

**Issue by khrisrichardson** [apache/bookkeeper#4444]
**QUESTION**

Can someone please trigger docker build/publish on Docker Hub for the release-4.17.0 tag? There was an intermittent issue when the tag was created: https://github.com/apache/bookkeeper/tree/release-4.17.0

> ci/dockercloud-stage (/docker/Dockerfile) - Your image failed to build in Docker Hub

According to the [Details link](https://hub.docker.com/redirect/?resource_uri=/api/audit/v1/action/a09c13a8-ecfa-4d1d-b03d-2c180f7e426d/) of that CI step

> {"error": "Our service is temporarily unavailable. We'll be back soon!"}

**Comment by shoothzj** [comment]
Well, I am willing to help, but I don't have ideas about how to retrigger this without a git tag. Should I run the script local in my pc? 
@eolivelli @dlg99 @nicoloboschi  Could you guys please give me some hint?

**Comment by eolivelli** [comment]
I can trigger the build but any committer can be added to the group that is able to trigger the build and see the logs.
@shoothzj please open an ASF INFRA JIRA ticket and ask to be added, please advertise on the dev@ mailing list

**Comment by eolivelli** [comment]
It seems that no tags for 4.17.0 and 4.17.1 have ever been built but the master docker image (nightly builds) is there.

I suggest to push a git SIGNED tag named 
4.17.0-docker and one  4.17.1-docker

**Comment by shoothzj** [comment]
@eolivelli 4.17.1's release is not complete. I can help push `4.17.0-docker` tag

**Comment by shoothzj** [comment]
@khrisrichardson Can you use `4.17.1` docker image? It has been successful released. I will take a look at `4.17.0` this night(UTC +8)

**Comment by zymap** [comment]
https://hub.docker.com/layers/apache/bookkeeper/4.17.0/images/sha256-8c81d383f4a92c28653be05f43b69951aa303e9e77d6d2ebf43bf6719bc8c207?context=repo

4.17.0 image out

**Comment by shoothzj** [comment]
@zymap Thanks for your help, close this issue.
