### ISSUE TITLE
Document Http Endpoint

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#449]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Http endpoint modules is introduced in #278 . We need to document this before 4.6.0 release.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*blocker* (mark this as blocker for 4.6.0 release)

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by jiazhai** [comment]
This is dup to #674, will close this one.
