### ISSUE TITLE
Port back recover related changes from twitter's branch

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#450]
In Distributedlog(https://github.com/apache/distributedlog/issues/150), we temp comment out RecoverCommand in tools/DistributedLogTool.java, because the needed support is not ready here.
We may need to do the porting work from twitter's branch during 4.6.0.

**Comment by eolivelli** [comment]
Is this an umbrella issue or it is just for a single port of code?

**Comment by sijie** [comment]
This is an umbrella issue.

**Comment by ivankelly** [comment]
@sijie @zhaijack are these the autorecovery changes that need to come in from the twitter branch (honouring placement policy etc)? Can we uncomment RecoverCommand now?
