### ISSUE TITLE
Error in downstream projects due to loopback address choosen by default event if not allowed and non-loopback address available

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#451]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
run tests of downstream project HerdDB (github.com/diennea/herddb)

- What did you expect to see?
tests running, bookie starting as expected

- What did you see instead?

```
java.net.UnknownHostException: Trying to listen on loopback address, localhost:3181 but this is forbidden by default (see ServerConfiguration#getAllowLoopback())
	at org.apache.bookkeeper.bookie.Bookie.getBookieAddress(Bookie.java:601)
	at org.apache.bookkeeper.proto.BookieNettyServer.<init>(BookieNettyServer.java:139)
	at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:98)
	at herddb.cluster.EmbeddedBookie.start(EmbeddedBookie.java:140)
	at herddb.server.Server.start(Server.java:327)
	at herddb.server.EmbeddedBookieTest.test_boot_with_bookie(EmbeddedBookieTest.java:99)

```
With the most recent commits before 4.5 release we changed something which makes the bookie select the loopback address.
This problem happens sometimes in downstream projects

**Comment by eolivelli** [comment]
it is related to #407 but the problem is not in the "localbookie" feature but it is affecting other projects

**Comment by eolivelli** [comment]
We should revert the behaviour to the previous and maybe release an hotfix ?  this  change can cause eventually problems in production environments

**Comment by sijie** [comment]
@eolivelli I don't think there is any behavior changed in 4.5.0. if you don't specify `listening interface`, it will use `default` to get default host. can you run both 4.4 and 4.5 on same machine and compare?

**Comment by sijie** [comment]
```
    /**
     * Get the IPAddress of the local host as a string.
     * This will be a loop back value if the local host address cannot be
     * determined.
     * If the loopback address of "localhost" does not resolve, then the system's
     * network is in such a state that nothing is going to work. A message is
     * logged at the error level and a null pointer returned, a pointer
     * which will trigger failures later on the application
     *
     * @return the IPAddress of the local host or null for a serious problem.
     */
    private static String resolveLocalHostIPAddress() {
        String address;
        try {
            address = InetAddress.getLocalHost().getHostAddress();
        } catch (UnknownHostException e) {
            LOG.warn("Unable to determine address of the host"
                    + "-falling back to \"" + LOCALHOST + "\" address", e);
            try {
                address = InetAddress.getByName(LOCALHOST).getHostAddress();
            } catch (UnknownHostException noLocalHostAddressException) {
                //at this point, deep trouble
                LOG.error("Unable to determine local loopback address "
                        + "of \"" + LOCALHOST + "\" " +
                        "-this system's network configuration is unsupported", e);
                address = null;
            }
        }
        return address;
    }
```

just fyi, if you address of local host can't be identified, it will use `localhost`. so please check your logs to see if you encountered this log statements.

**Comment by eolivelli** [comment]
@sijie I am really sorry, I apologize. I am using a new laptop and I did not test the project  with 4.4  version.
I will double check on monday at work and close the issue

**Comment by eolivelli** [comment]
With 4.4 the error is similar

**Comment by sijie** [comment]
yes. this situation is most likely related to your laptop environment. As suggested, if you want to reliably running tests, it is recommended to setAllowLoopback to true.

**Comment by sijie** [comment]
@eolivelli I removed the labels and marked it as `area/tests` for now. if you confirm this is a critical issue, please re-label them.

**Comment by eolivelli** [comment]
Closing as won't fix, it was a problem in by environment
