### ISSUE TITLE
Should this place be changed to tryReadLock()?

### ISSUE THREAD

**Issue by wodejiong** [apache/bookkeeper#4521]
https://github.com/apache/bookkeeper/blob/f148f6334d8810f0fd0fe76cb9541d126a770fb1/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/storage/ldb/SingleDirectoryDbLedgerStorage.java#L540

**Comment by xiezhx9** [comment]
I prefer `writeLock()` here

**Comment by shoothzj** [comment]
would you like to submit a PR?

**Comment by shoothzj** [comment]
After discussion with @xiezhx9, `readLock` is correct here. it controls writeCache object's rotation/switch, not the cache content. Thanks for submitting this issue, have fun!
