### ISSUE TITLE
Documentation: provide more specific info of Jekyll and Sass in site/README

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#454]
This is a TODO work in https://github.com/apache/bookkeeper/blob/master/site/README.md.
Here is a reference:
```
Tools

The site is built using Jekyll and Sass.

    I'll provide more specific info here later.  < ===
```

**Comment by ivankelly** [comment]
@zhaijack @lucperkins I don't think we need more info here. Modifying the site to add documentation is pretty easy given the instructions in the rest of the readme. If you're digging deeper, no amount of documentation will help. I suggest we just remove this comment.
