### ISSUE TITLE
TestTLS failures

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#462]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
https://builds.apache.org/job/bookkeeper-precommit-pullrequest/307/#showFailuresLink
contains test failure related with TestTLS

- What did you expect to see?
no ut errors.

- What did you see instead?
https://builds.apache.org/job/bookkeeper-precommit-pullrequest/307/#showFailuresLink

    org.apache.bookkeeper.tls.TestTLS.testTLSClientButOnlyFewTLSServers org.apache.bookkeeper.tls.TestTLS.testBookieAuthPluginDenyAccesstoClientWithoutTLSAuthentication
    org.apache.bookkeeper.tls.TestTLS.testClientWantsTLSNoServersHaveIt

**Comment by zhaijack** [comment]
@kishorekasi  @eolivelli , Would you mind help take a look at these failure？

**Comment by eolivelli** [comment]
I think that the problem is due to the changes to loadConfiguration but I am not sure I will check better as soon as possible

**Comment by sijie** [comment]
@eolivelli I have a fix for this. sending it out soon
