### ISSUE TITLE
mvn compile fail

### ISSUE THREAD

**Issue by Li-Haihui** [apache/bookkeeper#487]
Is this a question, feature request, or bug report?

**QUESTION**
In the bookkeeper_4.5.0 compilation process: Error occurred。

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project bookkeeper-stats-api: Fatal error compiling: invalid target release: 1.8 -> [Help 1]

**Comment by sijie** [comment]
@Li-Haihui : what is your java version? (run `java -version` to find it out)

"invalid target release: 1.8" means you are compiling using a javac version less than 1.8.

**Comment by Li-Haihui** [comment]
java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.1)

**Comment by sijie** [comment]
@Li-Haihui 

you need java8 to compile and run bookkeeper. you need to upgrade java version to 1.8.

**Comment by Li-Haihui** [comment]
ok,i will try来自我的华为手机-------- 原始邮件 --------主题：Re: [apache/bookkeeper] mvn compile fail (#487)发件人：Sijie Guo 收件人：apache/bookkeeper 抄送：Li-Haihui ,Mention @Li-Haihui
you need java8 to compile and run bookkeeper. you need to upgrade java version to 1.8.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apache/bookkeeper","title":"apache/bookkeeper","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/apache/bookkeeper"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sijie in #487: @Li-Haihui \r\n\r\nyou need java8 to compile and run bookkeeper. you need to upgrade java version to 1.8."}],"action":{"name":"View Issue","url":"https://github.com/apache/bookkeeper/issues/487#issuecomment-326544173"}}}

**Comment by Li-Haihui** [comment]
OK，now is success！

**Comment by sijie** [comment]
@Li-Haihui awesome!
