### ISSUE TITLE
Add a flag to not serialize `ctime` field

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#490]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Add a flag to not serialize `ctime` field.

This request is for DL bookkeeper version upgrade. Because twitter's bk version doesn't include this change, so any ledgers written by new bk version will fail to be read by old version. To simplify the upgrade story, it is good to allow not serialize `ctime` field.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*nice-to-have*

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by eolivelli** [comment]
Dropping the 4.5.1 label from this issue

// @sijie already agreed by email
