### ISSUE TITLE
Make an official bookkeeper docker image

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#498]
As discussed in the email, seems we need to make an official docker image, similar to [zookeeper’s](https://hub.docker.com/_/zookeeper/) or Flink's way.  

Here are some info:
[1] https://docs.docker.com/docker-hub/official_repos/
[2] https://github.com/docker-library/docs
[3] https://flink.apache.org/news/2017/05/16/official-docker-image.html

To achieve it, we may need to go through the official process, and open a dedicated repo for bookkeeper docker.

**Comment by zhaijack** [comment]
@caiok will handle this issue after discussion.

**Comment by eolivelli** [comment]
@sijie is there any way to assign this issue to @caiok ? 
on JIRA we had the ability to assign issue to contributors

**Comment by zhaijack** [comment]
@sijie , I recall you assigned issues to @caiok before. But seems I could not do it, Would you please help assign it again?

**Comment by sijie** [comment]
I think if @caiok make a comment here, we might be able to assign the issue to him. Otherwise, we don't have any way to assign issue to contributors outside of ASF organization.

**Comment by caiok** [comment]
@sijie @zhaijack Ok, let's see if the issue is now assignable to me

**Comment by eolivelli** [comment]
I still cannot assign  the issue to @caiok, maybe @sijie will be able

**Comment by jiazhai** [comment]
seem to me, not able to assign.

**Comment by sijie** [comment]
hmm I can't assign either.

**Comment by ivankelly** [comment]
Closing this issue. We have an image now, and improvements are being tracked in #335
