### ISSUE TITLE
BookKeeperDiskSpaceWeightedLedgerPlacementTest is flaky

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#503]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

run ci job

- What did you expect to see?

all tests should pass

- What did you see instead?

org.apache.bookkeeper.client.BookKeeperDiskSpaceWeightedLedgerPlacementTest is failing

https://builds.apache.org/job/bookkeeper-precommit-pullrequest/336/

**Comment by ivankelly** [comment]
The results no longer exist, so closing. If we find this to be flakey in future, we can reopen.
