### ISSUE TITLE
BP-15 New CreateLedger API

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#506]
Refer to BookKeeper Proposal 15 for a detailed description of this new feature
https://cwiki.apache.org/confluence/display/BOOKKEEPER/BP-15+New+CreateLedger+API

We are going to add a brand new API to manage ledgers using the Builder pattern.
Additionally we will introduce new interfaces to make it clear operations on ledgers, like WriteHandler and ReadHandler.
The new API will leverage CompletableFuture API

**Comment by sijie** [comment]
can you create an issue for adding documentation for the new API and mark it as a blocker? we need documentation to claim BP-15 is completed.
