### ISSUE TITLE
Port shared-resource-manager utilities from DistributedLog

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#517]
Try to port a few useful utilities from DistributedLog, to merge better DL and BK.

This is for introducing a shared resources manager for managing the common resources like scheduler/executor. This allows things like scheduler, timer shared between two different components. It manages reference counts of resources and tear down them when they don't need. It provides a clear way on managing resources.

**Comment by eolivelli** [comment]
Can you  a provide more background? 
I like that new code but I would like not to have generic code not used, bk is not a general purpose  library

**Comment by sijie** [comment]
I think this is for introducing a shared resources manager for managing the common resources like scheduler/executor. This allows things like scheduler, timer shared between two different components. It manages reference counts of resources and tear down them when they don't need. It provides a clear way on managing resources.

Jia, pls change the caption to reflect what are the changes.

Enrico, we are not making bk a general library. For better merging dlog and bk, it is making sense to put common utils in a common place, so it can be used across the board. Hope this make sense.

**Comment by eolivelli** [comment]
@sijie yep I was supposing that the goal was that (to merge better DL and BK)

I just pinged Jia to explain better the issue in order to make in clearer for people

I will give my +1 in the PR soon
