### ISSUE TITLE
Remote monitor JVM in bookkeeper-4.5.0

### ISSUE THREAD

**Issue by Li-Haihui** [apache/bookkeeper#519]
Is this a question, feature request, or bug report?

**QUESTION**

in there,if I want to used JMX to emote monitor JVM, should i use JMX Bean? is this the one way to solve this question? but i must change the code.like this.
Update JMX documentation #195 

if i changed this, is it work?

**Comment by sijie** [comment]
we removed JMX from bookkeeper in last release. StatsProvider takes the responsibility for exposing stats for monitoring. StatsProvider is a pluggable interface, you can use any popular metrics/stats collecting and reporting framework, such as statsd, prometheus. see http://bookkeeper.apache.org/docs/latest/admin/metrics/

**Comment by sijie** [comment]
@Li-Haihui is this still a question?

**Comment by ivankelly** [comment]
@Li-Haihui @sijie Closing this. We can reopen if there are further questions.
