### ISSUE TITLE
BookKeeper doesn't compile with oracle jdk

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#522]
This is a bug, though whether the bug is in oracle jdk or our code is unknown. 

To repro, download the oracle jdk, install it (I did so using java-package on debian 9), and run "mvn package -DskipTests".

This command should complete without error. Instead you get an error compiling bookkeeper-benchmark.
```
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ bookkeeper-benchmark ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /home/ivan/src/bookkeeper/bookkeeper-benchmark/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] An unknown compilation problem occurred
```

**Comment by eolivelli** [comment]
I am using oracle jdk with fedora, no problem

**Comment by sijie** [comment]
@ivankelly is this still an issue? we have travis CI covers both mac, linux and also openjdk and oraclejdk. didn't seem to be an issue on those CI jobs.

**Comment by ivankelly** [comment]
Not an issue. Dunno what was up with my setup.
