### ISSUE TITLE
UUIDs for bookies

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#545]
To be able to tell instances of a bookie apart we need some random unique token which is generated when the bookie is formatted. It should be stored in the cookie.

Whether we store this in the ledger metadata is an open issue.

**Comment by Ghatage** [comment]
@eolivelli This looks related to https://github.com/apache/bookkeeper/issues/2396. Perhaps we can close this after BP-41 is done.

**Comment by shoothzj** [comment]
BP-41 is done. bookie id lays in `ledgers/available`
