### ISSUE TITLE
Update website to deprecate JIRA workflow

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#546]
We should recommend only github for issues.

**Comment by ivankelly** [comment]
Also update the doap file.

https://issues.apache.org/jira/browse/BOOKKEEPER-806?jql=project%20%3D%20BOOKKEEPER%20and%20resolution%20%3D%20unresolved%20and%20status%20!%3D%20closed%20and%20(labels%20not%20in%20(iktriage0)%20or%20labels%20is%20empty)

**Comment by sijie** [comment]
This has been fixed by #558
