### ISSUE TITLE
Allow loading extra lifecycle components

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#547]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

recently we introduced lifecycle components in bookie server to provide a modular way for managing the components/services started by a bookie server. It would be good to allow loading extra lifecycle components by reflection. this is useful for managing dlog services.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*must-have*

3. Provide any additional detail on your proposed use case for this feature.

**Comment by jiazhai** [comment]
#548 is for the fix
