### ISSUE TITLE
Support Long-poll reads in new API

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#550]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
the new org.apache.bookkeeper.client.api.ReadHandle should support long-poll reads

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have

3. Provide any additional detail on your proposed use case for this feature.
it is needed in order to let applications which use the legacy API (like DistributeLog) switch to the new API

**Comment by jiazhai** [comment]
will do it.
