### ISSUE TITLE
Documentation for new API

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#553]
We need to document the new API on the website.
New documentation should at least cover:
- creating a BookKeeper client
- creating a ledger and writing to it
- reading from a ledger (no recovery)
- reading from a ledger with fencing
- deleting a ledger

a separate issue has been created for the update of the tutorial (#552)

**Comment by eolivelli** [comment]
Once committed this issue it would be good to drop https://cwiki.apache.org/confluence/display/BOOKKEEPER/API as it is incomplete and deals with legacy API

**Comment by sijie** [comment]
@eolivelli since you are the author of new API, can you please complete the documentation for this new API. We are supposed to complete all 4.6.0 tasks this week.

**Comment by eolivelli** [comment]
I will do my best.
Can you give some hint?
I think that a bunch of examples and a link to javadocs (how can I do this?) will be enough

**Comment by sijie** [comment]
There is already a page about ledger api - http://bookkeeper.apache.org/docs/latest/api/ledger-api/ you can add new api there.

**Comment by eolivelli** [comment]
great, I will add some paragraphs, as the new API is still "experimental" is it better to leave the old API on foreground, OK ?

**Comment by sijie** [comment]
@eolivelli we can only remove old API after we deprecate the old api.
