### ISSUE TITLE
Update credits.html page on website, drop references to JIRA 

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#558]
Page credits.html talks about JIRA, we moved to GitHub issue tracker

https://bookkeeper.apache.org/credits.html

**Comment by ivankelly** [comment]
Yes, in my backlog to update my affiliation. I'd prefer to do the JIRA reference stuff in a separate task.

**Comment by eolivelli** [comment]
yup, will change the description, I meant the JIRA part

**Comment by eolivelli** [comment]
Ops it is a duplicate of #546.
