### ISSUE TITLE
Ledger eviction should not impact write performance

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#566]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-1106

Reporter: Yiming Zang 

When read behind happens, it would quickly read bunch of ledgers, which will evict current active ledgers for writing from the ledger cache. with the ledger being evicted from cache, it would impact the write performance.

In order to address this issue, we should separate write FileInfo and read FileInfo in the cache.

**Comment by sijie** [comment]
This is fixed by #513
