### ISSUE TITLE
BookieDecommision Workflow

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#574]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-1029

Reporter: Charan Reddy Guttapalem @reddycharan

- LostBookieRecoveryDelay config param is stored in ZK
    - if LostBookieRecoveryDelay is reset to same value then it force triggers audit immediately
    - Added logic to trigger immediately or schedule pending audittask depending on the changed value in ZK
    - good number of testcases validating focetrigger/reschedluing audittask
    - added bookieshell command to get/set LostBookieRecoveryDelay from ZK
    - added bookieshell command to triggeraudit by resetting LostBookieRecoveryDelay
    - added decommissionbookie bkshell command, which validates the complete replication of ledgers stored in the bookie

### Comments from JIRA

---
*Hudson* 2017-07-07T13:50:48.980+0000

FAILURE: Integrated in Jenkins build bookkeeper-master #1808 (See [https://builds.apache.org/job/bookkeeper-master/1808/])
BOOKKEEPER-1028 and BOOKKEEPER-1029 (cguttapalem: [https://github.com/apache/bookkeeper/commit/29eb420f1cca07c1a3a7748ed7fbb8a5bc54f2fa])
* (edit) bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationException.java
* (edit) bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/ZkLedgerUnderreplicationManager.java
* (edit) bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerMetadata.java
* (edit) bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerChecker.java
* (edit) bookkeeper-server/conf/log4j.shell.properties
* (edit) bookkeeper-server/src/main/java/org/apache/bookkeeper/util/BookKeeperConstants.java
* (edit) bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java
* (edit) bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java
* (edit) bookkeeper-server/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
* (edit) bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/BookieShell.java
* (edit) bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LedgerUnderreplicationManager.java
* (add) bookkeeper-server/src/test/java/org/apache/bookkeeper/client/BookKeeperAdminTest.java

**Comment by sijie** [comment]
I think this has been resolved by #127
