### ISSUE TITLE
Ignore deleted ledgers

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#575]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-1026

Reporter: Matteo Merli @merlimat

There is some corner case in which deleted ledgers are failing to get replicated, while they should just be ignored.

https://github.com/yahoo/bookkeeper/commit/56a0947e0c4ae902468abc4a96e5842a7a0aee9b

**Comment by sijie** [comment]
This is already addressed by #146
