### ISSUE TITLE
Release underreplicated lock after errors

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#576]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-1025

Reporter: Matteo Merli @merlimat

There are some conditions in which the replication lock on some ledger is not being released, requiring manual intervention to bounce the replication work to let some other continue.

https://github.com/yahoo/bookkeeper/commit/850122ed56b9c3706cb44cce9f27989125b76e3a

**Comment by sijie** [comment]
This has been addressed by #1010
