### ISSUE TITLE
make MajorCompaction and MinorCompactions controlled by at least time of the day/day of the week

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#578]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-1005

Reporter: Andrey Yegorov @dlg99

MajorCompaction and Minor Compactions are strictly frequency based.
They should be at least time of the day based.

Ideally we should run longer compactions during low system load in background, and if the system load raises, reduce the compaction depending on the disk availability.
Simpler first step would be to schedule "deeper" compaction at the times of the day/days of the week with typically lower load. 
i.e. set major compaction threshold to 0.4 normally, 0.6 at night/weekdays and 0.8 at night/Saturday.

**Comment by ivankelly** [comment]
This is being implemented in #851

**Comment by sijie** [comment]
Closed it now due to lack of interest
