### ISSUE TITLE
change the bookieServer cmdline to pass any configuration property and system properties

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#580]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-985

Reporter: Enrico Olivelli @eolivelli

with  BOOKKEEPER-966 we have a better way to pass options from the command line.
A further enhancement will be to let the user pass any other configuration option and system property from the command line.
Something like
{code}
BookeServer -x option1=value1 -x option2=value2 -Djava.security.auth.login.config=jaas.conf
{code}

This change will enable to support new properties without changing the code of the CLI

**Comment by sijie** [comment]
@eolivelli are we still needing this? Can you just use -D?

**Comment by sijie** [comment]
Closed it since there is no activities about this requirement.
