### ISSUE TITLE
Open a Ticket for "Who is using Bookkeeper"

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#581]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-982

Reporter: Jia Zhai @jiazhai

As discussed, would like to create an always open issue "who is using Bookkeeper" on github.

Here is some example of other project:
[https://github.com/alibaba/RocketMQ/issues/1] 
[https://github.com/mgechev/angular-seed/issues/855]
[https://github.com/labstack/echo/issues/295]

**Comment by sijie** [comment]
@jiazhai not sure if we still need this. probably just close it?

**Comment by sijie** [comment]
Closed it as we don't need it.
