### ISSUE TITLE
ReplicationWorker should choose bookies from cluster rather than using local bookie

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#583]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-977

Reporter: Sijie Guo @sijie

currently replication worker uses local address for the target address. it has two problems:

1) if autorecovery is running separately, it doesn't work
2) it will volatile the placement policy

### Comments from JIRA

---
*Sijie Guo* 2017-07-28T00:03:42.073+0000

move replication related changes to 4.6.0

**Comment by sijie** [comment]
#596 is a related issue.
