### ISSUE TITLE
Provide an DCOS Universe package for bookkeeper

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#586]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-972

Reporter: Jia Zhai @jiazhai

Currently, the PR for this package is merged into main stream: https://github.com/mesosphere/universe
And the example PR is also merged into : https://github.com/dcos/examples

Maybe in next release of DCOS, we could use the bookkeeper package directly.

Left this ticket to tracking the following work left, such as the docker image automate update.
Since this version bookkeeper package use a fix version of bookkeeper docker, we need to handle automaticly "update the package as we release new versions"

**Comment by sijie** [comment]
@jiazhai what shall we do with this? were we planning to update the bookkeeper package in DC/OS when 4.5.0 is released?

**Comment by jiazhai** [comment]
@sijie mesosphere/universe#1544 has updated the BookKeeper package to version 4.5.1

**Comment by jiazhai** [comment]
This issue seems dup to #336. 
Original ticket  BOOKKEEPER-972 was fro tracking the first version of bookkeeper package, and as I could see, at least DC/OS 1.10 contains it. would like to close this issue.

**Comment by sijie** [comment]
Great work @jiazhai !

**Comment by sijie** [comment]
Can you send an email to dev@ list about this DCOS package upgrade?
