### ISSUE TITLE
command line options

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#589]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-953

Reporter: John Lonergan @Johnlon

Use more conventional patterns in usage warning messages ..

Eg  
{code}usage: listbookies  [-readwrite|-readonly] [-hostnames]{code}
ought to be 
{code}usage: listbookies  (-readwrite|-readonly) [-hostnames]{code}

.. if exactly one of -readwrite|-readonly are required as per the warning ...

{code}
$ bin/bookkeeper shell listbookies
20:23:17,808 ERROR One and only one of -readwrite and -readonly must be specified
listbookies: List the bookies, which are running as either readwrite or readonly mode.
usage: listbookies  [-readwrite|-readonly] [-hostnames]
 -h,--hostnames    Also print hostname of the bookie
 -ro,--readonly    Print readonly bookies
 -rw,--readwrite   Print readwrite bookies
{code}

There might be other instances so I suggest they are listed here and done in one go.

**Comment by ivankelly** [comment]
@sijie this will be handled automatically by jcommander in the new CLI, no?

**Comment by sijie** [comment]
Closed this since the new bkctl takes care of it.
