### ISSUE TITLE
Provide simple IP-filtered Auth Provider

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#592]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-936

Reporter: Enrico Olivelli @eolivelli

Since 4.4.0 we have introduced authentication. 
We can introduce a simple authentication provider which limit access to bookie data using the IP address of the client (it will affect inter-bookie connections too)

**Comment by sijie** [comment]
Closed this issue since there are already several Auth provider.
