### ISSUE TITLE
Enhanec Bookie Shell

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#597]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-905

Reporter: Venkateswararao Jujjuri (JV) @jvrao

Enhance Bookkeeper shell to perform following.
We may open sub-tasks for some of the following if needed.

- Add flush command to bookie shell
- Make bookie shell usable on dev box including using local bookie; so basically we must be able to run bookie specific commands even while using local bookie.
- Multiple formats for ExtentId in bk shell; input/output to take log/hex/uuid formats
- Spit out list of disk files, including index,journal,and ledger files
- enhance readlog command just to take a particular entryId and print that.

**Comment by sijie** [comment]
This issue has been addressed by multiple issues sent by @reddycharan. Close this master issue.
