### ISSUE TITLE
Document that BookKeeper servers will shutdown on losing quorum

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#598]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-882

Reporter: Lucas Bradstreet @lbradstreet

We have adopted BookKeeper as part of our state management in Onyx 0.8.0 http://www.onyxplatform.org. As part of testing Onyx 0.8.0 we have begun testing with Jepsen, and our first step was testing BookKeeper without any interaction with Onyx.

We have discovered that the BookKeeper servers automatically shutdown without retry upon losing a connection to a quorum of nodes, which is the expected behaviour according to the code.

It is not obvious from the link at http://bookkeeper.apache.org/ under "Documentation / Admin guide", that this is the expected behaviour.

I believe it would be beneficial if this was discussed in the admin documentation.

Cheers

### Comments from JIRA

---
*Sijie Guo* 2015-11-16T18:27:02.955+0000

[~lucas.bradstreet@onyxplatform.org] yup. will add that to admin page. btw, BOOKKEEPER-855 is the ticket to improve zookeeper session handling.

---
*Lucas Bradstreet* 2015-11-16T18:56:00.241+0000

Thank you Sijie. I'll keep an eye on BOOKKEEPER-855. We also use curator for ZooKeeper session retries within Onyx. Seems like a reasonable approach.

---
*Venkateswararao Jujjuri (JV)* 2016-03-16T18:06:59.320+0000

Do we still need to document this after addressing issue - BOOKKEEPER-855 (https://github.com/apache/bookkeeper/commit/92722ee9c34b069e23d1a87d7fc78256b8540268) ?

---
*Venkateswararao Jujjuri (JV)* 2016-03-16T18:07:47.458+0000

And if not, may be close this issue??

---
*Sijie Guo* 2016-11-03T23:27:33.950+0000

[~lucas.bradstreet@onyxplatform.org] 

Hello Lucas, I happened to read your blog post - http://www.onyxplatform.org/jekyll/update/2016/03/15/Onyx-Straps-In-For-A-Jepsening.html

I saw you did a jepsen test with bookkeeper. I am wondering do you have any plan to submit the report to aphyr or contribute your jepsen test with bookkeeper. It would be great if you can share the script and the community can work together to come up a full story of a jepsen test for bookkeeper.

Appreciate your response.

---
*Flavio Junqueira* 2016-11-04T13:34:40.117+0000

What is quorum referring to here, is it a zookeeper quorum?

---
*Sijie Guo* 2016-11-09T02:03:50.566+0000

[~fpj] I think he was referring the session expire

---
*Sijie Guo* 2016-11-09T02:03:53.666+0000

[~fpj] I think he was referring the session expire

---
*Lucas Bradstreet* 2016-11-09T06:59:38.483+0000

I've been travelling, apologies for the slow response. I'll spend a little time to fix up the jepsen test and will get back to you with a better report. 

---
*Sijie Guo* 2016-11-09T07:09:34.281+0000

[~lbradstreet] that will be very awesome! thank you in advance.

**Comment by sijie** [comment]
This is not-a-problem any more since 92722ee9c34b069e23d1a87d7fc78256b8540268
