### ISSUE TITLE
verify switching FlatLedgerManager to HierarchicalLedgerManager

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#599]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-878

Reporter: Sijie Guo @sijie

after BOOKKEEPER-438 is in, it is possible to switch FlatLedgerManager to HierarchicalLedgerManager. 

- we need to verify whether it works
- add test cases to cover these steps
- documentation about the steps

if this is verified, port BOOKKEEPER-438 back to 4.3.* branch to make it available.

### Comments from JIRA

---
*Sijie Guo* 2015-12-18T05:58:38.052+0000

[~eolivelli] I looked at this ticket. It is possible to switch from FlatLedgerManager to HierarchicalLedgerManager. But since the ledger path would be a bit difference between FlatLedgerManager and HierarchicalLedgerManager. This requires a bit code change to allow HierarchicalLedgerManager to read ledgers that were already created by FlatLedgerManager.

and the upgrade flow would be:

- upgrade all the bookies code first so the bookies understand both ledgers created by FlatLedgerManager and HierarhicalLedgerManager
- once all the bookies are upgraded, upgrade the reader who only read ledgers. so all the readers could understand the ledgers created by FlatLedgerManager and HierarchicalLedgerManager.
- upgrade writers' binary first (all the writers are still generating ledgers in FlatLedgerManager format).
- once all the writers understand the path for both FlatLedgerManager and HierarchicalLedgerManager, upgrade the configuration to generate ledgers by HierarchicalLedgerManager.

does that make senses to you?

And couple questions?

- do you want to move the ledgers that created by FlatLedgerManager to the HierarchicalLedgerManager?
- do you run writers separately from readers? or they are in same jvm process?

---
*Enrico Olivelli* 2015-12-18T12:53:53.619+0000

if it is possible we would like to preserve existing ledgers, but if it is not possible we can make otherway.

actually I tested that even dropping all the ledgers it is not possibile to switch because the Bookie does not boot if I change the LedgerManagerFactory

we are using bookkeeper for many purposes, for instance:
- state replication (using followers that tail active ledgers): so readers are on different JVMS, but readers can be stopped for some time
- a write-ahead-log:  reads are done only for recovery/replay of transactions, readers are new JVMs which are spawned for recovery

use wrote "This requires a bit code change to allow HierarchicalLedgerManager to read ledgers that were already created by FlatLedgerManager.", so a new implementation and release (probabily 4.3.3) is needed ?

thank you

---
*Enrico Olivelli* 2015-12-18T12:53:54.699+0000

if it is possible we would like to preserve existing ledgers, but if it is not possible we can make otherway.

actually I tested that even dropping all the ledgers it is not possibile to switch because the Bookie does not boot if I change the LedgerManagerFactory

we are using bookkeeper for many purposes, for instance:
- state replication (using followers that tail active ledgers): so readers are on different JVMS, but readers can be stopped for some time
- a write-ahead-log:  reads are done only for recovery/replay of transactions, readers are new JVMs which are spawned for recovery

use wrote "This requires a bit code change to allow HierarchicalLedgerManager to read ledgers that were already created by FlatLedgerManager.", so a new implementation and release (probabily 4.3.3) is needed ?

thank you

---
*Sijie Guo* 2015-12-19T01:22:20.548+0000

> actually I tested that even dropping all the ledgers it is not possibile to switch because the Bookie does not boot if I change the LedgerManagerFactory

it has to change the LedgerManagerFactory.class recorded in zookeeper.

> use wrote "This requires a bit code change to allow HierarchicalLedgerManager to read ledgers that were already created by FlatLedgerManager.", so a new implementation and release (probabily 4.3.3) is needed ?

yes. I needed to add a bit code to allow a smooth upgrade. and that requires a new release 4.3.3. does that work for you? I am starting the code change.

---
*Sijie Guo* 2015-12-19T01:22:26.892+0000

> actually I tested that even dropping all the ledgers it is not possibile to switch because the Bookie does not boot if I change the LedgerManagerFactory

it has to change the LedgerManagerFactory.class recorded in zookeeper.

> use wrote "This requires a bit code change to allow HierarchicalLedgerManager to read ledgers that were already created by FlatLedgerManager.", so a new implementation and release (probabily 4.3.3) is needed ?

yes. I needed to add a bit code to allow a smooth upgrade. and that requires a new release 4.3.3. does that work for you? I am starting the code change.

**Comment by sijie** [comment]
I don't think we are going to support upgrading from flat manager to hierarchical manager. we should consider removing flat manager at all. closing this issue for now and will open a new open to discuss removing flat manager.
