### ISSUE TITLE
Provide a configuration option to set a fixed BookieID

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#600]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-875

Reporter: Enrico Olivelli @eolivelli

In Bookkeeper 4.3.x there are two ways of configuring the BookieID, that is using an IP address or using the hostname (useHostNameAsBookieID). There is also an option to force the use of a specific network interface.

In environments with many IP addresses both of the two options can lead to an undeterministic behaviour.

Another useful option would be to set explicitly a "BookieID".
I have to usecases:
- network configuration of the machine changes, but I want to preserve bookie data without recovery
- bookie data is to be moved to another machine (that is somehow similar the the first case)

**Comment by sijie** [comment]
This has been addressed by #373
