### ISSUE TITLE
provide a simple way to compress the content in each Entry of EntryLogger

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#602]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-865

Reporter: Jia Zhai @jiazhai

This issue is an enhancement, it tries to provide a simple way to compress the content in each Entry of EntryLogger. 
By this enhancement, it will save a lot of disk space for the logs, under the condition that contents is large in Entry.

### Comments from JIRA

---
*Jia Zhai* 2015-10-10T14:38:33.390+0000

try to provide a patch.

---
*Hadoop QA* 2015-10-10T17:50:24.207+0000

Testing JIRA BOOKKEEPER-865

Patch [BOOKKEEPER-865.patch|https://issues.apache.org/jira/secure/attachment/12765988/BOOKKEEPER-865.patch] downloaded at Sat Oct 10 17:12:26 UTC 2015

----------------------------

{color:green}+1 PATCH_APPLIES{color}
{color:green}+1 CLEAN{color}
{color:green}+1 RAW_PATCH_ANALYSIS{color}
.    {color:green}+1{color} the patch does not introduce any @author tags
.    {color:green}+1{color} the patch does not introduce any tabs
.    {color:green}+1{color} the patch does not introduce any trailing spaces
.    {color:green}+1{color} the patch does not introduce any line longer than 120
.    {color:green}+1{color} the patch does adds/modifies 1 testcase(s)
{color:green}+1 RAT{color}
.    {color:green}+1{color} the patch does not seem to introduce new RAT warnings
{color:green}+1 JAVADOC{color}
.    {color:green}+1{color} the patch does not seem to introduce new Javadoc warnings
{color:green}+1 COMPILE{color}
.    {color:green}+1{color} HEAD compiles
.    {color:green}+1{color} patch compiles
.    {color:green}+1{color} the patch does not seem to introduce new javac warnings
{color:green}+1 FINDBUGS{color}
.    {color:green}+1{color} the patch does not seem to introduce new Findbugs warnings
{color:red}-1 TESTS{color}
.    Tests run: 955
.    Tests failed: 1
.    Tests errors: 3

.    The patch failed the following testcases:

.      testSimpleChat(org.apache.hedwig.jms.BasicJMSTest)

{color:green}+1 DISTRO{color}
.    {color:green}+1{color} distro tarball builds with the patch 

----------------------------
{color:red}*-1 Overall result, please check the reported -1(s)*{color}

The full output of the test-patch run is available at

.   https://builds.apache.org/job/bookkeeper-trunk-precommit-build/959/

---
*Sijie Guo* 2015-10-16T04:55:12.945+0000

compressing an single entry might not help a lot. I think we should think on compressing multiple entries. we should think about how to provide a compressed buffered file channel. 

---
*Jia Zhai* 2015-10-20T11:30:13.368+0000

Yes. That is the next step. 
This compressing way, which handle each single log entry, also saves a lot of space if the content of each entry is big.

**Comment by sijie** [comment]
This is a duplication of #627
