### ISSUE TITLE
Enhance client API

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#604]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-860

Reporter: Venkateswararao Jujjuri (JV) @jvrao

Today's BK client API generates entryId and LedgerHandle for the caller.
While this is very convenient and makes the life of caller very simple and easy,
this model may not be very suitable where application would like to have 
better control.

In order to facilitate applications/users of BK aspiring to have more control
following enhancements are proposed for BK client API:
 
- API enhancement to accept entryID:
Enhance BK client API to pass entryId as an input and the caller must guarantee the following:
    * entryIds are never duplicated
    * entryIds are sequential starting from 0.
    * entryIds have no holes.

- API enhancement to accept LedgerHandle
Applications are allowed to pass-in ledgerId  provided:
  * ledgerId is unique within the cluster. 
  * Or even better, if using GUID (128 bit) virtually guarantees universal
     uniqueness.  
   * Need to bypass current ledgerId generation logic. 

- Allow multiple entities (threads/processes) write to the ledger as long as
   there is only one writer at the given instance of time.

- Currently ledgerHandle interface accepts byteArray as input, but sockets 
  use byteBuffer. We will add additional functions to the new classes to 
  accept both byteBuffers and byteArrays.

- Sijie suggested to create a new classes that extents existing classes to accept LedgerId and entryId as inputs.This avoids any confusion with existing interfaces, and makes it explicit.

### Comments from JIRA

---
*Venkateswararao Jujjuri (JV)* 2015-07-27T17:06:36.815+0000

How do I assign it to myself? 

---
*Ivan Kelly* 2015-07-27T19:13:00.243+0000

I had to add you as a contributor to the project before the issue could be assigned to you.

This sounds great. It touches on a couple of things I had wanted to do with bk for a while. A few questions.

1. How are you planning to ensure that only one writer exists at any instance in time?
2. Since you are reopening a ledger for writing, how do old entries get cleaned up.

Is this preexisting work or planned work? If the api doesn't already exist, I would suggest having a complete break from ledgerhandle.

---
*Venkateswararao Jujjuri (JV)* 2015-07-27T21:30:14.359+0000

Thanks a lot for your quick response.

#1
I would like to leave it to the user/application to enforce. This is the requirement of the interface. 

#2
Plan is not to reopen rather open handle is shared by multiple threads.

This is all planned work. Can you please tell me more on what do you mean by "complete break form ledgerhandle"? 

Thanks,
JV

---
*Ivan Kelly* 2015-07-28T07:26:10.800+0000

Ah ok. What I had in my head was different. What I thought you wanted to do was make it so that when a resource that needs a log is created, only one ledger is ever used, and when ownership of the resource changes, the new owner would reopen the ledger, etc.

What is the usecase that you need these features for?

What I meant regarding the "complete break" is that, since you are starting an API from scratch, the new API doesn't need to resemble ledger handle at all. IMO, there are a lot of mistakes in the LedgerHandle api, but they're the kind of thing you only see 
when you've built it and used it for a while. A new api is a chance to start fresh.

---
*Sijie Guo* 2015-07-29T05:40:23.576+0000

[~ikelly] could you be more specific about what are the mistakes in current ledger handle api? are those coding style mistakes or semantic mistakes?

---
*Sijie Guo* 2015-07-29T06:26:07.302+0000

[~jujjuri][~ikelly]

I think the requirements here mostly focus on giving flexibility to clients on controlling entry id and ledger id. It doesn't change the semantic and ordering guarantee that current bookkeeper provides. so I would suggest doing as below:

*API*

- providing a new interface about 'ledger handle' on allowing accepting entry id. (I don't have a good name for it right now. I will use WriteLedgerHandle for right now)
{code}
public interface WriteLedgerHandle {

    // we could use guava's listenable future for new api, or just using existing AddCallback is okay too.
    ListenableFuture<Void> addEntry(long entryId, ByteBuffer data);

}
{code}

- add a new method in BookKeeper to allow creating a ledger with passing in ledger id.
{code}
ListenableFuture<WriteLedgerHandle> createWriteLedgerHandle(int ensSize, int writeQuorumSize, ...);
{code}

*Semantic*

for the entry id, you should reuse current lac and ordering guarantee logic. it is easily to prevent duplication by checking lac and pending entries in the client, which it could reject any add with duplicated entry id. it is hard to enforce starting from zero and no holes in the implementation, application takes the responsibility of the enforcement.

for the ledger id, BOOKKEEPER-438 is already working on moving ledger id generation out of LedgerManager interface. it would be easily to allow passing in ledger id after that. Since the ledger manager implementation is already prevent creating ledger with duplicated ledger id, so it should be good from semantic perspective.

*Tasks*

in order to achieve that, the jira could be break down as following sub-tasks:

- BOOKKEEPER-438 (for moving ledger id generation out of ledger manager)
- Support creating a ledger with pass-in ledger id (it might change the LedgerCreateOp to take ledger id. and move the ledger id generation out of LedgerCreateOp to BookKeeper on #createLedger)
- Add the new class of WriteLedgerHandle to allow accepting pass-in entry id. (This might require bunch of code cleanup in LedgerHandle, such moving pending entries management, lac management to a separated class that could be re-used by LedgerHandle and WriteLedgerHandle)

---
*Ivan Kelly* 2015-07-29T09:03:48.017+0000

{quote}could you be more specific about what are the mistakes in current ledger handle api? are those coding style mistakes or semantic mistakes?{quote}
It's more stuff that I would do differently now having had experience actually using the api to build stuff. What follows is a list of things I'd do different now.

- requiring a passwd and digest type when creating a ledger; It's not real security, and just means you need to define a constant for passwd. There should be sensible defaults.
- having more than 1 digest type
- over emphasis on striping (ensemble > write quorum). It's much better to have write quorum equal to ensemble in most cases, and ack quorum one smaller.
- many different callback types. One using generics would mean less to remember when implementing.
- using callbacks at all. ListenableFuture or rx Observables would make more concise code at this stage.
- context objects for callbacks.
- exposure of netty socket channel factory in constructor.
- use of Enumeration for readEntries
- having reading and writing on the same handle. Users generally don't want to be both at the same time.
- using byte[] over ByteBuffer
- reads are non-streaming. You have to ask for N entries. Most people go for 0-LAC, because it requires the least logic. Will blow up your memory if the ledger is large.
- in general, ledger handle is far too primative to be useful. For creating a log for a resource you need to implement a lot of complex code, especially if you want it to be non-blocking.

For the last one, I had been working on an higher level api, and had actually mostly implemented [1], but then I left yahoo, so I dropped it, as I no longer had a prod usecase. It really should be driven by someone with a prod usecase.

[1] https://github.com/ivankelly/bookkeeper/tree/public-ledgerset, see ledgerset submodule.

---
*Sijie Guo* 2015-07-29T23:11:33.315+0000

    > requiring a passwd and digest type when creating a ledger; It's not real security, and just means you need to define a constant for passwd. There should be sensible defaults.

+ 1 on removing passwd. it is useless.

    > having more than 1 digest type

+ 1 on that

    > over emphasis on striping (ensemble > write quorum). It's much better to have write quorum equal to ensemble in most cases, and ack quorum one smaller.

that is our take in Twitter too. we only use ensemble size == write quorum size. as it is hard to do efficient long poll when stripping.

    >  many different callback types. One using generics would mean less to remember when implementing.
    > using callbacks at all. ListenableFuture or rx Observables would make more concise code at this stage.
    > context objects for callbacks.

I am for ListenableFuture from guava

    >  exposure of netty socket channel factory in constructor.

Using builder for bookkeeper. It doesn't seem to be problem. Especially for resource management perspective, it would good to share channel factory in a service.

    > use of Enumeration for readEntries

+1 

    > having reading and writing on the same handle. Users generally don't want to be both at the same time.

there are use cases that need reading data of a writing ledger handle. but I agree it is not clear from interface perspective.

    > reads are non-streaming. You have to ask for N entries. Most people go for 0-LAC, because it requires the least logic. Will blow up your memory if the ledger is large.
    > in general, ledger handle is far too primative to be useful. For creating a log for a resource you need to implement a lot of complex code, especially if you want it to be non-blocking.

I'd for keeping the ledger handle as a primitive on readings. the control on how to streaming, reading-ahead or batching, should be done in a higher level library/wrapper. enforcing streaming in the primitive limits the flexibility on how people use it.

With this client API enhancement, we should also refactor the code in client side and deprecate things that we need to deprecated.

---
*Venkateswararao Jujjuri (JV)* 2015-09-01T15:17:30.877+0000

I have a patch for the portion of passing in entryId. Should I upload as part of this issue? or open a sub task/issue? Please advise.

**Comment by sijie** [comment]
this task has completed as `LedgerHandleAdv`. Close it.
