### ISSUE TITLE
Fix default value of logSizeLimit

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#605]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-856

Reporter: Flavio Junqueira @fpj

When I run ./bookkeeper bookie, I get an error complaining about the value of the variable:

{norformat}
2015-05-24 14:14:01,196 - ERROR - [main:BookieServer@289] - Malformed configuration file: /home/fpj/code/bookkeeper-4.3.1/bookkeeper-server/conf/bk_server.conf
org.apache.commons.configuration.ConfigurationException: Entry log file size should not be larger than 1073741824
{noformat}

The parameter is commented out by default, so the fix is to bring it back in and set an appropriate value.

**Comment by sijie** [comment]
we need to fix the default value in `bk_server.conf`

**Comment by sijie** [comment]
@fpj are you able to provide a fix for this? otherwise I can take it.

**Comment by ivankelly** [comment]
@sijie @fpj this is already fixed. 

Was only an issue in 4.3.1 & 4.3.2.

https://github.com/apache/bookkeeper/blob/a226dbedff03102291648df3a60e78a2c85ae65f/tests/docker-all-versions-image/scripts/update-conf-and-boot.sh#L28

**Comment by sijie** [comment]
@ivankelly are you sure - https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/conf/bk_server.conf#L418 ?

**Comment by ivankelly** [comment]
@sijie yup, you fixed it :)
https://github.com/apache/bookkeeper/commit/10cab08d0a8b4ca4b182554dee95834dc42175d2

The conf file needs an update though. Created a PR
