### ISSUE TITLE
Use integer for entry log id

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#606]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-853

Reporter: Sijie Guo @sijie

As the format of position (including log id and position) limitation, it'd better to use integer for entry log id rather than long.

### Comments from JIRA

---
*Ankur Garg* 2015-07-08T04:43:40.600+0000

Thanks Flavio .

Please assign https://issues.apache.org/jira/browse/BOOKKEEPER-687  this as
well to me .

Will submit a patch in day or two.

Thanks
Ankur

On Wed, Jul 8, 2015 at 12:14 AM, Flavio Junqueira (JIRA) <jira@apache.org>

---
*Sijie Guo* 2015-07-08T06:27:40.799+0000

You should be able to assign to yourself now.

- Sijie

On Tue, Jul 7, 2015 at 9:42 PM, Ankur Garg <ankurgarg198611@gmail.com>

---
*Ankur Garg* 2015-07-17T10:38:23.385+0000

[~sijie@apache.org] ..Should LedgerId be converted to int? Please suggest 

---
*Sijie Guo* 2015-07-21T01:31:08.222+0000

[~agarg1986] no you can't convert ledger id. we could only convert entry log id, since it won't be larger than 2^32

---
*Sijie Guo* 2016-03-14T05:54:10.073+0000

[~agarg1986] what is the status of this?

---
*Sijie Guo* 2017-07-17T21:32:38.843+0000

removed it from 4.5.0 and unassigned since it has been inactive for a while.

**Comment by eolivelli** [comment]
@ivankelly why did you assign this to me ?

**Comment by eolivelli** [comment]
Maybe the commit message was wrong for another patch

**Comment by eolivelli** [comment]
this issue is to be fixed and reopened

**Comment by eolivelli** [comment]
@ivankelly fixed

**Comment by ivankelly** [comment]
@eolivelli The commit title was wrong on #660

**Comment by shoothzj** [comment]
I think now entryId is long. Close this issue.
