### ISSUE TITLE
Need a tool to upgrade bookie cluster that has empty instance id

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#608]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-825

Reporter: Charles X 

after introducing instance id, bookkeeper doesn't provide a tool to upgrade existing clusters to have a valid instance id.

the tool is useful, when you operate multiple bookkeeper clusters and want to move bookies around, you could use 'instanceid' to prevent any bad admin operation. without instanceid, it provides a back hole to break data integrity.

**Comment by shoothzj** [comment]
Apache BookKeeper has introduced `instance id` for many than seven years. I think we can close this issue now. cc @eolivelli
