### ISSUE TITLE
Make bookie recovery work with recovering multiple bookies

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#612]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-818

Reporter: Sijie Guo @sijie

Make recovery tool work with multiple bookies so we could recover bookies inside ensemble at one time call. so we don't need to run the tool multiple times when we want to recover multiple bookies

### Comments from JIRA

---
*Sijie Guo* 2017-07-28T00:03:08.816+0000

move replication related changes to 4.6.0

**Comment by sijie** [comment]
#641 address the core issue. I need to integrate this in the tool. I will do this for `4.6.0`.
