### ISSUE TITLE
Bookie: LRU FileInfo Eviction Policy

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#613]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-817

Reporter: Sijie Guo @sijie

currently ledger cache used a FIFO mechanism to evict file info, it is not efficient. it'd better to adopt guava cache for file info cache.

### Comments from JIRA

---
*Ankur Garg* 2015-07-31T18:08:43.178+0000

Sijie , 

If this is not too much on priority and still needed . I would like to investigate and work on this .

Let me know what you think.

---
*Ankur Garg* 2015-07-31T18:10:29.720+0000

In case you are working on this or have a partial patch ready , I can take something else to work on.

---
*Sijie Guo* 2015-07-31T18:45:49.957+0000

we have a patch available in Twitter's branch. I will try getting one up this week.

---
*Venkateswararao Jujjuri (JV)* 2016-03-15T16:37:40.160+0000

+1 ; this looks like a good optimization.

---
*Sijie Guo* 2017-07-25T00:21:35.955+0000

Move this out of 4.5.0. [~yzang] will help port changes regarding the ledger cache improvements later on.

**Comment by sijie** [comment]
This issue is already addressed by #513
