### ISSUE TITLE
StatsLogger doesn't cache counters/stats-loggers

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#615]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-812

Reporter: Charles X 

Currently the stats providers implementation doesn't provide caching ability for counters/stats loggers for different metrics. if the underlying stats library (e.g. code hale, ostrich) doesn't provide that, the client would end up creating different instances for same metric name, which would introduce bad gc behavior.

it would be better that bookkeeper-stats-provider could address this in high level, rather than ask individual stats provider implementing similar caching behavior.

**Comment by sijie** [comment]
This is already addressed by apache/bookkeeper#fc51f73cbc9cdaae9876bc08cafa3e7a80826207
