### ISSUE TITLE
Document updatecookie and updateledgers admin tool sequence

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#616]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-807

Reporter: Rakesh R @rakeshadr

None

### Comments from JIRA

---
*Sijie Guo* 2016-03-14T05:56:28.758+0000

ping [~rakesh_r]

---
*Sijie Guo* 2017-06-22T00:31:41.915+0000

We should include the documentation for these commands in 4.5.0 release.

---
*Sijie Guo* 2017-07-25T00:50:22.930+0000

Defer this to new documentation.

---
*Sijie Guo* 2017-07-27T23:58:27.854+0000

Move this as a separate 'documentation task'

**Comment by sijie** [comment]
This already documented at http://bookkeeper.apache.org/docs/latest/reference/cli/
