### ISSUE TITLE
64-bit Ledger Id Support for MSLedgerManager

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#623]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-591

Reporter: Jiannan Wang 

Currently, MSLedgerManager use String.format("%010d", id) as the key for ledger metadata management. We need to extend it to support 64-bit, backward compatibility should also be taken into account.

### Comments from JIRA

---
*Sijie Guo* 2013-11-10T22:23:34.444+0000

moved to 4.4.0

---
*Venkateswararao Jujjuri (JV)* 2016-03-15T16:54:02.634+0000

Anyone working on this? We have a patch that is currently not given to community on this and we will be happy to push it forward. [~reddycharan18@gmail.com]

**Comment by sijie** [comment]
This has been implemented.
