### ISSUE TITLE
It would be better to remove bookie related data from ZooKeeper after bookie recover.

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#624]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-450

Reporter: Sijie Guo @sijie

Currently we had some bookie related data stored in ZooKeeper liked cookie. When we run BookKeeperAdmin to manually recover a bookie, it would be better to remove its related bookie data from ZooKeeper after recover successfully. otherwise, its zombie data would be still in ZooKeeper even we retired that bookie node.

**Comment by sijie** [comment]
This has been implemented with '-deleteCookie' in recovery command.
