### ISSUE TITLE
Zombie ledgers, how to deal with them?

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#625]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-449

Reporter: Sijie Guo @sijie

Currently, when acquiring topic or changing ledgers for a topic, hub server created ledger first and updated ledger ranges later. if hub server crashed between created ledger and update ledger ranges. the created ledger would become a zombie.

### Comments from JIRA

---
*Ivan Kelly* 2017-10-09T09:46:53.256+0000

This exists for all implementations where we build a log. We should consider how to deal with this.

**Comment by shoothzj** [comment]
I think it should be processed by roles like `hub server`(like Apache Pulsar Project?). I also invented a tools for cleaning zombie ledger in Apache Pulsar project. If you have any thoughs, feel free to reopen this issue.
