### ISSUE TITLE
Add checksumming for ledger index files

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#626]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-164

Reporter: Sijie Guo @sijie

now bookie ledger index files lacks checksumming to prevent truncation/corruption. if a ledger index file is truncated, the ledger index file still works but responds wrong response when reading last confirmed.

### Comments from JIRA

---
*Flavio Junqueira* 2012-03-13T11:06:48.353+0000

are we fixing this for 4.1.0?

---
*Sijie Guo* 2012-03-14T00:54:29.609+0000

sorry, I haven't finished this one. since it's an improvement to make system more robust, not a blocking issue. I think we can move it to 4.2.0.

---
*Flavio Junqueira* 2012-03-14T08:50:01.554+0000

Thanks, Sijie, marking it for 4.2.0.

**Comment by sijie** [comment]
Bump the priority to 4.8.0

**Comment by shoothzj** [comment]
closed by no update, feel free to reopen it.
