### ISSUE TITLE
Client backpressure

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#628]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-36

Reporter: Flavio Junqueira @fpj

The way we currently throttle on the client is by counting the number of outstanding operation on LedgerHandle, and having the application select what an appropriate value is. This is not a good way of doing it because the application has to guess what a good value is. We need to implement some form of backpressure instead to make sure we throttle only when the system is saturated. 

### Comments from JIRA

---
*Flavio Junqueira* 2011-10-10T21:51:23.375+0000

We might want to do it by bytes instead of number of requests. Also, throttling is currently done per ledger handle and not overall.

**Comment by dlg99** [comment]
I think this is covered in fix to https://github.com/apache/bookkeeper/issues/1086 see https://github.com/apache/bookkeeper/pull/1088

**Comment by sijie** [comment]
As commented above, this has been covered and fixed.
