### ISSUE TITLE
AuditorLedgerCheckerTest intermittent failures

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#629]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-1062

Reporter: Matteo Merli @merlimat

A couple of tests in {{AuditorLedgerCheckerTest}} keep failing from time to time on Jenkins builds, irrespective of the PR changes.

Example:
{noformat}
org.apache.bookkeeper.replication.AuditorLedgerCheckerTest.testReadOnlyBookieExclusionFromURLedgersCheck[4]
org.apache.bookkeeper.replication.AuditorLedgerCheckerTest.testReadOnlyBookieShutdown[4]
{noformat}

{noformat}
java.lang.AssertionError: latch should not have completed
	at org.apache.bookkeeper.replication.AuditorLedgerCheckerTest.testReadOnlyBookieExclusionFromURLedgersCheck(AuditorLedgerCheckerTest.java:283)
{noformat}

### Comments from JIRA

---
*Matteo Merli* 2017-05-10T21:45:05.305+0000

Example from https://builds.apache.org/job/bookkeeper-master-git-pullrequest/364/

---
*Sijie Guo* 2017-07-25T00:22:19.317+0000

Moved this out of 4.5.0 

---
*Robert Joseph Evans* 2017-10-12T19:44:55.614+0000

I have been debugging this and think I have found what the issue is.

When the Auditor runs it is looking at both the available bookies and the read only bookies.

https://github.com/apache/bookkeeper/blob/3ede9c6c507aa93432757c4f1fe47c538fa83e34/bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java#L431-L432

Admin gets the available bookies by going directly to ZK and reading the list.

https://github.com/apache/bookkeeper/blob/3ede9c6c507aa93432757c4f1fe47c538fa83e34/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieWatcher.java#L136-L149

But the ReadOnlyBookies just return some cached state.

https://github.com/apache/bookkeeper/blob/3ede9c6c507aa93432757c4f1fe47c538fa83e34/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookieWatcher.java#L151-L153

That is set by a combination of a ZK watcher and a callback.

The issue here is that they can get out of sync, and when they do get out of sync a read only bookie can be marked as lost, which is what is happening in this test.

Watchers for ZK are not guaranteed to be fired, and even when they are fired, which is most of the time it can take some time for the event to propagate.

There is also an issue with the test, or possibly with my understanding of the test, where it will pause for up to 5 seconds waiting for the auditor to run and mark something as under replicated.  But the auditor is not configured to run every 5 seconds, but every 24 hours.  I think the only way this works is because the auditor runs once at startup, and hopefully that is after the test finishes marking the node as read only.  If it ran too soon the test would  fail because it would never mark the ledger as under replicated.

I have made 2 changes to the test on my branch where it now reads the read only bookies directly from ZK and where it forces the audits to run and complete before going on with the test.  After that I have been able to run the test 23 times in a row with no failures (previously the longest  I saw without failures was 8, and that was I forced the audits to run at specific times).

I am happy to put up a pull request but I am not sure of all of the consequences of getting the read only bookies directly form ZK, and I would love some help if someone can offer it.  Simply because it might have a big performance impact, especially when the audit does not run that frequently and a bookie going read only is even less frequent, and in the absolute worst case it would mean that the auditor replicates the ledgers for a bookie when it should not have.

---
*Sijie Guo* 2017-10-12T21:24:58.819+0000

[~revans2] the analysis looks good to me. #getReadOnlyBookies is the problem of race conditions.

I think you can change the behavior of #getReadOnlyBookies, it should be same #getBookies. However there is one place you might need to look is in BookieWatcher, I think #getReadOnlyBookies was used in zookeeper callback (That is the reason that why #getReadOnlyBookies is reading the cached value). So adding an opt in method seems fine for me now.

---
*Robert Joseph Evans* 2017-10-12T21:49:55.866+0000

[~sijie@apache.org],

Sounds good I will add some javadocs to the alternate method for read only bookieas and try to come up with a better name for it.

**Comment by sijie** [comment]
Closed this issue since it is an old issue migrated from JIRA.
