### ISSUE TITLE
Remove Bookie global ZK Instance

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#630]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-1006

Reporter: Govind Menon 

Bookie has had a Zookeeper client for the whole process up to now. This
is only ever used in garbage collection though. This change moves the
creation and usage of the zookeeper client to the garbage collection
thread. It now creates a new zookeeper client for each GC iteration, and
tears it down afterwards. This means that if there is a problem with the
zookeeper connection, it will only exist for one iteration of garbage
 collection.

This work was originally done by Ivan Kelly and I am just pushing it back to open source

### Comments from JIRA

---
*Robert Joseph Evans* 2017-02-14T21:27:20.393+0000

[~mmerli],

Could you assign this to [~govindmenon]?

---
*Matteo Merli* 2017-02-14T22:25:17.736+0000

[~revans2] Sure, done

---
*Robert Joseph Evans* 2017-02-14T22:30:12.422+0000

[~mmerli]  Thanks

**Comment by sijie** [comment]
This issue is not valid anymore because GC thread doesn't use zookeeper directly any more. It is all hidden behind metadata API.
