### ISSUE TITLE
BookieRecoveryTest.ensurePasswordUsedForOldLedgers failing

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#631]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-1000

Reporter: Robert Joseph Evans 

Tests in error:
  BookieRecoveryTest.ensurePasswordUsedForOldLedgers[4] » BKNoSuchLedgerExists
  BookieRecoveryTest.ensurePasswordUsedForOldLedgers[5] » BKNoSuchLedgerExists

This has been happening in master recently both in Jenkins and on my Mac.  I'll try to take a look at it.

### Comments from JIRA

---
*Robert Joseph Evans* 2017-02-08T21:31:05.619+0000

The test fails consistently for org.apache.bookkeeper.meta.LongHierarchicalLedgerManagerFactory.

---
*Robert Joseph Evans* 2017-02-08T21:46:12.647+0000

It looks like this is a bug in BOOKKEEPER-873 and BOOKKEEPER-553.  Not sure how this test ever passed for them.  Essentially because the layout of the files changed for 2-4-4- to 3-4-4-4-4 it is not able to see the older ledgers.  It just ignores them.  It seems like we should be able to make it so that for IDs < max int we go with 2-4-4 and for > max int we go with 3-4-4-4-4.  Or we just disable this particular test because it will never work.  I would prefer to do the former because it provides a path towards a rolling upgrade.

[~knusbaum] said he was already looking at this so I think I will just hand it off to him.

---
*Robert Joseph Evans* 2017-02-08T21:48:08.873+0000

[~mmerli],

Would you mind adding in [~knusbaum] as a contributor so he can take over this JIRA?

---
*Matteo Merli* 2017-02-08T22:10:17.484+0000

[~revans2] Sure, added Kyle

**Comment by sijie** [comment]
Close this issue since it is an old issue migrated from JIRA. If it becomes flaky, we can reopen a new issue.
