### ISSUE TITLE
Implement guaranteed writes to specified number of racks

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#632]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-995

Reporter: Rithin Shetty 

With rackaware ensemble placement we get guaranteed writes to at least 2 different racks for every write quorum. We want to extend this such that user can ask for writes to at least 3 or more racks per write quorum. This is useful to ensure higher availability when one of the racks is already down: the remaining copies are guaranteed to be on different racks and hence can with stand another rack failure assuming the write quorum is 3.

**Comment by sijie** [comment]
This has been fixed by #2095
