### ISSUE TITLE
Placement policy to accomodate different types of ledger storage

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#633]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-916

Reporter: Venkateswararao Jujjuri (JV) @jvrao

As we start to use bookkeeper as long term storage, it may not be right use of resources to keep all copies of entry (write ensemble) on efficient storage. This feature is to come up with an intelligent placement that distributes entry copies across different classes of storage.

Simply put, say we have SSD based ledger storage and HDD based ledger storage on each system. Instead of putting all copies of entries either on SSD or on HDD, this placement policy maintains one copy on SSD and others on HDD.

- Have at least one copy on SSD and others on HDD.
   - Writer need to be aware of this classification
   - Replication logic need to be aware of this logic.

- While reading attempt to read from SSD first.
  - Reader also need to be aware of this logic.

This will push bookkeeper  towards the long term storage, also can be a stepping store towards introducing storage tiers in the future.

This has dependency/relation to

 https://issues.apache.org/jira/browse/BOOKKEEPER-912.
https://issues.apache.org/jira/browse/BOOKKEEPER-915

### Comments from JIRA

---
*Enrico Olivelli* 2016-04-07T06:36:08.651+0000

What kind of information is needed by your custom policy that cannot be get on current implementation? 
Do you need access to ledger Metadata?
do you need an extra custom value to be stored on Metadata?

---
*Enrico Olivelli* 2016-04-07T07:31:43.477+0000

we will need to store custom data on Bookie metadata and let the policy read (caching) that data

---
*Rakesh R* 2016-04-07T08:17:43.743+0000

Thanks [~jujjuri] for the new idea, interesting one. Is there an overall design document that one can follow?

Just few quick thoughts that comes in my mind:
# Are you planning to introduce storage tiers with this jira?. Is it like exposing storage types to the applications and suitable storage media can be chosen based on client preference.
# Reliability should not be affected if the preferred storage media is not avaialble. Probably need to define proper fall back policies.
# Way to configure new storage type (SSD, HDD, Memory etc). Admins will be interested to configure the storage media.

---
*Flavio Junqueira* 2016-04-07T09:12:35.818+0000

I really like the discussion about storage tiers. I'd like us to have a deeper discussion about it before endeavoring into a feature implementation. Here are some thoughts.

Long term storage and storage tiers have different aspects and implications. For long term storage, we probably want to have say archival bookies and have regular bookies replicating data there when they go cold rather than have clients directly writing into the cold storage layer. I'm assuming that the writes into cold storage are not necessarily fast and consequently you don't want to have it in the critical path of addEntry requests. Related to this observation is how often ledger data goes cold and that one needs to store long term. In the applications I've seen, it doesn't happen often, ledgers are rather short-lived, but I'd like to hear opinions.

On storage tiers, I assume we may want to be able to offer different ways of storing the data to client applications based on performance constraints, reliability, isolation. I think that making a distinction between SSDs and HDDs is a good one, and one tier we might want to care about because it might speed up things quite a bit for us is non-volatile RAM. 

---
*Venkateswararao Jujjuri (JV)* 2016-04-07T14:40:17.159+0000

1. No; Storage tiers is going to be much broader and deeper discussion. I will open a new Zira for that.

2. Absolutely. Reliability should not be affected. Preferred to be on specified medium and maintaining enough replicas is absolute must.

3. We may have to divide ledger storage directories into storage classes, placement policy to give the order of priority and Writer and replication logic will follow that.

No design document yet. :( Will come up with one soon.

---
*Venkateswararao Jujjuri (JV)* 2016-04-07T14:43:15.031+0000

[~fpj] Absolutely. Storage tiers is bigger discussion. That is the reason why  I said this can be a stepping stone towards that. Shall I open a Zira for that? or we open one when we actually start working on?

**Comment by sijie** [comment]
This has been fixed by #2095
