### ISSUE TITLE
Shell cmd to audit the ledgers and list bookie id requires updation

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#634]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-808

Reporter: Rakesh R 

The idea is to expose shell command to list the ledgers which needs to be updated using the 'updateledgers' command. This will be helpful for the administrators to ensure that the bookie id updation is completed.

### Comments from JIRA

---
*Sijie Guo* 2016-03-14T05:56:03.209+0000

[~rakesh_r] what do you think about this? shall we move to 4.5.0?

---
*Rakesh R* 2016-03-14T06:10:36.798+0000

Apart from the doc update this is the only known pending task for this feature. Can we move this jira to {{4.4.1}} minor release, considering that most of the major code changes for this feature is in and is available in 4.4.0(trunk).

---
*Venkateswararao Jujjuri (JV)* 2016-03-15T16:39:14.287+0000

anyone actively working on this?? [~reddycharan18@gmail.com] can you check if this is something you are looking into?

---
*Rakesh R* 2016-03-16T07:25:51.023+0000

bq. anyone actively working on this?? 
[~jujjuri] Would you be interested in proposing a patch. I'm happy to help in reviews.

**Comment by ivankelly** [comment]
bumping to 4.8.0
maybe this'll be done as part of the update to the cli (BP-27)

**Comment by sijie** [comment]
This has been fixed by #1968
