### ISSUE TITLE
AuditorLedgerCheckerTest is flakey

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#637]
JIRA: https://issues.apache.org/jira/browse/BOOKKEEPER-718

Reporter: Ivan Kelly @ivankelly

See:
https://builds.apache.org/job/bookkeeper-trunk/505/
& 
https://builds.apache.org/job/bookkeeper-trunk/509

Relevant errors attached.

### Comments from JIRA

---
*Sijie Guo* 2014-07-26T07:31:10.649+0000

ping the status. [~ikelly]

---
*Ivan Kelly* 2014-08-26T14:02:35.031+0000

Problem was that BookKeeperAdmin was taking ownership of a bookkeeper and zookeeper handle that was being passed in. This meant that when it was closed, it would clean up both. In the test in question, multiple bookkeeperadmin instances eventually shared the same zookeeper instance via auditor electors, so when one auditor elector was shut down, it would kill the zookeeper session of the other auditor electors and they weren't able to mark the unreplicated ledgers.

---
*Hadoop QA* 2014-08-26T14:30:08.730+0000

Testing JIRA BOOKKEEPER-718

Patch [0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch|https://issues.apache.org/jira/secure/attachment/12664390/0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch] downloaded at Tue Aug 26 14:25:41 UTC 2014

----------------------------

{color:red}-1{color} Patch failed to apply to head of branch

----------------------------

---
*Hadoop QA* 2014-08-26T15:45:50.280+0000

Testing JIRA BOOKKEEPER-718

Patch [0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch|https://issues.apache.org/jira/secure/attachment/12664390/0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch] downloaded at Tue Aug 26 15:41:43 UTC 2014

----------------------------

{color:red}-1{color} Patch failed to apply to head of branch

----------------------------

---
*Hadoop QA* 2014-08-26T16:35:50.353+0000

Testing JIRA BOOKKEEPER-718

Patch [0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch|https://issues.apache.org/jira/secure/attachment/12664390/0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch] downloaded at Tue Aug 26 16:31:43 UTC 2014

----------------------------

{color:red}-1{color} Patch failed to apply to head of branch

----------------------------

---
*Ivan Kelly* 2014-08-28T14:45:26.210+0000

Forgot to specify --no-prefix in previous patch.

---
*Hadoop QA* 2014-08-28T15:55:35.937+0000

Testing JIRA BOOKKEEPER-718

Patch [0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch|https://issues.apache.org/jira/secure/attachment/12664986/0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch] downloaded at Thu Aug 28 14:51:55 UTC 2014

----------------------------

{color:green}+1 PATCH_APPLIES{color}
{color:green}+1 CLEAN{color}
{color:red}-1 RAW_PATCH_ANALYSIS{color}
.    {color:green}+1{color} the patch does not introduce any @author tags
.    {color:green}+1{color} the patch does not introduce any tabs
.    {color:green}+1{color} the patch does not introduce any trailing spaces
.    {color:green}+1{color} the patch does not introduce any line longer than 120
.    {color:red}-1{color} the patch does not add/modify any testcase
{color:green}+1 RAT{color}
.    {color:green}+1{color} the patch does not seem to introduce new RAT warnings
{color:green}+1 JAVADOC{color}
.    {color:green}+1{color} the patch does not seem to introduce new Javadoc warnings
.    {color:red}WARNING{color}: the current HEAD has 23 Javadoc warning(s)
{color:green}+1 COMPILE{color}
.    {color:green}+1{color} HEAD compiles
.    {color:green}+1{color} patch compiles
.    {color:green}+1{color} the patch does not seem to introduce new javac warnings
{color:green}+1 FINDBUGS{color}
.    {color:green}+1{color} the patch does not seem to introduce new Findbugs warnings
.    {color:red}WARNING: the current HEAD has  Findbugs warning(s), they should be addressed ASAP{color}
{color:red}-1 TESTS{color}
.    Tests run: 863
.    Tests failed: 16
.    Tests errors: 20

.    The patch failed the following testcases:

.      testAsyncSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testSyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testSyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testSyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testPublishWithBookKeeperError[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testSyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testAsyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testSyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testAsyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testSyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testAsyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testPublishWithBookKeeperError[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)

{color:green}+1 DISTRO{color}
.    {color:green}+1{color} distro tarball builds with the patch 

----------------------------
{color:red}*-1 Overall result, please check the reported -1(s)*{color}

{color:red}.   There is at least one warning, please check{color}

The full output of the test-patch run is available at

.   https://builds.apache.org/job/bookkeeper-trunk-precommit-build/689/

---
*Hadoop QA* 2014-08-28T22:26:31.588+0000

Testing JIRA BOOKKEEPER-718

Patch [0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch|https://issues.apache.org/jira/secure/attachment/12664986/0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch] downloaded at Thu Aug 28 21:23:15 UTC 2014

----------------------------

{color:green}+1 PATCH_APPLIES{color}
{color:green}+1 CLEAN{color}
{color:red}-1 RAW_PATCH_ANALYSIS{color}
.    {color:green}+1{color} the patch does not introduce any @author tags
.    {color:green}+1{color} the patch does not introduce any tabs
.    {color:green}+1{color} the patch does not introduce any trailing spaces
.    {color:green}+1{color} the patch does not introduce any line longer than 120
.    {color:red}-1{color} the patch does not add/modify any testcase
{color:green}+1 RAT{color}
.    {color:green}+1{color} the patch does not seem to introduce new RAT warnings
{color:green}+1 JAVADOC{color}
.    {color:green}+1{color} the patch does not seem to introduce new Javadoc warnings
.    {color:red}WARNING{color}: the current HEAD has 23 Javadoc warning(s)
{color:green}+1 COMPILE{color}
.    {color:green}+1{color} HEAD compiles
.    {color:green}+1{color} patch compiles
.    {color:green}+1{color} the patch does not seem to introduce new javac warnings
{color:green}+1 FINDBUGS{color}
.    {color:green}+1{color} the patch does not seem to introduce new Findbugs warnings
.    {color:red}WARNING: the current HEAD has  Findbugs warning(s), they should be addressed ASAP{color}
{color:red}-1 TESTS{color}
.    Tests run: 863
.    Tests failed: 16
.    Tests errors: 20

.    The patch failed the following testcases:

.      testAsyncSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testSyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testSyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testSyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testPublishWithBookKeeperError[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testSyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testAsyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testSyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testAsyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testSyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testAsyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testPublishWithBookKeeperError[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)

{color:green}+1 DISTRO{color}
.    {color:green}+1{color} distro tarball builds with the patch 

----------------------------
{color:red}*-1 Overall result, please check the reported -1(s)*{color}

{color:red}.   There is at least one warning, please check{color}

The full output of the test-patch run is available at

.   https://builds.apache.org/job/bookkeeper-trunk-precommit-build/696/

---
*Hadoop QA* 2014-08-29T00:04:41.257+0000

Testing JIRA BOOKKEEPER-718

Patch [0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch|https://issues.apache.org/jira/secure/attachment/12664986/0001-BOOKKEEPER-718-AuditorLedgerCheckerTest-is-flakey.patch] downloaded at Thu Aug 28 23:01:27 UTC 2014

----------------------------

{color:green}+1 PATCH_APPLIES{color}
{color:green}+1 CLEAN{color}
{color:red}-1 RAW_PATCH_ANALYSIS{color}
.    {color:green}+1{color} the patch does not introduce any @author tags
.    {color:green}+1{color} the patch does not introduce any tabs
.    {color:green}+1{color} the patch does not introduce any trailing spaces
.    {color:green}+1{color} the patch does not introduce any line longer than 120
.    {color:red}-1{color} the patch does not add/modify any testcase
{color:green}+1 RAT{color}
.    {color:green}+1{color} the patch does not seem to introduce new RAT warnings
{color:green}+1 JAVADOC{color}
.    {color:green}+1{color} the patch does not seem to introduce new Javadoc warnings
.    {color:red}WARNING{color}: the current HEAD has 23 Javadoc warning(s)
{color:green}+1 COMPILE{color}
.    {color:green}+1{color} HEAD compiles
.    {color:green}+1{color} patch compiles
.    {color:green}+1{color} the patch does not seem to introduce new javac warnings
{color:green}+1 FINDBUGS{color}
.    {color:green}+1{color} the patch does not seem to introduce new Findbugs warnings
.    {color:red}WARNING: the current HEAD has  Findbugs warning(s), they should be addressed ASAP{color}
{color:red}-1 TESTS{color}
.    Tests run: 863
.    Tests failed: 16
.    Tests errors: 20

.    The patch failed the following testcases:

.      testAsyncSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testSyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testSyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testSyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testPublishWithBookKeeperError[1](org.apache.hedwig.server.integration.TestHedwigHubRegular)
.      testAsyncSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testSyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testAsyncUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testSyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testAsyncHubSubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testSyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testAsyncHubUnsubscribeWithInvalidSubscriberId[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)
.      testPublishWithBookKeeperError[1](org.apache.hedwig.server.integration.TestHedwigHubSSL)

{color:green}+1 DISTRO{color}
.    {color:green}+1{color} distro tarball builds with the patch 

----------------------------
{color:red}*-1 Overall result, please check the reported -1(s)*{color}

{color:red}.   There is at least one warning, please check{color}

The full output of the test-patch run is available at

.   https://builds.apache.org/job/bookkeeper-trunk-precommit-build/697/

---
*Sijie Guo* 2014-09-06T05:51:29.048+0000

patch looks good to me. +1.

committed as r1622830.

---
*Hudson* 2014-09-06T07:08:24.692+0000

FAILURE: Integrated in bookkeeper-trunk #766 (See [https://builds.apache.org/job/bookkeeper-trunk/766/])
BOOKKEEPER-718: AuditorLedgerCheckerTest is flakey (ivank via sijie) (sijie: rev 1622830)
* /zookeeper/bookkeeper/trunk/CHANGES.txt
* /zookeeper/bookkeeper/trunk/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/BookKeeperAdmin.java

---
*Charan Reddy Guttapalem* 2017-02-24T22:44:25.164+0000

Hey [~govindmenon] , wondering if you got chance to look at this flakiness. Tests of this testsuite are flapping both in the community builds and in our internal builds. Considering that this testsuite tests Auditor, I'm little hesitant to exclude this testsuite from testruns/testresults. 

[~jujjuri] FYI

---
*Govind Menon* 2017-02-24T22:54:12.503+0000

I'll take a closer look at this now (was working on another JIRA)

**Comment by sijie** [comment]
Close this issue since it was a issue migrated from JIRA. We can reopen a new one is it becomes flaky again.
