### ISSUE TITLE
Run bookkeeper on k8s using StatefulSets

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#681]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Currently the documentation provides an example to run bookkeeper on k8s using DaemonSet. It uses `hostIP` and `hostPort` for advertising the bookies. However in some environments (e.g. K8S on DC/OS), `hostIP` and `hostPort` doesn't work. 

Issues reported in twitter/heron#2500

Alternatively, we should provide an example to run bookkeeper on k8s using StatefulSets.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*nice-to-have*

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by mjschmidt** [comment]
Much appreciated!
