### ISSUE TITLE
Define a LedgerEntries interface for read entries

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#693]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

In the new API proposed in #506 , we return `Iterable<LedgerEntry>` for read entries. It is a bit problematic when returning multiple iterators and have no ability to release the entry buffers hold by ledger entries.

I am proposing introducing a `LedgerEntries` interface for wrapping the entries.

```
interface LedgerEntries extends Iterable<LedgerEntry>, AutoCloseable {

       LedgerEntry getEntry(long entryId);

       Iterator<LedgerEntry> iterator();

}
```

so:

- the implementation can increase the reference of the buffers when creating an iterator
- we can make `LedgerEntries` a recycle object, and it is returned to the pool when #close() is called.
- on #close(), it also releases all the references to release resources.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*blocker* for `4.6.0` release.

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by jiazhai** [comment]
would like to do it.

**Comment by ivankelly** [comment]
In this case, is it the LedgerEntries object that owns all entries, and is responsible for closing (releasing the refs)?
