### ISSUE TITLE
Slack signup link is wrong

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#724]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

Open https://bookkeeper.apache.org/community/slack/ and click the self-register link.

- What did you expect to see?

I should see the signup link not the signin link.

- What did you see instead?

I saw the signin link. The link of `https://apachebookkeeper.herokuapp.com/` was pointed to `http://apachebookkeeper.slack.com/`.

**Comment by jiazhai** [comment]
Thanks @sijie for reporting this. PR #725 opened for it.
