### ISSUE TITLE
fix getKeyName in ComponentConfiguration.

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#733]
In getKeyName, there seems missed a "." between "componentPrefix" and "keyName", 
when a child class passed in a componentPrefix, like "compX", then the getKeyName() would return a key name as: compX"name".
```
public abstract class ComponentConfiguration implements Configuration {

    protected static final String DELIMITER = ".";

    protected String getKeyName(String name) {
        return this.componentPrefix + name;
    }
```

**Comment by sijie** [comment]
I think this has been fixed in one of the table requests PRs. Closed it.
