### ISSUE TITLE
create assertEventuallyEquals for unit test, and do the clean up

### ISSUE THREAD

**Issue by zhaijack** [apache/bookkeeper#751]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
in unit test, some times, it is not avoidable to use sleep, then do the assert.  This sleep should not wait too much long. 

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have

3. Provide any additional detail on your proposed use case for this feature.
we could create a utility method in TestUtils, to do this kind of work:
```
assertEventuallyEquals(x, y, timeout, units) {
     long maxMillis = units.toMiliis(timeout);
     while (x != y && maxMillis > 0) {
         maxMillis -= 10;
         Thread.sleep(10);
    }
    assertEquals(x, y);
}
```
We could use this issue for this work, and clean up some of current test cases.

**Comment by eolivelli** [comment]
@zhaijack  @sijie @ivankelly 
usually I have a "waitForCondition" method in tests
like
```
public static void waitForCondition(Callable<Boolean> test, long maxMillis){
     while (maxMillis > 0) {
         if (test.call()){
            return;
         } 
        maxMillis -= 10;
         Thread.sleep(10);
    }
   fail("condition not me in time");
}
```
and something like:
```
public static void waitForCondition(Callable<Boolean> test, long maxMillis, Runnable spinner){
     while (maxMillis > 0) {
         if (test.call()){
            return;
         } 
         spinner.run();
        maxMillis -= 10;
         Thread.sleep(10);
    }
   fail("condition not me in time");
}
```

**Comment by ivankelly** [comment]
I'd prefer to have assert in the name, so that it's clear that its checking something that can kill the test

**Comment by eolivelli** [comment]
@ivankelly mine was just an example, maybe we can have somthing like
assertConditionEventuallyTrue
can't figure a good name

**Comment by jiazhai** [comment]
@eolivelli, That is great.
