### ISSUE TITLE
BP-20: Github workflow for bookkeeper proposals

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#761]
**BP**

This is the master ticket for tracking BP-20 :

Implementing a github workflow for bookkeeper proposals, so all the bookkeeper proposals can be reviewed as code changes, and they can be maintained in the same way as how we maintain documentation.

Proposal PR - #760

**Comment by ivankelly** [comment]
How should this deal with failed/rejected proposals? These proposals will have BP numbers allocated, but they'll not be merged (or will they)?

**Comment by sijie** [comment]
@ivankelly good point. for the failed/rejected proposals, in the BP PR, update the proposal list page to add them to the "Discard" section. so we have all the history about the proposal, which we can revisit them later and know all the context. I will try to send out a PR to add to the proposal workflow.

**Comment by sijie** [comment]
@ivankelly I sent a PR update the workflow. please take a look.
