### ISSUE TITLE
Codahale stats providers should be in a different package name

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#762]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Codahale stats providers are sharing same package name with the stats library `org.apache.bookkeeper.stats`. We should consider moving them to their own package name.

Codahale => `org.apache.bookkeeper.stats.codahale`

For BC concerns, we need to do this in two phases:

- in 4.7, we copy the files but still have the old files for BC. but mark the old classes as deprecated.
- in 4.8, we remove the old files.

because the class names are used for reflection.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*should-have*

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by jiazhai** [comment]
Seems 4.7 part is done by PR #1257, how about change this issue into milestone 4.8.0?
