### ISSUE TITLE
Make build pass using JDK9

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#778]
Fix poms and correct warnings in order to make the build pass using java9.

**Comment by sijie** [comment]
@eolivelli I think there is already an issue for this - #569  you can decide which one to use and mark the other one as duplicated.

**Comment by eolivelli** [comment]
@sijie  this is not really a duplicate.

BK 4.5 runs well on Java9 but you cannot "build" it with Java9 onwards (and JDK10).

I have a local branch which is able to run "mvn clean install" using JDK9 as JAVA_HOME.
There are only some plugin upgrades and we have to disable the check for deprecated APIs, like Observable. 

The pace of Java now will be faster, 1 major release every 6 months and they will drop soon all the stuff marked deprecated "for removal".

**Comment by sijie** [comment]
@eolivelli I am not sure what is the real difference here. you are trying to make bookkeeper complied and run with java 9, no?

I know the java community is moving fast with releases. but users are not. there are still users using java6 and java7, so I would expect to have bookkeeper support java8 for a long time. we are not going to deprecate java 8 soon. I am not fine we make it compiled and run with java9, but definitely not moving to java9.

**Comment by eolivelli** [comment]
@sijie I think that we must support java8 and we will do for a long time.

I think It is better that the build is doable with java8 onwards, not just having jdk8.

In my humble opinion we should run away from deprecated APIs as soon as possible.
In fact we do not want usages of deprecated APIs, actually we are using deprecated java APIs which will be dropped soon.

I think there are different  issues and multiple tasks to be done and so I am creating several github issues.
It would be good to create a jenkins job which runs tests on jdk9, this will be feasible only when mvn clean install works on java9.
Soon we will have users which use java9 at least for the client.
Myself I am porting applications to run both on java 8 and java9 (no modules, only runtime and new APIs)

**Comment by sijie** [comment]
> I think there are different issues and multiple tasks to be done and so I am creating several github issues.

If there are multiple issues, please have a master issue for tracking the sub-tasks. It is unobvious to see what is really needed for java9 by looking into these two issues. I was lost there.

> we should run away from deprecated APIs as soon as possible.

+1 for removing deprecated apis. please file an issue for that. if that is part of java9 efforts, please link it to the master issue.

**Comment by eolivelli** [comment]
For the deprecated API removal there is already this issue #326. We need to replace java.util.Observable.
I will create a master ticket, I think it is a very good idea. Will be back soon on this topic
