### ISSUE TITLE
BP-21: New API close inconsistencies

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#789]
Bookkeeper proposal

This is the master ticket for tracking BP-21

There are a couple of inconsistencies, overloading of meaning and general shortcomings of how close is accessed in the new api (and also in the old api, but I'm not proposing we change that). 

This BP will describe the shortcomings and suggest solutions.

Proposal PR - #790

**Comment by sijie** [comment]
Close this BP as `status/notaproblem` for now. The proposal content is merged.
