### ISSUE TITLE
Bookies should not try to replicate ledgers whose ensemble size is 1

### ISSUE THREAD

**Issue by yush1ga** [apache/bookkeeper#793]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
The ledger whose ensemble size is 1 was created and it was not deleted
when we used `simpletest` or  `bookiesanity` resulted failure.

- What did you expect to see?
When the bookie which has the ledger mentioned above is shut down or crashed,
it is not necessary to replicate the ledger.

- What did you see instead?
The other bookies tried to replicate the ledger.
However, since it was impossible to replicate it, the ledger continued to remain in `underreplicated` list.

- The version of bookkeeper
4.3.1.72-yahoo

**Comment by sijie** [comment]
it sounds reasonable to me, not to replicate ledgers whose ensemble size is 1.

**Comment by eolivelli** [comment]
@sijie make sense to me too

**Comment by shoothzj** [comment]
You can try with the latest release verison. I test it ok.
