### ISSUE TITLE
OrderedSafeExecutor exposes shaded guava API ListenableFuture

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#804]
I don't know how to classify this, as a feature request or bug, anyhow the problem is this:

org.apache.bookkeeper.util.OrderedSafeExecutor uses ListenableFuture which is in Guava and we are shading Guava.

Building a downstream project which uses OrderedSafeExecutor#submitOrdered
`public ListenableFuture<?> submitOrdered(Object orderingKey, SafeRunnable r)`

I get this error, compiling the project on Java 9 (BK is is the classpath, not using the module-path), the error is not present while using Java8

```
XXXX.java:[84,26] error: cannot access ListenableFuture
  class file for bk-shade.com.google.common.util.concurrent.ListenableFuture not found
```

Is OrderedSafeExecutor considered public API or internal API ?
if it is considered "public API" we have to drop references to shaded libraries, if we want to consider it "internal API" we can mark this issue as "won't fix"

From a brief analysis of code on BK (not dealing with DL for instance) the returned value of that method is never used so we could:
- drop the return type
- change the return type to "Future"

**Comment by eolivelli** [comment]
@sijie  @ivankelly what do you think ?

**Comment by ivankelly** [comment]
It's not a public API, though I've seen other use it. In any case, we should make this use a CompletableFuture. We were on java7 when this was first written.

**Comment by eolivelli** [comment]
I found it is used in PendingReadOp#issueSpeculativeRequest so the change won't be trivial. 
Yes we should move to CompletableFuture, that will be feasible

**Comment by sijie** [comment]
It is a non-public or limited private API. The problem seems to appear when using a shaded jar, no? If you are using a non-shaded jar, I don't think the issue would appear.

Given it is non-public api and only related a shaded jar, I am not sure if there is a strong need to switch to CompletableFuture, because the underlying executors are `ListeningScheduledExecutorService`. My take on this: 1) we can simply fix the shading rule, by changing 'bk-shade' to 'bkshade', to make it compiled with java 9; 2) defer changing it to `CompletableFuture` when they are needed.  BTW, personally I don't think this should be labelled as `important`.

**Comment by eolivelli** [comment]
@sijie I am fine with considering this class an internal.API and there is no need to encourage other projects to use it. 
I am closing this issue as 'won't fix'
Maybe it would be better something like 'not a problem'

**Comment by sijie** [comment]
sorry, I think we still fix the shading rule, no? 

> Maybe it would be better something like 'not a problem'

good idea.

**Comment by sijie** [comment]
added a label `status/notaproblem`. However I didn't change the status of this issue. because I think we still need to address the shading rule issue, unless I misunderstood the issue here.

**Comment by eolivelli** [comment]
I think that this problem of uncompilable code which uses relocated code is somehow a good side effect. It prevents client code to use things that we want to hide.
We want to hide our version of Guava to downstream projects, so it is good that those projects cannot consume our tweaked version of Guava.
The same problem with protobuf in 4.4 let us see that it was not possible to implement a custom AuthPlugin. If there error was not present maybe at that time I would have used a relocated Guava.

So I think it is good to have such weird package name for guava and protobuf

**Comment by sijie** [comment]
okay. I will close this as "Not a problem"
