### ISSUE TITLE
while release 4.6.0, meet some errors in release_guide.md

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#805]
during preparing release 4.6.0, there was some errors meet,
1, 
`git tag -d ${VERSION} && git push apache :refs/tags/${VERSION}`
should be
`git tag -d release-${VERSION} && git push apache :refs/tags/release-${VERSION}`

2, .m2/settings.xml may not take effect for  "Apache Nexus repository" setting.

**Comment by eolivelli** [comment]
Which problem did you have on settings.xml?

**Comment by jiazhai** [comment]
@eolivelli, seems .m2/settings not take effect, I have to also set /usr/local/Cellar/maven/3.5.0/libexec/conf/settings.xml with the servers on my Mac.
