### ISSUE TITLE
Issues in Prometheus stats provider

### ISSUE THREAD

**Issue by jiazhai** [apache/bookkeeper#848]
In https://github.com/apache/incubator-pulsar/issues/922, we try to run both pulsar and bookie together, and this may cause 2 prometheus http Servlet started, one for broker and one for bookie.

we may need to provide a flag to disable starting prometheus stats provider in bookie side.

As as Matteo point out, BK Prometheus plugin is using a private metrics registry instead of the global static registry

**Comment by sijie** [comment]
This is addressed at #1394
