### ISSUE TITLE
slf4j logging: use {} formatting instead of string concatenation

### ISSUE THREAD

**Issue by pasha-kuznetsov** [apache/bookkeeper#861]
Currently logging is done via both `{}` slf4j formatting, and `+` string concatenation. The former `{}` is preferrable for consistency, readability and [performance](https://www.slf4j.org/faq.html#logging_performance).

**Example**
The following
```
LOG.debug("Unsetting success for ledger: " + lh.ledgerId + " entry: " + entryId
           + " bookie index: " + bookieIndex);
```
would be changed to
```
LOG.debug("Unsetting success for ledger: {} entry: {} bookie index: {}",
          lh.ledgerId, entryId, bookieIndex);
```

**Comment by pasha-kuznetsov** [comment]
Related change is that then many `if (LOG.isDebugEnabled())` checks can be removed as they are done automatically by slf4j without extra overhead in case of `{}` formatting, e.g.:
```
            if (LOG.isDebugEnabled()) {
                LOG.debug("Failed to close ledger {} : ", ledgerId, re);
            }
```
is then simplified to
```
            LOG.debug("Failed to close ledger {} : ", ledgerId, re);
```

**Comment by sijie** [comment]
@pasha-kuznetsov regarding `if (LOG.isDebugEnabled())`, some of them can be simplified, some can't. so it is kind of depends. so in general, we try to put `if (LOG.isDebugEnabled())` there

**Comment by sijie** [comment]
This has been fixed.
