### ISSUE TITLE
LegacyHierarchicalLedgerManager: fix erroneous exception during race

### ISSUE THREAD

**Issue by athanatos** [apache/bookkeeper#869]
getLedgerRangeByLevel current throws an IOException if the node to be listed does not exist.  This can validly happen if there is a concurrent recursive removal of a leaf node.  Instead, return an empty list in that case.

I'll have a PR in the next day or two for this one.

**Comment by shoothzj** [comment]
@athanatos Hello, do you still want to work on this?

**Comment by athanatos** [comment]
I'm not working on bk these days -- feel free to close/reassign.

**Comment by shoothzj** [comment]
https://github.com/apache/bookkeeper/blob/d7b2df47452cc296a1b3c0b6a9d018d3dd3cc5e9/bookkeeper-server/src/main/java/org/apache/bookkeeper/meta/LegacyHierarchicalLedgerManager.java#L269-L273
