### ISSUE TITLE
Integration/compatibility tests based on docker

### ISSUE THREAD

**Issue by ivankelly** [apache/bookkeeper#903]
With the changes coming in from yahoo, we need to ensure that we're not breaking compatibility. The current compatibility tests are horrible to work with. This issue proposes setting up an integration test framework, based on docker, with different versions of bookkeeper running in different JVMs.

This is required to test #898 correctly.

**Comment by eolivelli** [comment]
@ivankelly  @sijie I think the approach based on Arquillian maybe be better, if I understand it correctly. I never used Arquillian but I am afraid that spawing containers could be too complex for this case.
We can use isolated classloaders (and I think Arquillian uses this approach)

Anyway every idea and approach is welcome, I am fine with the docker approach too.
Maybe it would limit tests execution from contributors as it is not always possible to have docker on developer machines (for instance in my company we have nasty rules of this kind)

**Comment by sijie** [comment]
> We can use isolated classloaders (and I think Arquillian uses this approach)

Not sure if Arquillian uses the approach you are suggesting. But If it does, we should just go with Arquillian, no? Reinventing a testing framework is not fun.

**Comment by ivankelly** [comment]
I don't think we should go with a classloader based approach. Classloader
based would allow current jars versions, but that's all. These tests will
be used to test failure cases like network partitions, which we can't test
with junit. Each node needs to appear as its own machine for this, which is
why I'm suggesting docker. The underlying assumption is that it will be
with arquillian too, but I'd like to see how that works too.

I would suspect that these tests will be too heavy to run on developer
machines in any case, and I wouldn't expect a dev to run them before
submitting a patch. Rather, they would be run as part of the pre commit.

**Comment by eolivelli** [comment]
I have some idea for the classloader approch we can try with both and maybe they could be complementary. I think the docker approach is well suited for running bookies but it will be trickier for clients, dually it will be simpler to create tests for the client with the CL approch.
I will create another issue with my proposal

**Comment by sijie** [comment]
@eolivelli you can use this issue here but just send a PR for your proposal. we don't need to have two different issues for tracking changes for same purpose.

**Comment by ivankelly** [comment]
#930

**Comment by ivankelly** [comment]
This has been implemented in all the linked PRs.
