### ISSUE TITLE
Troubles setting up environment for website builder script (expecially on Fedora 25,26,27)

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#961]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?
run this command in subdirectory "site"
```make setup```

- What did you expect to see?
system correctly set up for building website

- What did you see instead?
```
[enrico.olivelli@xxxxx site]$ make setup
gem install bundler \
	-v 1.15.1 \
	--no-rdoc \
	--no-ri
Successfully installed bundler-1.15.1
1 gem installed
NOKOGIRI_USE_SYSTEM_LIBRARIES=true bundle _1.15.1_ install \
	--path vendor/bundle
Your Ruby version is 2.3.4, but your Gemfile specified 2.4.1
Makefile:14: set di istruzioni per l'obiettivo "setup" non riuscito
make: *** [setup] Errore 18
```

Can we have some other way to run the builder, maybe running the builder using a docker container  ?
On every (fedora based) machine I try to setup the env it is always very difficult to make it run

**Comment by sijie** [comment]
@eolivelli there is a docker file. https://github.com/apache/bookkeeper/blob/master/site/docker/run.sh you can use this to get into a docker environment with Ruby 2.4.1 and run the commands.

**Comment by eolivelli** [comment]
It works like a charm!
