### ISSUE TITLE
Installation instructions are bad due to 4.6.1 not existing in suggested mirror

### ISSUE THREAD

**Issue by dancollins34** [apache/bookkeeper#982]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

Attempted to follow the installation instructions,

- What did you expect to see?

http://apache.claz.org/bookkeeper/bookkeeper-4.6.1/bookkeeper-4.6.1-src.tar.gz exists

- What did you see instead?

http://apache.claz.org/bookkeeper/bookkeeper-4.6.1/bookkeeper-4.6.1-src.tar.gz does not exist, 404 instead

**Comment by eolivelli** [comment]
Sorry,  we have updated the website before actually releasing 4.6.1. Currently latest release is 4.6.0

**Comment by sijie** [comment]
@dancollins34 we just released 4.6.1 two days ago. please check the download links and play with the new release and give us feedback.

we will improve our release flow to avoid this happen again.
