### ISSUE TITLE
Build failures on java 9 for Mac

### ISSUE THREAD

**Issue by dancollins34** [apache/bookkeeper#984]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

Downloaded bookkeeper tarball for version 4.6.0
ran mvn package

- What did you expect to see?

build success

- What did you see instead?

build failure (java 9.0.1 , brew cask version)

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project bookkeeper-stats-api: Fatal error compiling: java.lang.NoClassDefFoundError: com/sun/tools/javac/file/BaseFileObject: com.sun.tools.javac.file.BaseFileObject -> [Help 1]

-notes

build success (java 1.8.0_152, brew cask version)
high Sierra 10.13.3 Beta (17D25b)

**Comment by sijie** [comment]
@dancollins34 are you using oracle jdk or open jdk? I am not sure about "brew cask version", is it an openjdk? Have you tried oracle jdk?

We have travis ci and jenkins ci building/testing both branch 4.6 and latest master using oracle jdk 9. I checked all the ci jobs, they seems to work well with oracle jdk. but apparently we don't have a ci job that covers openjdk 9. will have to look into how to fix it.

https://travis-ci.org/apache/bookkeeper/jobs/328186006

**Comment by dancollins34** [comment]
@sijie this is the standard oracle jdk 9.0.1 running on osx. Do you intend to support osx for your builds or Linux only?

**Comment by sijie** [comment]
@dancollins34 we supported both mac and linux. most of our committers are using mac as the development environment. and we have travis CI running on osx to ensure the builds have no problems.

**Comment by sijie** [comment]
@dancollins34 actually. I think I confused myself. so 4.6.0 doesn't support java 9. java 9 support is a recent change, which should be released in the coming releases 4.6.1 (in a week also) and 4.7.0 (in a month also). 

if you want to play with bookkeeper in java 9, you can either checkout master or branch-4.6. sorry for making you confused in my previous comments.

**Comment by dancollins34** [comment]
Okay, thanks for clearing that up!
