### ISSUE TITLE
Bookie Identifier / Bookie Port 

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#999]
A general question coming up when running bookkeeper in a scheduler environment (e.g. mesos, aurora): can bookkeeper use dynamic port?  Currently the port is used both as bookie identifier and also as the communication port stored in metadata. We'd better to think about how to better improve this. 

This should also incorporate twitter's change about port splitting - support different ports for read/write purposes, so write/read traffic can be managed through some kernel traffic control tools.

**Comment by sijie** [comment]
This needs a BP to raise a discussion.

**Comment by shoothzj** [comment]
closed by no updates, feel free to reopen it.
